### ISSUE TITLE
card_width option of  top-langs API has problem 

### ISSUE THREAD

**Issue by sehoon787** [anuraghazra/github-readme-stats#1941] opened 2022-08-12 15:38 UTC
I created my vercel. And I can surely search my private repo as well to use top-langs API with my url.
But I think top-langs API's card_width option for setting 445 has some problem showing only 5 less languages.
When I set "card_width" option as the number bigger than 445 even just 446, then top-langs api prints every languages successfully. 

Do you think this line has any problem?

`https://github-readme-stats-git-master-sehoon787.vercel.app/api/top-langs/?username=sehoon787&custom_title=⚡Alien%20Coder's%20Most%20Used%20Languages&layout=compact&card_width=445&bg_color=0d1117&title_color=ffffff&text_color=ffffff&icon_color=db1cff&hide_border=true&count_private=true&langs_count=10&hide=jupyter%20notebook`

And next url works very well.

`https://github-readme-stats-git-master-sehoon787.vercel.app/api/top-langs/?username=sehoon787&custom_title=⚡Alien%20Coder's%20Most%20Used%20Languages&layout=compact&card_width=446&bg_color=0d1117&title_color=ffffff&text_color=ffffff&icon_color=db1cff&hide_border=true&count_private=true&langs_count=10&hide=jupyter%20notebook`

**Comment by rickstaa** [comment] 2022-08-13 08:17
@sehoon787 Thanks for your bug report. I checked the cards and cannot reproduce your problem (see examples below). The only design flaw I see is that we allow the width below the title width without using ellipsis for the text overflow. Can you maybe provide me with an example of where this issue occurs?

**Card_width 100**

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=100&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=100&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)
```

**Card_width 445**

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=445&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=445&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)
```

**Card_width 446**

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=446&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&card_width=446&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)
```

**Comment by sehoon787** [comment] 2022-08-15 09:39
I also failed to reproduce this bug again. Because after about 4 hours my successful top-langs API failed to show other language(private repo with Dart) again suddenly. It's hard to explain the routine for this bug. I just leave my successful api and disappeared few hours later. I experienced this but before I use Vercel too. But other API works well and cool.

**Comment by rickstaa** [comment] 2022-08-16 07:45
@sehoon787 Ah, I see. If it's okay with you, I will close this issue now since it is tough for me to reproduce your problem. I think the best thing to do is that when it happens, you build the project locally (see https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md) and debug it using [vscode](https://code.visualstudio.com/). That way, you can put a breakpoint at the card creation code and see what is going on. Let me know if you find additional information about the problem so I can reproduce it.

**Closed by rickstaa** 2022-08-16 07:45 UTC
Labels: bug, question

**Comment by sehoon787** [comment] 2022-08-16 07:59
Ok. I will try it soon. Thanks
