### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by JLLeitschuh** [anuraghazra/github-readme-stats#1463] opened 2021-11-16 22:13 UTC
**Describe the bug**

Loading for my profile seems to be broken. In the defense of this project though, I have a bit of an unusual profile. 😆 

The error I see is:
> Cannot read property 'data' of undefined

**Expected behavior**

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
[If applicable, add screenshots to help explain your problem.](https://github-readme-stats.vercel.app/api?username=JLLeitschuh)

![Screen Shot 2021-11-16 at 5 12 00 PM](https://user-images.githubusercontent.com/1323708/142074302-05489767-9422-455e-9682-2f4be6227e82.png)

**Additional context**

I have ~1.2k repositories against my account. I'm in 56 GitHub organizations. Across a span of two days last year I generated 1,596 PRs from my account, and across another two days I generated a further 3,500 something PRs from my account. I'm also a GitHub Star.

**Comment by anuraghazra** [comment] 2021-11-17 12:56
Hi @JLLeitschuh thanks for reporting the issue. 

Yes there are few people who are facing similar issues, seems like there is something wrong with GitHub's API. 

@rickstaa and I even contacted github support for one of the similar issues with github's api's getting timed out. 
We'll look into whats happening with this.

**Comment by anuraghazra** [comment] 2021-11-17 13:08
Here, see how the graphql API is timing out. 

![image](https://user-images.githubusercontent.com/35374649/142206474-46527f5d-fe55-4414-9280-6fc646727cbc.png)

**Comment by JLLeitschuh** [comment] 2021-11-17 13:53
I have lots of contacts inside of GitHub, could you include in a response the full GraphQl query used here? I can get in contact with some of the GH folks to see if I can get this resolved sooner.

**Comment by rickstaa** [comment] 2021-11-17 14:06
@JLLeitschuh As pointed out by @anuraghazra the Github Support is looking into this problem. I however have not received an update. I will update https://github.com/anuraghazra/github-readme-stats/issues/1406 when I hear from them. The GitHub support ticket number is `1369436`.

**Comment by anuraghazra** [comment] 2021-11-17 14:07
Here's the GraphQL query

Here's the previous issue where we were discussing the same problem but we found a workaround:
https://github.com/anuraghazra/github-readme-stats/issues/1406

Here's the hotfix which I did: https://github.com/anuraghazra/github-readme-stats/pull/1409

```gql
        user(login: "JLLeitschuh") {
          name
          login
          contributionsCollection {
            totalCommitContributions
            restrictedContributionsCount
          }
          repositoriesContributedTo(first: 1, contributionTypes: [COMMIT, ISSUE, PULL_REQUEST, REPOSITORY]) {
            totalCount
          }
          pullRequests(first: 1) {
            totalCount
          }
          openIssues: issues(states: OPEN) {
            totalCount
          }
          closedIssues: issues(states: CLOSED) {
            totalCount
          }
          followers {
            totalCount
          }
          repositories(first: 100, ownerAffiliations: OWNER, orderBy: {direction: DESC, field: STARGAZERS}) {
            totalCount
            nodes {
              stargazers {
                totalCount
              }
            }
          }
        }
```

@rickstaa can you share the previous ticket number of the report which we sent to github with @JLLeitschuh?

**Comment by VincentLanglet** [comment] 2022-02-15 21:02
I do have the same error with https://github-readme-stats.vercel.app/api?username=VincentLanglet

**Comment by rickstaa** [comment] 2022-02-18 09:29
@VincentLanglet thanks a lot for your comment. Do you also get a timeout error when you fetch the data in the https://docs.github.com/en/graphql/overview/explorer.

**Comment by rickstaa** [comment] 2022-02-18 09:43
@VincentLanglet ah that looks like a timeout problem and might be related to https://github.com/anuraghazra/github-readme-stats/issues/1406. Unfortunately, we have no updates from the Github team on whether they are planning to fix this.

**Comment by JLLeitschuh** [comment] 2022-02-23 16:11
Can I get a link to the support ticket? I can pass this along to the GitHub team, I have some direct connections I can leverage.

**Comment by rickstaa** [comment] 2022-02-23 16:16
@JLLeitschuh Thanks a lot for offering to bring this issue to the attention of the GH team. The ticket is already closed and is under a private link. The ticket number, however, is `1369436`.

**Comment by marcospb19** [comment] 2023-01-25 05:07
For other people that end up on this issue, I solved this by choosing classic tokens instead of fine-grained ones.

![image](https://user-images.githubusercontent.com/38900226/214484269-ef4be189-4eba-4b0c-b464-494f27b91b17.png)

So one of the reasons for this error, assuming there are multiple, might be the token type (or the fine grained config I did wrong).

**Comment by rickstaa** [comment] 2023-05-06 09:07
Duplicate of #https://github.com/anuraghazra/github-readme-stats/issues/1406.

**Closed by rickstaa** 2023-05-06 09:07 UTC
Labels: bug, upstream
