### ISSUE TITLE
Wakatime user not found

### ISSUE THREAD

**Issue by MorganJay** [anuraghazra/github-readme-stats#2757] opened 2023-05-29 07:44 UTC
### Describe the bug

I've had this card on my profile for a while and it always worked fine, with my Wakatime accounts since 2020 [my account](https://wakatime.com/@Morgan_Jay) but now it shows the error on my Github Profile page

### Expected behavior

Show Wakatime stats

### Screenshots / Live demo link

[![MorganJay's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Morgan_Jay&theme=midnight-purple)](https://github.com/anuraghazra/github-readme-stats)

**Comment by qwerty541** [comment] 2023-05-29 08:16
Your card works with `&range=last_7_days` parameter. See #2754 for more information.

`https://github-readme-stats.vercel.app/api/wakatime?username=Morgan_Jay&theme=midnight-purple&range=last_7_days`

<img src="https://github-readme-stats.vercel.app/api/wakatime?username=Morgan_Jay&theme=midnight-purple&range=last_7_days" />

**Comment by rickstaa** [comment] 2023-05-29 21:41
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/2698. Will be fixed if https://github.com/anuraghazra/github-readme-stats/pull/2707 is merged. @Zo-Bro-23 can you maybe approve this pull request so that we can merge it?

**Closed by rickstaa** 2023-05-29 21:41 UTC
Labels: bug

**Comment by MorganJay** [comment] 2023-05-30 07:06
Thanks @qwerty541 @rickstaa

**Comment by qwerty541** [comment] 2023-05-30 22:02
> Duplicate of #2698. Will be fixed if #2707 is merged. @Zo-Bro-23 can you maybe approve this pull request so that we can merge it?

Hey, @rickstaa! If i correctly understand you need at least one another collaborator to approve your pull request before merging due to repository branch protection rules? In that case you can ping Anurag to send me an invitation, i will approve your pull request instantly after receiving.

**Comment by rickstaa** [comment] 2023-05-31 06:34
> > Duplicate of #2698. Will be fixed if #2707 is merged. @Zo-Bro-23 can you maybe approve this pull request so that we can merge it?
> 
> Hey, @rickstaa! If i correctly understand you need at least one another collaborator to approve your pull request before merging due to repository branch protection rules? In that case you can ping Anurag to send me an invitation, i will approve your pull request instantly after receiving.

Thanks! I just sent him a reminder on Twitter.
