### ISSUE TITLE
 Could not fetch total commits. 

### ISSUE THREAD

**Issue by PriyanshK09** [anuraghazra/github-readme-stats#3267] opened 2023-09-21 12:34 UTC
### Describe the bug

The commit report isn't loading as intended when the tag : &include_all_commits=true is being use

**Comment by qwerty541** [comment] 2023-09-21 17:13
@PriyanshK09 Thanks for the report! You can see this when upstream GitHub API respond with error due to some reason during fetching stats card data. Should be resolve automatically after some time. Currently stats card in your profile works well. After merging https://github.com/anuraghazra/github-readme-stats/pull/3255 error message will be improved to be more clear. 

Recently we merged https://github.com/anuraghazra/github-readme-stats/pull/3238 which improved confusing behavior of showing 0 commits when upstream API feails, currently we show an error instead, i'm curious what do you think about this change.

Closing as duplicate of https://github.com/anuraghazra/github-readme-stats/issues/3243

**Closed by qwerty541** 2023-09-21 17:13 UTC
Labels: bug

**Comment by rickstaa** [comment] 2023-09-21 18:35
We merged https://github.com/anuraghazra/github-readme-stats/pull/3255.

**Comment by qwerty541** [comment] 2024-06-27 16:38
> I started experiencing this issue today with the `&include_all_commits=true` parameter today. It was working for a few hours, then stopped working when I deleted a private repo. Error is still occurring 12 hours later.

Answered your question there https://github.com/anuraghazra/github-readme-stats/issues/3264#issuecomment-2195185876
