### ISSUE TITLE
[Sever Problem] Maximum retries exceeded

### ISSUE THREAD

**Issue by jujumilk3** [anuraghazra/github-readme-stats#1763] opened 2022-05-18 10:53 UTC
**Describe the bug**
Service doesn't work

**Expected behavior**
I think It's a kind of traffic problem as i captured.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
<img width="526" alt="스크린샷 2022-05-18 오후 7 49 16" src="https://user-images.githubusercontent.com/41659814/169022351-d751d8c9-5ae1-484d-ab3a-6ea53c9f7d91.png">
you can just visit my profile
https://github.com/jujumilk3

**Comment by carloocchiena** [comment] 2022-05-18 10:56
I am experiencing the same issues, actually it start occurring two days ago.

@jujumilk3 I suggest to amend the title of the issue with something more talkative, such as "Maximun retries exceeded issues" so other people can see there's already an issue going on.

**Comment by krau5** [comment] 2022-05-18 10:58
Same thing.
I am agree with @carloocchiena. 
@jujumilk3 you should change the title.

**Comment by rickstaa** [comment] 2022-05-18 11:39
@jujumilk3 Thanks for creating this issue. This issue is related to #1471. Please use https://github.com/anuraghazra/github-readme-stats/issues/1471#issuecomment-979306704 as a workaround.

**Comment by rickstaa** [comment] 2022-05-18 11:40
@anuraghazra, although it is a duplicate of #1471, I think I will keep this issue open for a while. I have been closing similar issues all this morning, and people don't seem to find the #1471. See my suggestion at https://github.com/anuraghazra/github-readme-stats/issues/1471#issuecomment-1129752460.

**Comment by aghogwarts** [comment] 2022-05-18 11:51
same issue just popped up in my account as well. no hurries take your time to fix it if it's a problem in the code. amazing service again, cheers !

**Comment by qhy040404** [comment] 2022-05-18 11:56
@rickstaa i'm wondering if it's a good resolution to host it on our own Vercel server. and this may reduce the frequency of use of the main service

**Comment by rickstaa** [comment] 2022-05-18 12:01
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Got bombarded with github notifications today. 🥲<br>Because github-readme-stats is down.<br><br>People don&#39;t understand that &quot;+1&quot; and &quot;same here&quot; comments don&#39;t help anyone, it&#39;s just puts pressure on the maintainer and spams their inbox.</p>&mdash; Anurag Hazra ⚛ (@anuraghazru) <a href="https://twitter.com/anuraghazru/status/1526842284167245824?ref_src=twsrc%5Etfw">May 18, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

@aghogwarts This problem is affecting all users of the public Vercel instance. For people who experience this problem, please  wait until we fix this issue upstream or as mentioned in https://github.com/anuraghazra/github-readme-stats/issues/1471 deploy your own vercel instance. Locking this issue for now to keep the notification bar from exploding 🤯.

**Closed** 2022-05-18 21:12 UTC
Labels: bug, upstream
