### ISSUE TITLE
Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by mxsm** [anuraghazra/github-readme-stats#2383] opened 2023-01-12 08:23 UTC
### Describe the bug

**Cannot read properties of undefined (reading 'user')** how to fix it
![image](https://user-images.githubusercontent.com/15797831/212015197-3e30d6c8-aef2-4f07-a57f-3aceb2dbe6bd.png)

**Comment by fernvenue** [comment] 2023-01-12 08:24
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/2382.

**Comment by MitkoVtori** [comment] 2023-01-12 08:28
This issue is uneeded

**Closed** 2023-01-12 08:51 UTC
Labels: bug
