### ISSUE TITLE
'include_all_commits' doesn't work properly with 'count_private'.

### ISSUE THREAD

**Issue by Taiizor** [anuraghazra/github-readme-stats#2037] opened 2022-09-21 17:39 UTC
**Describe the bug**
The commit count does not work correctly at all times.

**Expected behaviour**
Correct operation of total commit count at all times (including hidden commits).

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
[![image](https://user-images.githubusercontent.com/41683699/191572091-e29908c0-7bfc-4cca-bbd7-a63dfca1c3c4.png)](https://github-readme-stats.vercel.app/api?username=Taiizor&show_icons=true&theme=tokyonight&count_private=true)

[![image](https://user-images.githubusercontent.com/41683699/191572446-9371407d-b093-4d61-84cf-2c2b9f3b1153.png)](https://github-readme-stats.vercel.app/api?username=Taiizor&show_icons=true&theme=tokyonight&count_private=true&include_all_commits=true)

**Additional context**
Working properly:
https://github-readme-stats.vercel.app/api?username=Taiizor&show_icons=true&theme=tokyonight&count_private=true

Not working properly:
https://github-readme-stats.vercel.app/api?username=Taiizor&show_icons=true&theme=tokyonight&count_private=true&include_all_commits=true

**Comment by akielaries** [comment] 2022-09-21 23:56
Having the same issue with mine. Here is what my stats card looks like with include_all_commits=false vs include_all_commits=true

![include_all_commits-false](https://user-images.githubusercontent.com/56521583/191629964-c4d08e4c-fcd6-4632-a727-fd4dc4122803.png)
![include_all_commits-true](https://user-images.githubusercontent.com/56521583/191629965-c8040669-e921-4b94-9d9c-f22b21a9bf48.png)

**Comment by Taiizor** [comment] 2022-09-22 08:21
It's working as it should now.

**Comment by akielaries** [comment] 2022-09-22 08:45
am still getting some errors with mine unfortunately

**Comment by rickstaa** [comment] 2022-09-24 14:08
@Taiizor and @akielaries, I checked the codebase, and I think both `count_private` and `include_all_commits` parameters are correctly implemented.

https://github.com/anuraghazra/github-readme-stats/blob/9a909ff0a41a6abba34b008ce57744d7cb2cd220/src/fetchers/stats-fetcher.js#L155-L163

I, therefore, think the error is caused by incorrect data returned from GitHub's [REST API](https://docs.github.com/en/rest) and [GraphQL API](https://docs.github.com/en/graphql) APIs. If this happens, these wrong values are cached for 4 hours. 

https://github.com/anuraghazra/github-readme-stats/blob/9a909ff0a41a6abba34b008ce57744d7cb2cd220/api/index.js#L60-L64

When this happens, you can check the console.log to see if there is any error and use the `&v=123` syntax to force the cache to reload.

### Detailed explanation

If `include_all_commits` is enabled, and GitHub [REST API](https://docs.github.com/en/rest) fails the code will return 0. 

https://github.com/anuraghazra/github-readme-stats/blob/9a909ff0a41a6abba34b008ce57744d7cb2cd220/src/fetchers/stats-fetcher.js#L69-L100

This will then be used as the total commits. To this value, the private commits will be correctly added if `count_private` is enabled. Since we used caching, this wrong value will be on the card for 4 hours. 

### Posible solutions

We can use the previous cache when this problem happens.

**Comment by rickstaa** [comment] 2022-09-24 14:11
Duplicate of #1515.

**Closed by rickstaa** 2022-09-24 14:11 UTC
Labels: bug
