### ISSUE TITLE
I want to hide 'jupyter notebook' in top languages card

### ISSUE THREAD

**Issue by minji-o-j** [anuraghazra/github-readme-stats#220] opened 2020-07-27 17:32 UTC
**Describe the bug**
I want to hide 'jupyter notebook' in top languages card

**Expected behavior**

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=minji-o-j)
`![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=minji-o-j)`
<br>

![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=minji-o-j&hide=jupyter-notebook)
`![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=minji-o-j&hide=jupyter-notebook)`
<br>

![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=minji-o-j&hide=notebook)
`![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=minji-o-j&hide=notebook)`
<br>

![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=minji-o-j&hide=Jupyter-Notebook)
`![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=minji-o-j&hide=Jupyter-Notebook)`
<br>

how can I hide this?

**Comment by anuraghazra** [comment] 2020-07-27 17:35
you can hide using `&hide=Jupyter Notebook`

Duplicate of #201

**Closed** 2020-07-27 17:38 UTC

**Comment by sele14** [comment] 2022-01-03 12:42
> you can hide using `&hide=Jupyter Notebook`
> 
> Duplicate of #201

This doesn't work for me, it just creates this:
![image](https://user-images.githubusercontent.com/48357515/147931698-20b4e0bb-f1e5-4304-aa14-c9b0f09d6347.png)
