### ISSUE TITLE
Why your util don't count contributions for organizations

### ISSUE THREAD

**Issue by Ythosa** [anuraghazra/github-readme-stats#609] opened 2020-11-02 10:13 UTC
I rly want this feature! Because of I have organizations where I'm the only member :( And nothing from repositories in this organizations don't count :(

**Comment by anuraghazra** [comment] 2020-11-02 11:33
see #1

**Comment by anuraghazra** [comment] 2020-11-05 10:25
duplicate of #1

**Closed by anuraghazra** 2020-11-05 10:25 UTC
