### ISSUE TITLE
Hide border option influences commit count

### ISSUE THREAD

**Issue by klieret** [anuraghazra/github-readme-stats#2026] opened 2022-09-15 16:34 UTC
## Description

Hide border option influences total  commit count

## Live

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&hide_border=true&show_icons=true&count_private=true&include_all_commits=true)

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&hide_border=false&show_icons=true&count_private=true&include_all_commits=true)

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&show_icons=true&count_private=true&include_all_commits=true)

## Screenshot of the above (15 Sep 2022)

![image](https://user-images.githubusercontent.com/13602468/190458730-fe47a7ae-ea75-4d05-8bed-29e6cd9f55ee.png)

**Comment by rickstaa** [comment] 2022-09-16 09:13
@klieret Thanks for your bug report. I can not think of how the `hide_border` option can break the card:

https://github.com/anuraghazra/github-readme-stats/blob/3b0f1b11a01e32c4f254861f66a28c14df70c890/src/Card.js#L121

I have heard reports from others (i.e. #1963 and #1968), but those were related to caching or syntax errors. Can you maybe provide me with the syntax you're using for generating the card?

**Comment by klieret** [comment] 2022-09-16 16:05
Thank you for your quick reply! I'm also quite puzzled. My only hypothesis that there might be some parsing error, perhaps due to wrong syntax on my side that causes some other options to be triggered...

The syntax should be included above (it's live markdown), but let me quickly copy it:

```
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&hide_border=true&show_icons=true&count_private=true&include_all_commits=true)

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&hide_border=false&show_icons=true&count_private=true&include_all_commits=true)

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&show_icons=true&count_private=true&include_all_commits=true)
```

are the three cards.

**Comment by rickstaa** [comment] 2022-09-17 09:35
@klieret Ah, sorry, I thought all were screenshots. I checked your syntax and it is correct 👍🏻.

**Hide border**

```md
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&hide_border=true&show_icons=true&count_private=true&include_all_commits=true)
```

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&hide_border=true&show_icons=true&count_private=true&include_all_commits=true)

**Explicitly show border**

```md
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&hide_border=false&show_icons=true&count_private=true&include_all_commits=true)
```

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&hide_border=false&show_icons=true&count_private=true&include_all_commits=true)

**No border argument**

```md
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&show_icons=true&count_private=true&include_all_commits=true)
```

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=klieret&show_icons=true&count_private=true&include_all_commits=true)

After inspecting the codebase, I don't think a parsing error of the `hide_border` can affect the commit count. I created #2029, to be sure. What I think is happening is that there is a temporary problem with GitHub's REST API, and the incorrect commit count gets stored in the cache and stays on the card for 4 hours. Maybe if you see it happen again, can you check whether an error or warning is thrown inside the browser's console? 🤔 I will close this issue for now since I can not reproduce it. Feel free to add extra information if you find something.

**Closed by rickstaa** 2022-09-17 09:35 UTC

**Comment by klieret** [comment] 2023-01-09 21:02
Hi @rickstaa. Just letting you know that I observed the same issue again today (a completely wrong commit count)
![image](https://user-images.githubusercontent.com/13602468/211407624-9b989652-ab01-4840-86bb-b5c87be074d1.png)

(should be something like 7k). 

I don't see relevant warnings in the browser console.

**Comment by rickstaa** [comment] 2023-01-10 09:42
@klieret, thanks for letting me know. I checked, and the commit count seems to be back on 8k again. This problem happens from time to time because GitHub's REST API gives us wrong data or timeout. The only thing I can do to alleviate it is merged https://github.com/anuraghazra/github-readme-stats/pull/2029. It will be fixed when https://github.com/anuraghazra/github-readme-stats/issues/2179 is created since I can then use the GraphQL API, which is less buggy, and sum the commits per year.

**Comment by lukaszmielczarekdev** [comment] 2023-02-15 21:27
I managed to make it work by setting `count_private` property to `true`.

`https://github-readme-stats.vercel.app/api?username=lukaszmielczarekdev&theme=dark&hide_border=true&include_all_commits=true&count_private=true`

![](https://github-readme-stats.vercel.app/api?username=lukaszmielczarekdev&theme=dark&hide_border=true&include_all_commits=true&**count_private=true**)
