### ISSUE TITLE
`include_all_commits` decrease the stats

### ISSUE THREAD

**Issue by wiryadev** [anuraghazra/github-readme-stats#1234] opened 2021-08-09 09:28 UTC
**Describe the bug**
`include_all_commits` decrease the stats instead of increasing it.

**Expected behavior**
I expect `include_all_commits` to be increase my stats since it should counts total commits.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
Here is the table showing with and without `include_all_commits`
<table style="width:100%">
  <tr>
    <th>With</th>
    <th>Without</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/26060382/128685642-a8c04e93-38e7-42db-a445-0f7ed0033a49.png"></td>
    <td><img src="https://user-images.githubusercontent.com/26060382/128685558-757bf24f-9d90-4c78-9af8-7dab3ebb3690.png"></td>
  </tr>
</table>

**Comment by viticis** [comment] 2021-08-10 05:46
I ran into the same problem.

**Comment by AyushShahh** [comment] 2021-08-12 17:24
I have the same problem

**Comment by wy-luke** [comment] 2021-10-18 05:58
same

**Comment by AlessioQuercia** [comment] 2021-11-17 15:15
In my case this happens only when both ```include_all_commits=true``` and ```count_private=true``` are used.

|  | ```count_private=false``` | ```count_private=true``` |
| :---: | :---: | :---: |
| ```include_all_commits=false``` | ![immagine](https://user-images.githubusercontent.com/18620868/142222761-78cd4f8b-ff06-4317-bf71-10b6f0b8f31b.png) | ![immagine](https://user-images.githubusercontent.com/18620868/142225159-9a801677-85e2-468a-9e07-aa8683378c65.png) |
| ```include_all_commits=true``` | ![immagine](https://user-images.githubusercontent.com/18620868/142223123-1dd7d46f-dbe4-4286-a8a8-308912e7dd9d.png) | ![immagine](https://user-images.githubusercontent.com/18620868/142225447-1eb81535-87b7-478e-9e0a-c57e95315f98.png) |

Perhaps the issue is when both are included?

Furthermore, I just noticed that by adding an additional ```&``` after the github name increases the commits (probably close to the right number, I am not sure, but the ones before are definetely not the right ones):
```
https://github-readme-stats.vercel.app/api?username=USERNAME&&include_all_commits=true&count_private=true
```
Result (using the double ```&```): 
![immagine](https://user-images.githubusercontent.com/18620868/142227125-4386e8e0-7f79-4023-bcb3-e91561ab1591.png)

**Comment by MagicLike** [comment] 2022-01-15 17:35
still same issue

**Comment by Almighty-Shogun** [comment] 2022-03-07 10:36
I also have the same issue

**Comment by luankaip** [comment] 2022-03-14 05:28
Same problem

**Comment by rickstaa** [comment] 2022-09-24 14:11
Duplicate of #1515.

**Closed by rickstaa** 2022-09-24 14:11 UTC
Labels: bug, stats-card
