### ISSUE TITLE
Hide rank box layout

### ISSUE THREAD

**Issue by dineshyadav3169** [anuraghazra/github-readme-stats#364] opened 2020-08-11 14:01 UTC
When hide_rank is set True then box does not shrink
the box is not responsive

Also I want to request a feature :
a parameter in url that lets you align text to right

**Comment by anuraghazra** [comment] 2020-08-11 14:07
Duplicate of #108 

Please open another issue for any particular feature request.

**Closed by anuraghazra** 2020-08-11 14:07 UTC
