### ISSUE TITLE
Allow count of organisations activities

### ISSUE THREAD

**Issue by Jose-JohnEm** [anuraghazra/github-readme-stats#1243] opened 2021-08-11 07:53 UTC
I want to have a beautiful Github counting all my contributions. However the Readme Stats don't take care about organisations' activities, but that's where I contribute the most (approximatively 6 times more).

How can we add organisation's contributions so ?

**Comment by anuraghazra** [comment] 2021-08-24 15:51
duplicate of #1

**Closed by anuraghazra** 2021-08-24 15:51 UTC
