### ISSUE TITLE
Stats rendering bug on mobile

### ISSUE THREAD

**Issue by rafaelfaustini** [anuraghazra/github-readme-stats#776] opened 2021-01-02 01:27 UTC
**Describe the bug**
When seeing the stats card on Github's android app the stats text disappear and the grade gets unaligned

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![e2a34722-6670-4166-b8f2-71fd29dc5623](https://user-images.githubusercontent.com/26970976/103448975-00549480-4c80-11eb-88ca-967b307c60a6.jpg)

**Additional context**
Reproduced with Android 10 and Github app version 1.3.14

**Comment by nathanchu** [comment] 2021-01-03 01:29
Does it happen with this image (animations disabled):

![](https://github-readme-stats.vercel.app/api?username=nathanchu&disable_animations=true)

**Comment by rafaelfaustini** [comment] 2021-01-03 02:16
@nathanchu It does happen
![image](https://user-images.githubusercontent.com/26970976/103470386-8d671e80-4d50-11eb-9406-8c9d05f4f9cb.png)

**Comment by nathanchu** [comment] 2021-01-03 16:14
How does this look:
![](https://github-readme-stats-git-776.nathanchu.vercel.app/api?username=nathanchu)

**Comment by anuraghazra** [comment] 2021-01-03 16:17
@rafaelfaustini can you try the `disable_animations`  flag?

https://github-readme-stats.vercel.app/api?username=anuraghazra&disable_animations=true

**Comment by nathanchu** [comment] 2021-01-03 16:18
I already tried that, see https://github.com/anuraghazra/github-readme-stats/issues/776#issuecomment-753553623

**Comment by anuraghazra** [comment] 2021-01-03 16:19
> I already tried that, see [#776 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/776#issuecomment-753553623)

ops missed your comment.

**Comment by anuraghazra** [comment] 2021-01-03 16:34
@rafaelfaustini can you try this one? this should work i suppose 🤔 currently our disable_animation option just sets the animation-duration to 0 which probably isn't working in github mobile so i totally removed all the css animation stuff and deployed on this url 

https://github-readme-stats-9bnk44l7j.vercel.app/api?username=anuraghazra

![](https://github-readme-stats-9bnk44l7j.vercel.app/api?username=anuraghazra)

**Comment by nathanchu** [comment] 2021-01-03 16:39
Hmm maybe it has something to do with #571

**Comment by anuraghazra** [comment] 2021-01-03 16:40
related to #215

**Comment by rafaelfaustini** [comment] 2021-01-03 19:06
> @rafaelfaustini can you try this one? this should work i suppose 🤔 currently our disable_animation option just sets the animation-duration to 0 which probably isn't working in github mobile so i totally removed all the css animation stuff and deployed on this url 
> 
> https://github-readme-stats-9bnk44l7j.vercel.app/api?username=anuraghazra
> 
> ![](https://github-readme-stats-9bnk44l7j.vercel.app/api?username=anuraghazra)

Same problem

**Comment by nathanchu** [comment] 2021-01-03 19:22
@rafaelfaustini What about this:
![](https://github-readme-stats-git-776.nathanchu.vercel.app/api?username=nathanchu&disable_animations=true&1)

**Comment by MitchTalmadge** [comment] 2021-01-07 08:50
I am experiencing the same problem on the  Google Pixel 5 GitHub app. 

This one looks the best so far:

![Screenshot_20210107-014927.png](https://user-images.githubusercontent.com/8848080/103871697-a2162000-508a-11eb-940c-33bc9354e5b5.png)

Perhaps the image server could detect the user agent and serve a mobile optimized version for the GitHub app.

**Comment by nathanchu** [comment] 2021-01-07 22:04
The user agent will always be github’s cdn though... So user-agent sniffing isn’t possible. Ideally, the same card should work on all platforms

**Comment by MitchTalmadge** [comment] 2021-01-07 22:12
Good point, hadn't thought of that.

**Comment by sci4me** [comment] 2021-01-14 21:08
Potential duplicate of/related to #664?

**Comment by rickstaa** [comment] 2022-02-17 07:02
This appears to be fixed. See https://github.com/anuraghazra/github-readme-stats/issues/899#issuecomment-877199309. I will close the related issues for now. If anyone is still experiencing issues feel free to leave a comment.

**Closed by rickstaa** 2022-02-17 07:02 UTC
Labels: bug, design
