### ISSUE TITLE
Maximum Retries Exceeded

### ISSUE THREAD

**Issue by KendallDoesCoding** [anuraghazra/github-readme-stats#2574] opened 2023-03-10 15:29 UTC
### Describe the bug

Error

### Screenshots / Live demo link

![image](https://user-images.githubusercontent.com/84712013/224356616-08a7f7b7-05db-4a5e-bf35-ef78c76db226.png)

**Comment by Zo-Bro-23** [comment] 2023-03-10 16:46
Duplicate of #1471.

**Closed by Zo-Bro-23** 2023-03-10 16:46 UTC
Labels: bug
