### ISSUE TITLE
Maximum retries exceeded

### ISSUE THREAD

**Issue by Pyth0nHere** [anuraghazra/github-readme-stats#2639] opened 2023-04-24 16:25 UTC
### Describe the bug

# HOW CAN I FIX THIS ISSUE???

### Screenshots / Live demo link

![Screenshot (52)](https://user-images.githubusercontent.com/88571280/234057308-0ed9f174-fe13-4d1d-8d38-b306e473933f.png)
https://camo.githubusercontent.com/6b39b8c238ae2a4ec07935bdc36d04beb4c203408a8de81b06fde642c3ad7a92/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d70797468306e686572652673686f775f69636f6e733d74727565266c6f63616c653d656e

**Comment by SlideeScherz** [comment] 2023-04-24 18:20
recd same issue. [my-repo](https://github.com/SlideeScherz/SlideeScherz)

**Comment by rickstaa** [comment] 2023-04-24 19:17
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/1471.

**Closed by rickstaa** 2023-04-24 19:17 UTC
Labels: bug

**Comment by PencilNavigator** [comment] 2023-04-27 05:39
https://github.com/anuraghazra/github-readme-stats/issues/2415
