### ISSUE TITLE
Feature Request: Designing a new stat card for showing GitHub streak(on weekly basis)

### ISSUE THREAD

**Issue by yaten2302** [anuraghazra/github-readme-stats#3210] opened 2023-09-06 18:17 UTC
### Is your feature request related to a problem? Please describe.

The GRS has a lot of stats cards included, but there is no card for showing the streak of the user.

### Describe the solution you'd like

My solution to this issue:

Creating a new stat card for showing the total contributions, current streak and the longest streak of the user(along with date)
I'll also share the sample template that how the stat card will look like, once this issue gets approved.

**Comment by yaten2302** [comment] 2023-09-08 17:29
![image](https://github.com/anuraghazra/github-readme-stats/assets/129659514/99c12b0f-1c05-4254-92ee-7deb0b440158)


Hi @rickstaa, @qwerty541, I just took an idea from a website that how to design the streak card. The card will not be exactly the same, but will change the layout a couple of things, may I create a PR, if you approve?

**Comment by qwerty541** [comment] 2023-09-09 14:10
@yaten2302 Closing this as duplicate of https://github.com/anuraghazra/github-readme-stats/issues/3209. Different basis can be implemented as query parameter, we should not create two cards for it. So it will be enough to have only one issue.

**Closed** 2023-09-09 14:10 UTC
Labels: enhancement
