### ISSUE TITLE
Organization cards

### ISSUE THREAD

**Issue by jmbanda** [anuraghazra/github-readme-stats#460] opened 2020-09-13 16:40 UTC
**Is your feature request related to a problem? Please describe.**
Cards cannot display organization stats.

**Describe the solution you'd like**
It would be great to be able to display our organization stats on our profile.

**Describe alternatives you've considered**
No alternative possible.

**Additional context**
NA

**Comment by rivenirvana** [comment] 2020-09-13 17:35
#1 may be of relevance.

**Comment by anuraghazra** [comment] 2020-10-17 13:42
Hi @jmbanda sorry for late response, yeah seems like duplicate of #1 

Closing this in favor of that since we are already discussing it on there. Feel free to open another one if you have any other queries. :)

**Closed by anuraghazra** 2020-10-17 13:42 UTC
