### ISSUE TITLE
Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by abhish1ss** [anuraghazra/github-readme-stats#2380] opened 2023-01-12 05:59 UTC
### Describe the bug

Something went wrong! file an issue at https://tiny.one/readme-stats

Showing this error while fetching the github stats
![ss](https://user-images.githubusercontent.com/31668873/211989352-19efc63f-053f-43d1-995f-2b513016670c.png)

**Comment by leekm0310** [comment] 2023-01-12 06:02
Facing the same issue

**Comment by XSuperMeteorX** [comment] 2023-01-12 06:02
Facing the same issues

**Comment by SnakeHit** [comment] 2023-01-12 06:02
Facing the same issues

**Comment by Lingling-LynnChan** [comment] 2023-01-12 06:03
Facing the same issues

**Comment by sokhuong-uon** [comment] 2023-01-12 06:05
Yes, same issue

**Comment by KyrieLii** [comment] 2023-01-12 06:05
same issue

**Comment by WuWenL0** [comment] 2023-01-12 06:06
Facing the same issues

**Comment by akirataguchi115** [comment] 2023-01-12 06:06
Same here

**Comment by 3000-codes** [comment] 2023-01-12 06:07
I am not alone

**Comment by SuperBruceJia** [comment] 2023-01-12 06:08
+1

<img width="587" alt="image" src="https://user-images.githubusercontent.com/31528604/211990604-0ea1b5c2-47d6-4358-b097-4b22e8f3fedc.png">

**Comment by timerring** [comment] 2023-01-12 06:08
Facing the same issues

**Comment by dangolbeeker** [comment] 2023-01-12 06:10
Same here I think since we're all here within 10 minutes we should give it an hr or so maybe moving hosts or something.

**Comment by chlzslvdr** [comment] 2023-01-12 06:25
same issue

**Comment by MitkoVtori** [comment] 2023-01-12 06:31
That's mass error

**Comment by DeveloperChoi90** [comment] 2023-01-12 06:31
same issue

**Comment by jazmand** [comment] 2023-01-12 06:34
Same here!

**Comment by ThreeCatsLoveFish** [comment] 2023-01-12 06:39
Facing the same issue

**Comment by Cierra-Runis** [comment] 2023-01-12 06:43
Facing the same issue

**Comment by pachuho** [comment] 2023-01-12 06:50
facing the same issue

**Comment by myps6415** [comment] 2023-01-12 06:55
Facing the same issue

**Comment by DhanushNehru** [comment] 2023-01-12 06:56
Facing the same

<img width="590" alt="Screenshot 2023-01-12 at 12 26 20 PM" src="https://user-images.githubusercontent.com/22955675/211998377-efa40c18-2cb4-4a87-97e0-70a9fc5d9fb3.png">

**Comment by jxareas** [comment] 2023-01-12 06:56
Samesies! Hope they can address this soonly. :dizzy:

**Comment by caicaishmily** [comment] 2023-01-12 06:58
Facing the same issues

**Comment by kaluojushi** [comment] 2023-01-12 07:00
Facing the same issue

**Comment by LJoson** [comment] 2023-01-12 07:00
Facing the same issue

**Comment by boring-km** [comment] 2023-01-12 07:05
Facing the same issue

**Comment by David1X** [comment] 2023-01-12 07:07
Facing the same issues

**Comment by zhc-njdx** [comment] 2023-01-12 07:12
facing the same.
![image](https://user-images.githubusercontent.com/80049721/212001091-428ae549-e76a-43a6-bbad-c759e67a903c.png)

**Comment by damon-911** [comment] 2023-01-12 07:13
Facing the same issues!

**Comment by ihengshuai** [comment] 2023-01-12 07:17
+1

**Comment by WForst-Breeze** [comment] 2023-01-12 07:21
Facing the same issue

**Comment by 5onchangwoo** [comment] 2023-01-12 07:24
Facing the same issue

**Comment by MitkoVtori** [comment] 2023-01-12 07:25
CAN EVERYONE STOP!? This is mass issue, everyone have it. Stop commenting "Facing same issue" WE KNOW! Some people are following this issue to see what is going on, but because Y'all have to say it, we're getting spammed in our emails.

**Comment by nmsn** [comment] 2023-01-12 07:45
Facing the same issues

**Comment by jxareas** [comment] 2023-01-12 07:52
True. [It could be worse somehow...](https://github.com/EpicGames/Signup/pull/24#issuecomment-1146718968)  :stuck_out_tongue_closed_eyes:

For the record, *there's an unsubscribe button* in the right column, almost at the bottom, just above the participants list. Click it **if you don't want to get notifications**.
<div align="center">
<img src="https://user-images.githubusercontent.com/60629627/212008121-22dea520-d0d2-469c-9a10-258791f87fea.png" width="200" height="250"/>

**Comment by Joker-5** [comment] 2023-01-12 08:21
same issue

**Comment by ZiAzusa** [comment] 2023-01-12 08:22
Same issue

**Comment by MitkoVtori** [comment] 2023-01-12 08:27
> True. [It could be worse somehow...](https://github.com/EpicGames/Signup/pull/24#issuecomment-1146718968) 😝
> 
> For the record, _there's an unsubscribe button_ in the right column, almost at the bottom, just above the participants list. Click it **if you don't want to get notifications**.
> 
> <img alt="" width="200" height="250" src="https://user-images.githubusercontent.com/60629627/212008121-22dea520-d0d2-469c-9a10-258791f87fea.png">

The problem is, I want to recieve notifications about **UPDATES**, not to see the 10930943th person saying "same issue", WE KNOW YOU all have it, why people still saying, aren't these 100 people with the same problem enough!?

**Comment by Dot32IsCool** [comment] 2023-01-12 08:28
Could it be related to the github ratelimit? 
<img width="866" alt="Screenshot 2023-01-12 at 16 26 54" src="https://user-images.githubusercontent.com/61964090/212016206-43d40d7c-47f0-400a-aa97-a3dfb4838a14.png">

**Comment by MitkoVtori** [comment] 2023-01-12 08:32
> Could it be related to the github ratelimit? <img alt="Screenshot 2023-01-12 at 16 26 54" width="866" src="https://user-images.githubusercontent.com/61964090/212016206-43d40d7c-47f0-400a-aa97-a3dfb4838a14.png">

I have my own vercel, but it does not work.

**Comment by archan0621** [comment] 2023-01-12 08:36
same issue

**Comment by Yomna-J** [comment] 2023-01-12 08:39
same here

**Comment by galaxy-s10** [comment] 2023-01-12 08:46
同样的问题

**Comment by 5ime** [comment] 2023-01-12 08:47
Yes, same issue

**Comment by ArchLeaders** [comment] 2023-01-12 08:47
~~I would say "same issue" but I'm pretty sure you guys get the gist~~

**Comment by iostyle** [comment] 2023-01-12 08:48
为了自由～

**Comment by ozanyetkin** [comment] 2023-01-12 08:52
I'm also facing the same issue

**Comment by Dot32IsCool** [comment] 2023-01-12 08:54
> > Could it be related to the github ratelimit? <img alt="Screenshot 2023-01-12 at 16 26 54" width="866" src="https://user-images.githubusercontent.com/61964090/212016206-43d40d7c-47f0-400a-aa97-a3dfb4838a14.png">
> 
> I have my own vercel, but it does not work.

Yeah, i just tried deploying one myself, and it's also not working

**Comment by Faeq-F** [comment] 2023-01-12 08:55
same issue

**Comment by DINGDANGMAOUP** [comment] 2023-01-12 08:56
1

**Comment by Allan-1** [comment] 2023-01-12 09:02
I'm also facing the same issue

**Comment by chsxf** [comment] 2023-01-12 09:14
Deploying on my own Vercel instance fixed the issue for me

**Comment by ten1fs** [comment] 2023-01-12 09:27
Facing the same issue

**Comment by xiaoyunjie** [comment] 2023-01-12 09:27
Facing the same issue

**Comment by E3TU** [comment] 2023-01-12 09:28
Same issue

**Comment by thebarshablog** [comment] 2023-01-12 09:37
![Cannot Read Properties of Undefined](https://user-images.githubusercontent.com/103309340/212031415-ca35a75c-123b-4026-ba70-46f0d11c6dcf.png)

Seems like everyone's facing the same issue. Let's fix it @anuraghazra

**Comment by ZiAzusa** [comment] 2023-01-12 09:47
I tried to deploy this project on my own vercel, and it works very well. So what happened with this?

**Comment by thebarshablog** [comment] 2023-01-12 09:50
> I tried to deploy this project on my own vercel, and it works very well. So what happened with this?

I've deployed using GitHub pages. Not working there.

**Comment by Ddhruv-IOT** [comment] 2023-01-12 09:58
Not Working

**Comment by HuseyinHartavi** [comment] 2023-01-12 10:01
> tance fix

How can to do this ? Please explain.

**Comment by HuseyinHartavi** [comment] 2023-01-12 10:02
> Deploying on my own Vercel instance fixed the issue for me

How can to do this ? Please explain.

**Comment by ZiAzusa** [comment] 2023-01-12 10:08
> > Deploying on my own Vercel instance fixed the issue for me
> 
> How can to do this ? Please explain.

See this: [readme](https://github.com/anuraghazra/github-readme-stats/#deploy-on-your-own-vercel-instance)

**Comment by BILLXZY1215** [comment] 2023-01-12 10:08
Same issue here, any workaround?

**Comment by AlbShar** [comment] 2023-01-12 10:24
Same issue. 
![52A2FCAC-EF1E-46E1-B317-3C26C17A9ABB](https://user-images.githubusercontent.com/86482752/212041937-3e7d4e2d-ff6a-475d-8293-628182aecf66.jpeg)

**Comment by ozanyetkin** [comment] 2023-01-12 10:36
> I'm also facing the same issue

update: deploying to my own Vercel resolved the issue, thanks for the advice!
[Here ](https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s&ab_channel=codeSTACKr)is the tutorial for that

**Comment by KatCote** [comment] 2023-01-12 10:58
Same issue here
![image](https://user-images.githubusercontent.com/43048681/212049126-21c646d8-290c-4714-94f2-4ecd8949ecdb.png)

**Comment by Ryagg** [comment] 2023-01-12 11:08
Facing the same isssue.

**Comment by Derrick-Yuan** [comment] 2023-01-12 11:11
same issue

**Comment by sousadiego11** [comment] 2023-01-12 11:16
i didn't deployed a version of the project, the issue is the same for me;

**Comment by Tang1705** [comment] 2023-01-12 11:27
Facing the same issues

**Comment by yukiyukixing** [comment] 2023-01-12 11:44
same issue

**Comment by confetti39** [comment] 2023-01-12 11:45
Same issue here

**Comment by engaziwayo** [comment] 2023-01-12 11:46
same issue

**Comment by hmes98318** [comment] 2023-01-12 11:50
same issue

**Comment by isLinXu** [comment] 2023-01-12 11:53
Same issue here

**Comment by patyhank** [comment] 2023-01-12 11:54
same issue

**Comment by Neftyr** [comment] 2023-01-12 12:04
Hello everyone,

seems like git issue, you can solve it by changing below and thats why it works for some people as they have their own setup:

https://github-readme-stats.vercel.app/api?
into

https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?

**Comment by MitkoVtori** [comment] 2023-01-12 12:20
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below and thats why it works for some people as they have their own setup:
> 
> `https://github-readme-stats.vercel.app/api?`
> 
> into
> 
> `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?`

It worked,

Just a comment:
If you want the languages card, at the end of the link add `/top-langs/` like that: `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs/?` for the repos, it's `/pin/`

PLEASE, STOP SAYING **SAME HERE** OR ANYTHING ELSE FROM NOW ON! Instead, let the people see the solution!


https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1380227822

**Comment by ayhankesicioglu** [comment] 2023-01-12 12:21
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below and thats why it works for some people as they have their own setup:
> 
> `https://github-readme-stats.vercel.app/api?`
> 
> into
> 
> `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?`

Thanks @Neftyr. This is work for me

**Comment by aliatillaydemir** [comment] 2023-01-12 12:22
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below and thats why it works for some people as they have their own setup:
> 
> `https://github-readme-stats.vercel.app/api?`
> 
> into
> 
> `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?`

This solved the problem. Thanks.

**Comment by thebarshablog** [comment] 2023-01-12 12:22
> Literally, Someone from the GitHub give me admin, and Ima start banning y'all. SHUT UP! We know there's a problem, IT'S FOR EVERYONE, no need the whole world to come here jees!!!!!!!!!!!


Yes, we should be tad bit patient about this. It's clear that this issue has comments flooding in, constantly! 

If anyone reads this particular comment, please shy away from commenting the things which has already been raised! 

@MitkoVtori Please be respectful with your words. We must address people in the community with respect. If unsophisticated means are employed that harms the community, I'm sure maintainers will take appropriate actions .

**Comment by E3TU** [comment] 2023-01-12 12:26
LLLLLLLLL

**Comment by Allan-1** [comment] 2023-01-12 12:49
> Hi! I was able to fix it by this way:
> 
> REPLACE THIS: "https://github-readme-stats.vercel.app/api?username="
> 
> TO THIS: "https://github-readme-stats-eight-theta.vercel.app/api?username="
> 
> You can check the change on my profile: https://github.com/brunogroth/brunogroth [#9](https://github.com/brunogroth/brunogroth/commit/ff1309c456013d38c8d6b43803b04eb4644509e1) commit in this repository.
> 
> Hope I could help you! smile

Thanks it has helped.

**Comment by anic4cio** [comment] 2023-01-12 12:52
Chill! This already had happened before, I think the solution is just wait

**Comment by AlbShar** [comment] 2023-01-12 13:08
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below and thats why it works for some people as they have their own setup:
> 
> `https://github-readme-stats.vercel.app/api?`
> 
> into
> 
> `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?`

Thanks a lot!  It has helped.

**Comment by tavareshenrique** [comment] 2023-01-12 13:11
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs/?

Thanks man! It's work!

**Comment by jincheny** [comment] 2023-01-12 13:19
> I think the solution is just wait
Ha ha, it makes sense! The main reason is that I tried the method mentioned above and it still didn't work!

**Comment by QJune** [comment] 2023-01-12 13:50
> seems like git issue, you can solve it by changing below and thats why it works for some people as they have their own setup:
> 
> `https://github-readme-stats.vercel.app/api?`
> 
> into
> 
> `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?`

Thanks.

**Comment by maynardgui** [comment] 2023-01-12 19:40
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below and thats why it works for some people as they have their own setup:
> 
> `https://github-readme-stats.vercel.app/api?`
> 
> into
> 
> `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?`

thanks

**Comment by ARLY-LC-JUNIOR** [comment] 2023-01-12 19:48
my friend, you helped this community, show of ball.
Your guidance was positive, I managed by following your premises.

Tks.

**Comment by rickstaa** [comment] 2023-01-12 21:40
Duplicate of #2391. Please see https://github.com/anuraghazra/github-readme-stats/issues/2391#issuecomment-1381020968.

**Comment by rickstaa** [comment] 2023-01-12 21:41
I can not find an error in the code base 🤔. I think it is a problem with the @anuraghazra Vercel instance. I texted him to check if he could find out what was going wrong. You can use my Vercel instance, but I'm afraid it will be rate-limited very quickly since GitHub allows only 5000 API requests per hour on my instance, and we currently use 70k per hour on the public Vercel instance 🤣. As explained in https://github.com/anuraghazra/github-readme-stats/issues/1471, the best option is to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). 👍

**Comment by showierdata9978** [comment] 2023-01-12 21:46
Dupe of #1471

**Comment by showierdata9978** [comment] 2023-01-12 21:58
Workaround: fork, it seems to work there

**Comment by showierdata9978** [comment] 2023-01-12 21:58
Newest version

**Comment by dragoncoder047** [comment] 2023-01-12 22:00
I'm seeing this one too.

My thoughts on this is that it is a rate limit issue but the code is not detecting this and showing an appropriate error instead. It could be something as simple as the JSON from github usually has a `user` property but when you hit rate-limit it returns an unhelpful `{"error":"rate limit"}` or such that only contains the error message and no data. I'm not familiar with the github api, please correct me if I'm wrong. But maybe this not-displaying-an-appropriate-error-message problem should be fixed?

**Comment by rickstaa** [comment] 2023-01-12 22:03
> iate-error-message problem should be fixe

Your conclusion is correct. I had that error show up some months ago as well on a rate limit. 😅 I, however, have no access to the Public Vercel team instance, and everything is working from my side. We, therefore, have to wait for @anuraghazra to check what goes wrong. 👍

**Comment by rickstaa** [comment] 2023-01-12 22:08
I am planning on creating a GitHub Action version of this repository (see https://github.com/anuraghazra/github-readme-stats/issues/2179). This will solve a lot of the problems and inaccuracies we currently have (i.e. https://github.com/anuraghazra/github-readme-stats/issues/1, https://github.com/anuraghazra/github-readme-stats/issues/1406, https://github.com/anuraghazra/github-readme-stats/issues/1515, https://github.com/anuraghazra/github-readme-stats/issues/1852, https://github.com/anuraghazra/github-readme-stats/issues/1801). I, however, do not have time to take this on within the next three months. If somebody wants to take it on, feel free to comment on #2169, and I will assign you.

**Comment by Radeonares32** [comment] 2023-01-12 22:23
Facing the same issues

**Comment by Ein-Tim** [comment] 2023-01-12 22:31
Hey everyone! Please, don't comment just for saying you're facing the same issue! You can use GitHub's upvote feature (= like this issue) to make clear that you have the same problem, but commenting isn't optimal, as everyone who subscribed to this issue will be notified about new comments. Also, important information easily gets lost in such unhelpful and unnecessary comments.

Thanks!

**Comment by kraj2503** [comment] 2023-01-12 22:34
Same issue.

**Comment by PiyushKumar-18-AI** [comment] 2023-01-12 23:06
In the following image you can see the change in the readme file which <b><i>fixed</b></i> the <b><i> github-readme</b></i> problem. 
<img width="1609" alt="Screenshot 2023-01-13 at 4 30 23 AM" src="https://user-images.githubusercontent.com/68659006/212199512-2b62bcf4-8566-45ee-b31c-2ef749fb9a75.png">

So, by adding <b><i>"-git-masterrstaa-rickstaa"</b></i> into the existing code and your problem will be solved.

from:

https://github-readme-stats.vercel.app/api?

into:

https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?

**Comment by rreeves1996** [comment] 2023-01-12 23:40
> -git-masterrstaa-rickstaa.vercel.app/api?

I was having this issue up until right now (3:30pm Pacific -7:00) and this fix worked for me.

**Comment by henryelga** [comment] 2023-01-13 00:01
Facing the same issue

**Comment by EmanoelG** [comment] 2023-01-13 01:02
Enfrentando o mesmo problema

**Comment by jheavejimenez** [comment] 2023-01-13 01:04
Facing the same issue

**Comment by EmanoelG** [comment] 2023-01-13 01:06
Enfrentando o mesmo problema

**Comment by SuperBruceJia** [comment] 2023-01-13 01:08
> In the following image you can see the change in the readme file which fixed the github-readme problem. <img alt="Screenshot 2023-01-13 at 4 30 23 AM" width="1609" src="https://user-images.githubusercontent.com/68659006/212199512-2b62bcf4-8566-45ee-b31c-2ef749fb9a75.png">
> 
> So, by adding "-git-masterrstaa-rickstaa" into the existing code and your problem will be solved.
> 
> from:
> 
> https://github-readme-stats.vercel.app/api?
> 
> into:
> 
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?

Well done! Thank you very much!

**Comment by igortrinidad** [comment] 2023-01-13 01:13
@Brunopaun look here to fix your profile too bro

> > In the following image you can see the change in the readme file which fixed the github-readme problem. <img alt="Screenshot 2023-01-13 at 4 30 23 AM" width="1609" src="https://user-images.githubusercontent.com/68659006/212199512-2b62bcf4-8566-45ee-b31c-2ef749fb9a75.png">
> > So, by adding "-git-masterrstaa-rickstaa" into the existing code and your problem will be solved.
> > from:
> > https://github-readme-stats.vercel.app/api?
> > into:
> > https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> 
> Well done! Thank you very much!

**Comment by matheusbnas** [comment] 2023-01-13 01:19
> In the following image you can see the change in the readme file which fixed the github-readme problem. <img alt="Screenshot 2023-01-13 at 4 30 23 AM" width="1609" src="https://user-images.githubusercontent.com/68659006/212199512-2b62bcf4-8566-45ee-b31c-2ef749fb9a75.png">
> 
> So, by adding "-git-masterrstaa-rickstaa" into the existing code and your problem will be solved.
> 
> from:
> 
> https://github-readme-stats.vercel.app/api?
> 
> into:
> 
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?

Thanks so much!

**Comment by PabloButron** [comment] 2023-01-13 01:38
Thuis worked for me:

replace: 
"https://github-readme-stats"
with 
"https://github-readme-stats-git-masterrstaa-rickstaa"

**Comment by czasg** [comment] 2023-01-13 01:40
"-git-masterrstaa-rickstaa" 
it works. Great

**Comment by matheusbnas** [comment] 2023-01-13 01:43
> > Hello everyone,
> > seems like git issue, you can solve it by changing below and thats why it works for some people as they have their own setup:
> > `https://github-readme-stats.vercel.app/api?`
> > into
> > `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?`
> 
> thanks

Thanks!

**Comment by paulovictor1997** [comment] 2023-01-13 01:52
@matheusbnas valeu !!!

**Comment by jesterb0206** [comment] 2023-01-13 02:04
Thank you everyone for helping fix this! 😊

**Comment by tjrans9248** [comment] 2023-01-13 02:32
I have same issue

**Comment by sakibb019** [comment] 2023-01-13 02:52
It's working me as well just to change
replace:
"https://github-readme-stats/"
with
"https://github-readme-stats-git-masterrstaa-rickstaa/"

**Comment by carepollo** [comment] 2023-01-13 03:52
![image](https://user-images.githubusercontent.com/67649525/212233185-0c62eb1f-6445-4f14-aef8-ec94972696cf.png)

I have the exact same issue, I had a configuration that worked perfectly, but now this.
It is not working on most used languages card and stars card

**Comment by Brunopaun** [comment] 2023-01-13 03:52
> @Brunopaun look here to fix your profile too bro
> 
> > > In the following image you can see the change in the readme file which fixed the github-readme problem. <img alt="Screenshot 2023-01-13 at 4 30 23 AM" width="1609" src="https://user-images.githubusercontent.com/68659006/212199512-2b62bcf4-8566-45ee-b31c-2ef749fb9a75.png">
> > > So, by adding "-git-masterrstaa-rickstaa" into the existing code and your problem will be solved.
> > > from:
> > > https://github-readme-stats.vercel.app/api?
> > > into:
> > > https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> > 
> > 
> > Well done! Thank you very much!

Thanks bro

**Comment by carepollo** [comment] 2023-01-13 03:55
> It's working me as well just to change replace: "https://github-readme-stats/" with "https://github-readme-stats-git-masterrstaa-rickstaa/"

I try that but I get this
![image](https://user-images.githubusercontent.com/67649525/212233705-733dec99-3440-42d1-b5d4-8bcddfb426fa.png)

**Comment by trwstin** [comment] 2023-01-13 04:19
> > It's working me as well just to change replace: "https://github-readme-stats/" with "https://github-readme-stats-git-masterrstaa-rickstaa/"
> 
> I try that but I get this ![image](https://user-images.githubusercontent.com/67649525/212233705-733dec99-3440-42d1-b5d4-8bcddfb426fa.png)

You still need to include your username at the end of the URL. For example:
https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=carepollo

**Comment by Mentors4EDU** [comment] 2023-01-13 04:32
Fixed, thanks @PabloButron

|![Andrew's github stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=Mentors4EDU&count_private&include_all_commits=true&hide_title=true&show_icons=true&theme=highcontrast)

**Comment by hu1won** [comment] 2023-01-13 04:50
![image](https://user-images.githubusercontent.com/71807924/212240079-6ad778a1-e880-4148-aecf-77fa37a8db27.png)

same issue

**Comment by jdevstatic** [comment] 2023-01-13 05:24
> > > Hello everyone,
> > > seems like git issue, you can solve it by changing below and thats why it works for some people as they have their own setup:
> > > `https://github-readme-stats.vercel.app/api?`
> > > into
> > > `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?`
> > 
> > 
> > thanks
> 
> Thanks!

this temporarily fixed the issue, but I hope, this is permanent

**Comment by guoqiangqi** [comment] 2023-01-13 06:21
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below and thats why it works for some people as they have their own setup:
> 
> `https://github-readme-stats.vercel.app/api?`
> 
> into
> 
> `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?`

Thanks, it works!

**Comment by qd-xiaowang** [comment] 2023-01-13 07:02
Facing the same issue

**Comment by The-Leo** [comment] 2023-01-13 07:12
I know the issue has been fixed now but for learning purposes, what was the issue?

**Comment by KyeOnDiscord** [comment] 2023-01-13 07:31
Facing the same issue

**Comment by rkdtmddnjs97** [comment] 2023-01-13 07:46
Facing the same issue

**Closed by rkdtmddnjs97** 2023-01-13 07:46 UTC
Labels: bug

**Comment by anuraghazra** [comment] 2023-01-13 07:48
Hi everyone, sorry for the downtime. It failed quite unexpectedly. 

I've fixed the issue in #2400 and will deploy the fix in few minutes. It should work after that. 

Turns out that one of the PAT account was suspended and in result caused the retryer logic to fail.

**Comment by KorivashC** [comment] 2023-01-13 07:48
[Fixed]

(https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=KorivashC

Was mentioned above and worked for me

**Comment by anuraghazra** [comment] 2023-01-13 07:58
https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1380227822

Also for everyone who reverted to @rickstaa's URL, if you want you can now change back to the original URL. rick's vercel account might not be able to handle millions of request if everyone starts using it. 

> PS: It's also a better idea to deploy github-readme-stats on your own vercel instance: [guide is here ](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)

**Comment by ysirblack** [comment] 2023-01-13 08:03
The same URL is not working btw. Do we have to do something on our side ?

**Comment by anuraghazra** [comment] 2023-01-13 08:07
> The same URL is not working btw. Do we have to do something on our side ?

Possible that the response is cache, you can burst the cache manually by adding a random param like `ver=2` or just wait 2h. 

https://github-readme-stats.vercel.app/api/?username=anuraghazra&ver=2

**Comment by ysirblack** [comment] 2023-01-13 08:14
Thanks, worked.

**Comment by gia-world** [comment] 2023-01-18 08:51
Thanks, also solved

**Comment by eceakin** [comment] 2024-09-03 15:00
Hello everyone. If you have changed your username, you must also change the places where your username is in the readme file. You should also change the name of the readme file to your new username. I just experienced this problem. I thought it might be helpful for people who may encounter this problem in the future. :)
