### ISSUE TITLE
Card Animation Freezing Issue in README File

### ISSUE THREAD

**Issue by giorgileladze** [anuraghazra/github-readme-stats#3487] opened 2023-11-17 16:09 UTC
### Describe the bug

The animated Cards on the README file occasionally freezes when the file is opened in a new tab. A simple refresh resolves the problem, and the animation resumes as expected.

### Screenshots / Live demo link
![image](https://github.com/anuraghazra/github-readme-stats/assets/101295551/8981d472-7c24-4cb4-a9b5-c32d61d9a08a)

[Link to Video](https://drive.google.com/file/d/10GSqB4fWBqenslydM1gWNtBCR0cC8X-O/view?usp=sharing)

**Comment by qwerty541** [comment] 2023-11-21 19:50
Hey, @giorgileladze! Thanks for your report! I have doubts about if we can do anything about this problem. I assume that this problem appears due to some browser optimizations and can't be resolved from our side. If you experience this too often the solution can be using `disable_animations=true` querystring parameter. If you have any concrete suggestion about how to resolve this feel free to share.

@rickstaa I also interested what do you think about this issue.

**Comment by rickstaa** [comment] 2023-11-21 20:55
> Hey, @giorgileladze! Thanks for your report! I have doubts about if we can do anything about this problem. I assume that this problem appears due to some browser optimizations and can't be resolved from our side. If you experience this too often the solution can be using `disable_animations=true` querystring parameter. If you have any concrete suggestion about how to resolve this feel free to share.
> 
> @rickstaa I also interested what do you think about this issue.

You might be correct about this issue being on the browser or GitHub CDN side. I have yet to experience the problem with the [Brave Browser](https://brave.com/). We can only fix issues we can reproduce 😅.

**Comment by qwerty541** [comment] 2023-11-22 18:52
> > Hey, @giorgileladze! Thanks for your report! I have doubts about if we can do anything about this problem. I assume that this problem appears due to some browser optimizations and can't be resolved from our side. If you experience this too often the solution can be using `disable_animations=true` querystring parameter. If you have any concrete suggestion about how to resolve this feel free to share.
> > @rickstaa I also interested what do you think about this issue.
> 
> You might be correct about this issue being on the browser or GitHub CDN side. I have yet to experience the problem with the [Brave Browser](https://brave.com/). We can only fix issues we can reproduce 😅.

I noticed that our wakatime card contains animations, but there is not query parameter to disable it unlike stats and top languages card. I have opened pull request https://github.com/anuraghazra/github-readme-stats/pull/3496 to give ability for users who experience this issue to avoid the problem. Please check it. I think that we can close this issue after merging https://github.com/anuraghazra/github-readme-stats/pull/3496, since it can't be fixed from our side.

**Closed** 2023-11-23 19:06 UTC
Labels: bug
