### ISSUE TITLE
#github-stats-card not working in mobile phone app

### ISSUE THREAD

**Issue by withrvr** [anuraghazra/github-readme-stats#977] opened 2021-03-29 04:51 UTC
https://github.com/anuraghazra/github-readme-stats#github-stats-card

other cards are working but #github-stats-card
is not working properly in the mobile phones

**Comment by anuraghazra** [comment] 2021-06-09 19:50
Hi @withrvr yes there are few rendering issues on mobile especially because in mobile the markdown renderer and the rendering engine is different. We are looking into it to solve some issues. Thanks!

**Comment by anuraghazra** [comment] 2021-06-09 19:50
duplicate of #215

**Closed by anuraghazra** 2021-06-09 19:50 UTC
