### ISSUE TITLE
Total commit number changes when card width is not set to 500

### ISSUE THREAD

**Issue by CodeNinja-tech** [anuraghazra/github-readme-stats#2284] opened 2022-11-22 10:22 UTC
### Describe the bug

I'm not sure why this happens but, whenever I set the card width to anything other than 500, the total commit number changes to 2.

When the width is set to **440**:
![image](https://user-images.githubusercontent.com/70282966/203288761-3bf22f8e-ceda-47e3-a32e-dedf5f2ebb7f.png)
![image](https://user-images.githubusercontent.com/70282966/203288336-061300fb-bb0e-4b57-9d7c-123b9ed46e3a.png)

Default, at **500**:
![image](https://user-images.githubusercontent.com/70282966/203289116-37dc1cda-2130-4c77-9d46-666319821fdc.png)
![image](https://user-images.githubusercontent.com/70282966/203289254-32d368c1-a361-4812-bc37-01972b95e90a.png)

### Expected behaviour

I expected that the number should stay the same, I'm not sure why it isn't

### Screenshots / Live demo link

![image](https://user-images.githubusercontent.com/70282966/203289510-07a6b4a9-8153-4eea-8fb4-87ec4506376d.png)
![image](https://user-images.githubusercontent.com/70282966/203289540-0d9d952d-498d-4538-9a09-5281031dae74.png)

**Comment by rickstaa** [comment] 2022-11-22 11:54
Hey, @CodeNinja-tech, I looked at your card, and I can not reproduce the issue you are experiencing. It is likely caused by a caching bug that will be fixed by merging https://github.com/anuraghazra/github-readme-stats/pull/2177.

**Width 400**

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=CodeNinja-tech&card_width=400)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=CodeNinja-tech&card_width=400)](https://github.com/anuraghazra/github-readme-stats)
```

**Other width**

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=CodeNinja-tech)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=CodeNinja-tech](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=CodeNinja-tech&card_width=600)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=CodeNinja-tech&card_width=600](https://github.com/anuraghazra/github-readme-stats)
```

**Closed by rickstaa** 2022-11-22 11:54 UTC
Labels: bug

**Comment by CodeNinja-tech** [comment] 2022-11-22 12:55
😄 Awesome! Thanks so much for taking your time to reply !
