### ISSUE TITLE
Card throws maximum retries exceeded error

### ISSUE THREAD

**Issue by brundabharadwaj** [anuraghazra/github-readme-stats#2130] opened 2022-10-05 11:34 UTC
**Describe the bug**
Unable to add top languages used to my profile

**Expected behaviour**
Display most used languages on my profile

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/49773125/194050569-619c3be7-fbac-4a09-b046-44f02ecc2bbd.png)

**Additional context**
Tried accessing the provided URL to my profile as well as adding the same to my profile. Languages are not displayed as expected.
Could you please help me with this? 

Thanks in advance  :)
#hacktoberfest

**Comment by Rajdave69** [comment] 2022-10-05 13:13
same here.

**Comment by SSSDNSY** [comment] 2022-10-05 14:03
+1

**Comment by devpla** [comment] 2022-10-05 14:30
Same here

**Comment by anic4cio** [comment] 2022-10-05 16:24
[How to deploy your own Vercel GitHub Status instance, step-by-step.](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)

**Comment by willster277** [comment] 2022-10-05 16:29
I get that we're all developers, but I don't think deploying our own clone of this app is really a solution.
If the app has a critical bug, it has a critical bug, that will only be fixed by code/deployment changes.

If [your favorite API service] went down, all hell would break loose if they said to their users "deploy it yourself".

**Comment by duberlyguarnizofuentesrivera** [comment] 2022-10-05 17:21
> I get that we're all developers, but I don't think deploying our own clone of this app is really a solution. If the app has a critical bug, it has a critical bug, that will only be fixed by code/deployment changes.
> 
> If [your favorite API service] went down, all hell would break loose if they said to their users "deploy it yourself".

It's not really a bug. Vercel instances cost money. Donating to maintainers so they can afford more instances is the real solution here. This has been discussed a lot before. This is a service provided for free to the users, but sadly it's not free to maintain. Meanwhile, we can only wait. If your stats are critical for your repo, it's a good idea to deploy it yourself. Never depend critical functionality on free services.

https://github.com/anuraghazra/github-readme-stats/issues/1772#issue-1240477488

> "This is likely caused by the public Vercel instance reaching one of the [Github GraphQL limits](https://docs.github.com/en/graphql/overview/resource-limitations#rate-limit). Multiple [PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) tokens have been used to overcome these limits (see [github-readme-stats/blob/master/src/common/retryer.js](https://github.com/anuraghazra/github-readme-stats/blob/master/src/common/retryer.js)) but due to the popularity of GitHub-readme-stats, they sometimes run out. The best solution is to deploy your own Vercel instance. Please check [this guide](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance) on how this is done. You can find more information on this problem in https://github.com/anuraghazra/github-readme-stats/issues/1471. You can also use https://github.com/anuraghazra/github-readme-stats/issues/1471 to let us know the limits are being reached."

**Comment by rickstaa** [comment] 2022-10-05 17:56
@willster277 I fully understand your frustration. This issue, however, is mostly outside our control as it is caused by the popularity of this project. 😅  We use the GraphQL API for fetching the data, but this API is rate limited at 5000 points per hour (see https://www.google.com/url?sa=t&source=web&rct=j&url=https://docs.github.com/en/graphql/overview/resource-limitations%23:~:text%3DThe%2520GraphQL%2520API%2520rate%2520limit,API%2520use%2520different%2520rate%2520limits.&ved=2ahUKEwiAv4CpzMn6AhWKGuwKHYtEDMYQFnoECAsQBQ&usg=AOvVaw1Dw78YN6PD8LW5QBFwl1c6). The main thing we can do is add more PATs to overcome this, for this you have to be patient until @anuraghazra adds new PAT's. Because of this, we ask people to deeply their [own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance) to reduce the load. I also created #2121 and #2122 to mitigate the issue, but we still need to review those. Hope this helps to clear up some confusion about what is causing the issue. 👍

**Comment by FelipeFama** [comment] 2022-10-05 22:15
Check out this link, it helped me:
https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s

**Comment by brundabharadwaj** [comment] 2022-10-06 04:03
> Check out this link, it helped me: https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s
Hi Thanks for sharing the details, during deployment in Vercel facing an issue which gives an error popup stating the value of max duration is between 1 and 10 seconds and in order to increase please upgrade the plan. Can't it be done with the free version? or am I missing out something? . @anuraghazra @FelipeFama

**Comment by anuraghazra** [comment] 2022-10-06 20:11
Hey everyone, sorry for the recent downtimes. 

For the sake of transparency, we get a huge amount of requests per month (it's kind of mind boggling for a side project which I built just for fun). Here's the vercel dashboard statistics: 

![image](https://user-images.githubusercontent.com/35374649/194407743-9af65825-483a-49af-9e16-cac3a5ea5a50.png)

As you can see even with 73% of the responses being cached by vercel the amount of `live` requests are huge, and the bottleneck here is [Personal Access Tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) 

Each PAT have 5000 points, and based on the complexity of the GraphQL query & [resource limitations](https://docs.github.com/en/graphql/overview/resource-limitations) set by GitHub, it's actually very very low considering that amount of requests. 

To circumvent the issue, we currently have 7 PATs (thats 35k points) which sometimes get exhausted. 
Thanks to @rickstaa we are going to add few more probably bumping it up to 10 or 12, hopefully that could help alleviate the downtimes. 

> Note: That these downtimes are temporary, and only lasts for 1hour, since PATs regenerate after 1 hour

------

*So whats the idea way?*


https://github.com/anuraghazra/github-readme-stats/issues/1471#issuecomment-979306704
Deploy on your own vercel instance. WHY? 
It's easy to do, free & reliable. 

- It reduces loads on our vercel instance.
- Your own PAT will give you more concrete stats including private stats
- It ensures that there won't be any downtime on your profile stats because you are the only one who is gonna hit your URL

**Comment by anuraghazra** [comment] 2022-10-06 20:15
> Hi Thanks for sharing the details, during deployment in Vercel facing an issue which gives an error popup stating the value of max duration is between 1 and 10 seconds and in order to increase please upgrade the plan. Can't it be done with the free version? or am I missing out something? . 

@brundabharadwaj sorry for that inconvinence 

Yes you can fix this for free. 

I'm assuming you already forked github-readme-stats on your github, so all you have to do is edit the `vercel.json` and set `"maxDuration": 10`
https://github.com/anuraghazra/github-readme-stats/blob/master/vercel.json#L5

**Comment by brundabharadwaj** [comment] 2022-10-07 10:27
> 

Thanks for the help @anuraghazra . will try it it out!

**Comment by brundabharadwaj** [comment] 2022-10-07 16:31
> > Hi Thanks for sharing the details, during deployment in Vercel facing an issue which gives an error popup stating the value of max duration is between 1 and 10 seconds and in order to increase please upgrade the plan. Can't it be done with the free version? or am I missing out something? .
> 
> @brundabharadwaj sorry for that inconvinence
> 
> Yes you can fix this for free.
> 
> I'm assuming you already forked github-readme-stats on your github, so all you have to do is edit the `vercel.json` and set `"maxDuration": 10` on your end and deploy. https://github.com/anuraghazra/github-readme-stats/blob/master/vercel.json#L5

Hi @anuraghazra , following with the previous discussion, deployment was successful after modification of json file. But the issue persist even after adding my own domain generated. Please let me know if any other details are required from my end .

**Comment by rickstaa** [comment] 2022-10-07 16:55
@brundabharadwaj Did you create a PAT like is explained in the documentation?

10. Create a personal access token (PAT) [here](https://github.com/settings/tokens/new) and enable the repo permissions (this allows access to see private repo stats).
11. Add the PAT as an environment variable named PAT_1 (as shown).

![image](https://user-images.githubusercontent.com/17570430/194609874-d9a8df70-623d-45f0-b301-996b44c93020.png)

**Comment by brundabharadwaj** [comment] 2022-10-07 17:01
> @brundabharadwaj Did you create a PAT and add it to your Vercel instance as explained in the documentation?
> 
> 10. Create a personal access token (PAT) [here](https://github.com/settings/tokens/new) and enable the repo permissions (this allows access to see private repo stats).
> 11. Add the PAT as an environment variable named PAT_1 (as shown).
> 
> ![image](https://user-images.githubusercontent.com/17570430/194609874-d9a8df70-623d-45f0-b301-996b44c93020.png)

@rickstaa  yes I did.

**Comment by rickstaa** [comment] 2022-10-07 17:05
@brundabharadwaj Strange. Can you maybe share your deployment URL?

**Comment by brundabharadwaj** [comment] 2022-10-07 17:07
> @brundabharadwaj Strange. Can you maybe share your deployment URL?

sure, here are the urls
[github-readme-stats-brundabharadwaj.vercel.app](http://github-readme-stats-brundabharadwaj.vercel.app/)

·
Automatic URL

[Learn More](https://vercel.com/docs/concepts/deployments/generated-urls)
[github-readme-stats-git-master-brundabharadwaj.vercel.app](http://github-readme-stats-git-master-brundabharadwaj.vercel.app/)
·
Automatic URL

[Learn More](https://vercel.com/docs/concepts/deployments/generated-urls)
[github-readme-stats-beta-ten-25.vercel.app](http://github-readme-stats-beta-ten-25.vercel.app/)
·
Custom Domain

Thanks for your time!

**Comment by rickstaa** [comment] 2022-10-07 19:31
@brundabharadwaj I checked your deployment, and it looks like the `PAT_1` variable is not added to the Vercel instance or that it does not have the right permissions. Please check if you completed all the steps under the `hammer_and_wrench Step-by-step guide on setting up your own Vercel instance` subsection of the https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance section. I followed these steps myself to be sure our documentation is still up to date, and I had no problems deploying my own Vercel instance.

![image](https://user-images.githubusercontent.com/17570430/194639473-86ddfa15-3b18-4734-8831-48efe17daf9d.png)

**Comment by brundabharadwaj** [comment] 2022-10-08 02:45
@rickstaa Yes, tried deploying again and things are as expected now!
Thank you

**Comment by rickstaa** [comment] 2022-10-08 10:45
> @rickstaa Yes, tried deploying again and things are as expected now! Thank you. But when I click on the image, page what is see is blank! May I know the reason behind it? ![image](https://user-images.githubusercontent.com/49773125/194684414-fe4fb6a6-2a71-4a2a-9b8d-c869d42ca9de.png)

Great to hear! I checked your instance and for me, it is working correctly:

[![Anurag's GitHub stats](https://github-readme-stats-brundabharadwaj.vercel.app/api?username=rickstaa
)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats-brundabharadwaj.vercel.app/api?username=rickstaa
)](https://github.com/anuraghazra/github-readme-stats)
```

Maybe your theme settings cause the card to be fully black.

**Comment by rickstaa** [comment] 2022-10-08 10:46
Let's track this on #1471 again.

**Closed by rickstaa** 2022-10-08 10:46 UTC

**Comment by AtanasovaVanya** [comment] 2023-01-06 15:42
I followed the suggestions by @rickstaa and everything works as intended now. Thanks!

**Comment by YulietM** [comment] 2023-01-06 15:45
hi
they should only add a variable increasing the token's

This is what I had with the error:
`    <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

and adding (sigma-five) so it was solved:
`    <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

**Comment by turrnut** [comment] 2023-01-13 20:36
same issue

**Comment by glaucia86** [comment] 2023-06-20 14:53
FIY: easy solution

[https://gh-stats-gen.vercel.app/](https://gh-stats-gen.vercel.app/)
