### ISSUE TITLE
Maximum retries exceeded" error.

### ISSUE THREAD

**Issue by MustafaAliCetinkaya** [anuraghazra/github-readme-stats#2402] opened 2023-01-13 11:36 UTC
### Describe the bug

Personal access tokens are currently failing, I see the "Maximum retries exceeded" error.

**Comment by jimbolimbo3** [comment] 2023-01-13 11:38
![Screenshot 2023-01-13 at 12 38 32](https://user-images.githubusercontent.com/2467359/212311859-d9473b2b-d1d2-411e-9b36-1c65ae77136c.png)
Me too, unfortunately

**Comment by DalpatRathore** [comment] 2023-01-13 12:00
Some server PAT limits or depletion causes the known issue, I am facing it too. The best solution, for now, is to deploy on your own instance (see https://github.com/anuraghazra/github-readme-stats/issues/1471).

**Comment by itsmanibharathi** [comment] 2023-01-13 12:39
![image](https://user-images.githubusercontent.com/76097762/212321822-260d11d4-d3b0-486c-9697-66e04e76b1b0.png)
4
I too have same issue

**Comment by anuraghazra** [comment] 2023-01-13 13:02
Hi it should resolve within an hour, our PATs are invalidated. 

But a better option for would be to deploy github-readme-stats on your own Vercel instance. 
https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance

Pros: 
- No downtime
- Private commits will also be counted

**Comment by Juknum** [comment] 2023-01-13 13:49
Duplicate of #2336 :eyes:

**Comment by IamManchanda** [comment] 2023-01-13 14:50
Hi @anuraghazra ... I have self deployed it (changed maxDuration to `10` too as I am on a Hobby Plan) 
=> https://github-readme-stats-ruddy-six.vercel.app

But still getting Maximum retries exceeded error

![Harry Manchanda's Github Stats](https://github-readme-stats-ruddy-six.vercel.app/api?username=IamManchanda&theme=flag-india&count_private=true&show_icons=true&line_height=25&hide=prs,issues,contribs&include_all_commits=true)

**Comment by fatimakay** [comment] 2023-01-13 15:04
Facing the same issue

**Comment by serginator** [comment] 2023-01-13 15:08
I think the problem with the self deployed ones from a fork is that the urls generated by vercel are pointing to the real repo, not the fork :(

**Comment by nathanredblur** [comment] 2023-01-13 16:05
Me too

**Comment by San3-Cod3** [comment] 2023-01-13 16:47
Still have this issue, and attempting to deploy my own is asking for a phone number for verification which I will not give under any circumstances; don't even have a number attached to my GitHub account either way as far as I know.  Very unnecessary asking for this, in my opinion.

**Comment by KatarzynaChmielecka** [comment] 2023-01-13 17:06
and also I'm bug buddy ;)

**Comment by ruchernchong** [comment] 2023-01-13 17:23
> 



> Hi it should resolve within an hour, our PATs are invalidated.
> 
> But a better option for would be to deploy github-readme-stats on your own Vercel instance. https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance
> 
> Pros:
> 
> * No downtime
> * Private commits will also be counted

Do you mean the current implementation now will now count the private commits?

**Comment by ruchernchong** [comment] 2023-01-13 18:11
> Hi @anuraghazra ... I have self deployed it (changed maxDuration to `10` too as I am on a Hobby Plan) => https://github-readme-stats-ruddy-six.vercel.app
> 
> But still getting Maximum retries exceeded error
> 
> ![Harry Manchanda's Github Stats](https://camo.githubusercontent.com/b5dacea16030119c76d777c00bcc8a13b62620c2ae4e5ba519460a5a7762f34a/68747470733a2f2f6769746875622d726561646d652d73746174732d72756464792d7369782e76657263656c2e6170702f6170693f757365726e616d653d49616d4d616e6368616e6461267468656d653d666c61672d696e64696126636f756e745f707269766174653d747275652673686f775f69636f6e733d74727565266c696e655f6865696768743d323526686964653d7072732c6973737565732c636f6e747269627326696e636c7564655f616c6c5f636f6d6d6974733d74727565)

2nd this. I am also facing the same problem with my own hosting.

**Comment by Scemist** [comment] 2023-01-13 20:08
> Hi @anuraghazra ... I have self deployed it (changed maxDuration to `10` too as I am on a Hobby Plan) => https://github-readme-stats-ruddy-six.vercel.app
> 
> But still getting Maximum retries exceeded error
> 
> ![Harry Manchanda's Github Stats](https://camo.githubusercontent.com/b5dacea16030119c76d777c00bcc8a13b62620c2ae4e5ba519460a5a7762f34a/68747470733a2f2f6769746875622d726561646d652d73746174732d72756464792d7369782e76657263656c2e6170702f6170693f757365726e616d653d49616d4d616e6368616e6461267468656d653d666c61672d696e64696126636f756e745f707269766174653d747275652673686f775f69636f6e733d74727565266c696e655f6865696768743d323526686964653d7072732c6973737565732c636f6e747269627326696e636c7564655f616c6c5f636f6d6d6974733d74727565)

Same here, I deployed my own hosting in vercel with the correct PAT_1 env variable with correct token permissions. The problem doesn't look in the host.

**Comment by ajfm88** [comment] 2023-01-13 20:23
The "most used languages" one is back and working as normal, but the github stats one

https://github-readme-stats.vercel.app/api?username=*yourusernamehere*&show_icons=true&theme=transparent

is still not working.

**Comment by KatarzynaChmielecka** [comment] 2023-01-13 20:29
> The "most used languages" one is back and working as normal, but the github stats one
> 
> https://github-readme-stats.vercel.app/api?username=*yourusernamehere*&show_icons=true&theme=transparent
> 
> is still not working.

For me both not working.

**Comment by SyafaHadyan** [comment] 2023-01-13 22:37
![SmartSelect_20230114-063516_GitHub.jpg](https://user-images.githubusercontent.com/107655102/212431821-84a013a2-7a62-4b37-9d90-32c7955bd7ec.jpg)

**Comment by SyafaHadyan** [comment] 2023-01-13 22:38
> The "most used languages" one is back and working as normal, but the github stats one
> 
> https://github-readme-stats.vercel.app/api?username=*yourusernamehere*&show_icons=true&theme=transparent
> 
> is still not working.

Both not working

**Comment by SyafaHadyan** [comment] 2023-01-14 02:47
Working on GitHub Mobile
![SmartSelect_20230114-104619_GitHub.jpg](https://user-images.githubusercontent.com/107655102/212447388-e71664f5-59b8-4383-a916-3d1a781c4d9b.jpg)

**Comment by anuraghazra** [comment] 2023-01-14 09:39
> Same here, I deployed my own hosting in vercel with the correct PAT_1 env variable with correct token permissions. The problem doesn't look in the host.

@Scemist can you double check on your vercel dashboard that the PAT_1 is marked as "production"? 

Here's the docs for adding env: 
https://vercel.com/docs/concepts/projects/environment-variables

**Comment by hello-sabira** [comment] 2023-01-14 10:44
Same problem here too :(

**Comment by KatarzynaChmielecka** [comment] 2023-01-14 11:30
For me work now, but this stats is falsy. It still counts last year :( 
![image](https://user-images.githubusercontent.com/56206231/212469742-cae7ce94-79f3-45d3-b66c-b9f9028b48d6.png)

**Comment by claudiotancredi** [comment] 2023-01-14 11:56
> Hi it should resolve within an hour, our PATs are invalidated.
> 
> But a better option for would be to deploy github-readme-stats on your own Vercel instance. https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance
> 
> Pros:
> 
> * No downtime
> * Private commits will also be counted

I solved it by deploying my own Vercel instance. In addition to what is already [reported here](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance), there are other few things that I did at the end of the process. You should:

1. Go on the Deployment tab of the Vercel project. Then, under Deployment Status, expand Assigning Domain and copy the Custom Domain;
2. Go to your profile README.md and be sure to change the url that you use so that it starts with your Custom Domain that you copied in step 1. For me, instead of having _https://github-readme-stats.vercel.app_ it was _https://github-readme-stats-ruby-one.vercel.app_ .

As you can see [on my profile README](https://github.com/claudiotancredi/claudiotancredi), it appears to be working properly.

**Comment by ruchernchong** [comment] 2023-01-14 17:49
> > Hi it should resolve within an hour, our PATs are invalidated.
> > But a better option for would be to deploy github-readme-stats on your own Vercel instance. https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance
> > Pros:
> > 
> > * No downtime
> > * Private commits will also be counted
> 
> I solved it by deploying my own Vercel instance. In addition to what is already [reported here](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance), there are other few things that I did at the end of the process. You should:
> 
> 1. Go on the Deployment tab of the Vercel project. Then, under Deployment Status, expand Assigning Domain and copy the Custom Domain;
> 2. Go to your profile README.md and be sure to change the url that you use so that it starts with your Custom Domain that you copied in step 1. For me, instead of having _https://github-readme-stats.vercel.app_ it was _https://github-readme-stats-ruby-one.vercel.app_ .
> 
> As you can see [on my profile README](https://github.com/claudiotancredi), it appears to be working properly.

This is working for me.

**Comment by eggnaut** [comment] 2023-01-15 02:36
Is there any way this can be fixed without deploying yourself on Vercel?

**Comment by SyafaHadyan** [comment] 2023-01-15 03:26
> Is there any way this can be fixed without deploying yourself on Vercel?
> 
> Will this issue keep happening, or is it a bug that can be fixed by the maintainers?

I deployed on Vercel for free, fork the repo and make PAT(Classic).

Or you can see the instructions [Here](https://github.com/anuraghazra/github-readme-stats)

**Comment by RedHeadphone** [comment] 2023-01-15 04:44
Deploying own Vercel works for few hours then again `Maximum retries exceeded` error is returned from the API, my guess is that github has updated some limitation on usage of PAT

**Comment by eggnaut** [comment] 2023-01-15 15:40
@RedHeadphone - So you have to continuously redeploy after the PAT limit is reached?

**Comment by RedHeadphone** [comment] 2023-01-15 16:35
that did make the API work for first time, but now even after updating PAT with new one, still old error is returned Maximum retries exceeded

**Comment by RedHeadphone** [comment] 2023-01-15 16:45
I created a new project in vercel using same PAT which was giving me `Maximum retries exceeded`, the new vercel project seems to be working. I am not sure but I think this issue might lie with vercel.

**Comment by mojixcoder** [comment] 2023-01-15 17:19
I'm having this problem too.

**Comment by rickstaa** [comment] 2023-01-19 08:11
Duplicate of #https://github.com/anuraghazra/github-readme-stats/issues/1471.

**Closed by rickstaa** 2023-01-19 08:11 UTC
Labels: bug

**Comment by mk3709** [comment] 2023-03-21 14:09
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel what should be done
