### ISSUE TITLE
Waka Card: Compact mode does not work with Lang Count

### ISSUE THREAD

**Issue by Nathan13888** [anuraghazra/github-readme-stats#1115] opened 2021-06-05 15:13 UTC
**Describe the bug**
When using the waka card widget, the `langs_count` limits the number of languages that appear. This works as expected in the default/normal layout mode.

**Expected behavior**
When `layout=compact` is set, the layout of the widget should change the compact version. Since there is the `langs_count` setting, it should only show a certain number of languages. **This seems to work with the Top Languages card**

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
`https://github-readme-stats.vercel.app/api/wakatime?username=Nathan13888&langs_count=8&hide_border=true&bg_color=282a36&title_color=fdaaaa&text_color=fdaaaa&icon_color=fdaaaa` (works as expected)
![image](https://user-images.githubusercontent.com/29968201/120896243-be44cb80-c5ee-11eb-88ba-43e663128c32.png)

`https://github-readme-stats.vercel.app/api/wakatime?username=Nathan13888&langs_count=8&layout=compact&hide_border=true&bg_color=282a36&title_color=fdaaaa&text_color=fdaaaa&icon_color=fdaaaa` (`langs_count` seems ignored or not applied)
![image](https://user-images.githubusercontent.com/29968201/120896218-99505880-c5ee-11eb-81d3-8c411a6b2c66.png)

**Comment by anuraghazra** [comment] 2021-06-05 16:20
Hi @Nathan13888 thanks for reporting the issue we will look into it.

**Comment by florianbussmann** [comment] 2021-06-05 16:32
@anuraghazra this is a duplicate of #1038 and I fixed the issue last month. The PR (#1041) is waiting for your approval

**Comment by Nathan13888** [comment] 2021-06-05 17:32
Hmmm. PR #1041 does appear to fix the issue @anuraghazra. Also, not sure why issue #1038 didn't show up when I searched "waka" 🤷

**Comment by anuraghazra** [comment] 2021-06-07 06:59
Ah i see. @florianbussmann Thanks for the PR. I totally missed it. Will review and merge today.

**Comment by anuraghazra** [comment] 2021-06-09 19:11
#1038 is merged should be fixed now.

**Closed by anuraghazra** 2021-06-09 19:11 UTC
Labels: bug
