### ISSUE TITLE
Not Showing XML

### ISSUE THREAD

**Issue by sudip-mondal-2002** [anuraghazra/github-readme-stats#1102] opened 2021-05-31 19:08 UTC
**Describe the bug**
When I use the API for most used languages it's not showing the XML

**Expected behavior**
It should show the percentage weight of lines of XML codes written in the repositories of mine

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/74463091/120232387-1ab38e00-c271-11eb-891b-7908472c9278.png)
![image](https://user-images.githubusercontent.com/74463091/120232462-3dde3d80-c271-11eb-991f-39049337ecef.png)
![image](https://user-images.githubusercontent.com/74463091/120232494-4898d280-c271-11eb-93c5-ea65ffae0396.png)
![image](https://user-images.githubusercontent.com/74463091/120232540-5fd7c000-c271-11eb-997a-0bac959048e1.png)

**Additional context**

**Comment by anuraghazra** [comment] 2021-06-05 16:26
Top langs card counts langs by how much code (in bytes) you have in the repo.
It's not showing XML because you have so little XML code that it's got underemphasize and overwritten by other languages.

Even by setting the langs_count to 10 it did not show up 
https://github-readme-stats.vercel.app/api/top-langs/?username=sudip-mondal-2002&langs_count=20

**Comment by sudip-mondal-2002** [comment] 2021-06-06 04:11
I have set the lang count to 20, and to be sure I have written more XML codes than C codes, but still it not showing

**Comment by anuraghazra** [comment] 2021-06-09 19:25
Hi @sudip-mondal-2002 i've looked through your stats and also inspected the github api data, but for some reason I cannot see any XML from it, the github API itself isn't sending it in. 

![image](https://user-images.githubusercontent.com/35374649/121416513-83dc8500-c986-11eb-89ef-f75dd99e1ae2.png)

**Comment by sudip-mondal-2002** [comment] 2021-06-10 04:31
Can you share the end point for this API?

**Comment by tomschr** [comment] 2021-06-15 14:48
Hi sorry to interrupt, but I have the same issue with my repository (https://github.com/tomschr). For some reason, it shows "XSLT" instead of "XML", although it shouldn't.

**Comment by sudip-mondal-2002** [comment] 2021-06-15 16:00
I think it's a problem from github side not from this repo

**Comment by cicirello** [comment] 2021-06-28 20:28
@sudip-mondal-2002 @anuraghazra I stumbled upon this issue while looking for something else, and I believe I have the explanation for why you are not seeing XML.  It is on GitHub's side, but it is by definition and not a bug.  By default, GitHub excludes languages that are classified as `data` or `prose` from the language statistics for a repository. And XML is classified as `data`. So no matter how much XML you have, the default language statistics for a repository won't include it.

GitHub uses [Linguist[(https://github.com/github/linguist) to compute the language statistics of a repository.  In its documentation, it explains [how it works](https://github.com/github/linguist/blob/master/docs/how-linguist-works.md), where you can see the part about excluding `data` languages.  You'll find XML listed as a `data` language in Linguist's [languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).

However, Linguist provides the ability to override the default behavior.  See Linguist's [documentation on overrides](https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes).  It looks like you should be able to use the `linguist-detectable` gitattribute in a `.gitattributes` file in any repositories for which you want XML included in GitHub's language stats (or any other language excluded as data or prose). 

Specifically, create a `.gitattributes` file in the root of the repository where you want XML included in GitHub's language stats, and add the following line to it:
```
*.xml linguist-detectable
```
That should cause GitHub to begin to include XML in that repository's language statistics, and in turn should cause github-readme-stats to start to pick it up.

**Comment by andreakaye** [comment] 2021-06-28 21:04
Thanks! I know it’s Jabberwocky and I could read the doc but I’m still
working on learning basic coding. I appreciate that ❤️❤️❤️

**Comment by rickstaa** [comment] 2023-05-06 08:36
> @sudip-mondal-2002 @anuraghazra I stumbled upon this issue while looking for something else, and I believe I have the explanation for why you are not seeing XML. It is on GitHub's side, but it is by definition and not a bug. By default, GitHub excludes languages that are classified as `data` or `prose` from the language statistics for a repository. And XML is classified as `data`. So no matter how much XML you have, the default language statistics for a repository won't include it.
> 
> GitHub uses [Linguist](https://github.com/github/linguist) to compute the language statistics of a repository. In its documentation, it explains [how it works](https://github.com/github/linguist/blob/master/docs/how-linguist-works.md), where you can see the part about excluding `data` languages. You'll find XML listed as a `data` language in Linguist's [languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).
> 
> However, Linguist provides the ability to override the default behavior. See Linguist's [documentation on overrides](https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes). It looks like you should be able to use the `linguist-detectable` gitattribute in a `.gitattributes` file in any repositories for which you want XML included in GitHub's language stats (or any other language excluded as data or prose).
> 
> Specifically, create a `.gitattributes` file in the root of the repository where you want XML included in GitHub's language stats, and add the following line to it:
> 
> ```
> *.xml linguist-detectable
> ```
> 
> That should cause GitHub to begin to include XML in that repository's language statistics, and in turn should cause github-readme-stats to start to pick it up.

@cicirello is correct, this is an upstream problem. Closing this for now.

**Closed by rickstaa** 2023-05-06 08:36 UTC
Labels: bug, lang-card
