### ISSUE TITLE
Wrong Commit Count , correct count on github api.

### ISSUE THREAD

**Issue by Ingenious-c0der** [anuraghazra/github-readme-stats#2181] opened 2022-10-11 17:10 UTC
### Describe the bug

When I use the link with options: include private and include all the total commit count returned is 176, but in reality it is around 655. It was working fine till yesterday, with no changes made today, it's bugged.

when I do not use the include all option it shows 554 for 2022 
when I do not use the include private option it shows 483 
when I use both it shows 176 instead of 665

https://api.github.com/search/commits?q=author:Ingenious-c0der -> 483

### Expected behaviour

Commit count should be 665 when I use include all and include private options 

### Screenshots / Live demo link

![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Ingenious-c0der&show_icons=true&theme=radical&count_private=true&include_all_commits=true)

**Comment by Nikhil562** [comment] 2022-10-11 19:57
please assign this to me , I can fix this issue

**Comment by rickstaa** [comment] 2022-10-12 07:15
@Ingenious-c0der this is likely a duplicate of https://github.com/anuraghazra/github-readme-stats/issues/1515. Merging https://github.com/anuraghazra/github-readme-stats/pull/2177 will fix this issue. You can already use these on your own fork. They are not yet merged into the master because we have to ensure the GraphQL and Vercel limits are not hit. We will likely implement this as an opt-in for Vercel instance and Github Action users (see https://github.com/anuraghazra/github-readme-stats/issues/2179 and https://github.com/anuraghazra/github-readme-stats/pull/2159).

@Nikhil562 If you think it is caused by something else, feel free to create a PR. 👍🏻

**Closed** 2022-10-12 07:15 UTC
Labels: bug

**Comment by asrivastav-aag** [comment] 2023-01-11 07:45
I'm also having the same problem. Stats are showing wrong commit count, and may be other stats also.

My total commits for 2023 (at the time of this post) is/was 23.
![image](https://user-images.githubusercontent.com/110137595/211747094-3c526b63-6569-4e2d-8638-67c3b753df82.png)

Thanks for looking into it.
