### ISSUE TITLE
Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by AmyLim328** [anuraghazra/github-readme-stats#2382] opened 2023-01-12 07:51 UTC
### Describe the bug

Cannot read properties of undefined (reading 'user')

### Expected behaviour

I hope that stats cards will be shown

### Screenshots / Live demo link

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=amylim328&layout=compact&theme=dark)](https://github.com/anuraghazra/github-readme-stats)
![Amy's GitHub stats](https://github-readme-stats.vercel.app/api?username=amylim328&show_icons=true&theme=dark)

**Comment by Dot32IsCool** [comment] 2023-01-12 08:14
Am getting this too

**Comment by oscar-defelice** [comment] 2023-01-12 08:42
Duplicate of #2380

**Comment by rickywesker** [comment] 2023-01-12 09:56
Same Issue here

**Comment by yogiealfin** [comment] 2023-01-12 10:51
I have the same issue

**Comment by Ser-AM** [comment] 2023-01-12 10:54
same problem here

**Comment by e-candeloro** [comment] 2023-01-12 11:00
same problem here

**Comment by XiaMoHuaHuo-CN** [comment] 2023-01-12 11:22
同样的问题，我名字里有`-`这个字符就不行

**Comment by Lorena-Mattos** [comment] 2023-01-12 11:23
Same problem here too

**Comment by Kot-Alenya** [comment] 2023-01-12 11:25
Same problem here too

**Comment by ilyamixaltik** [comment] 2023-01-12 11:30
I have the same issue

**Comment by arth-inacio** [comment] 2023-01-12 11:34
same

**Comment by bormaxi8080** [comment] 2023-01-12 11:37
I have same issue:

https://github-readme-stats.vercel.app/api/top-langs/?username=bormaxi8080&theme=dark&langs_count=10

https://github-readme-stats.vercel.app/api?username=bormaxi8080&count_private=true&show_icons=true&theme=dark

**Comment by Neftyr** [comment] 2023-01-12 11:53
Hello everyone,

seems like git issue, you can solve it by changing below:

```html
https://github-readme-stats.vercel.app/api?
```
into

```html
https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
```

**Comment by bormaxi8080** [comment] 2023-01-12 12:08
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

It works. Thanks!

**Comment by cubxxw** [comment] 2023-01-12 12:09
> Hello everyone,
> 
> 大家好，
> 
> seems like git issue, you can solve it by changing below:
> 
> 看起来像git问题，你可以通过修改以下内容来解决它：
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> 变成
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

May I ask if this stability is in effect for a long time

**Comment by ozturkgurbuz** [comment] 2023-01-12 12:18
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

Thanks working for now

**Comment by Victor0596647** [comment] 2023-01-12 12:24
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```
@Neftyr now it works, I guess there is problem with the previous link

**Comment by Reckit075** [comment] 2023-01-12 12:33
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

It works. Thanks

**Comment by MiChaelinzo** [comment] 2023-01-12 12:35
To me it didn't

**Comment by Kminzzi** [comment] 2023-01-12 12:37
```
[![Top Langs](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs?username=Kminzzi&layout=compact)](https://github.com/KMinzzi/github-readme-stats)
```
Try changing your username.

**Comment by MiChaelinzo** [comment] 2023-01-12 12:51
Fixed mine I thought I need to change masterrstaa-rickstaa to my username.

**Comment by NoahNinja100** [comment] 2023-01-12 13:09
Mine is just the title and image invalid

**Comment by Irene-123** [comment] 2023-01-12 13:46
Is it a temporary solution or permanent?

**Comment by NexON39** [comment] 2023-01-12 13:49
https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?

not work for me ;(

**Comment by modernpacifist** [comment] 2023-01-12 13:52
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

Nice, kudos to you

**Comment by NexON39** [comment] 2023-01-12 13:53
it works though

**Comment by danielamorattodev** [comment] 2023-01-12 14:29
> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

It's works! Thank you for help.

**Comment by 197naveen** [comment] 2023-01-12 15:02
same issue, but worked after changing url

> Hello everyone,
> 
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

Thanks it worked!

**Comment by Walter-Jucah** [comment] 2023-01-12 15:57
> > Hello everyone,
> > seems like git issue, you can solve it by changing below:
> > ```
> > https://github-readme-stats.vercel.app/api?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > into
> > ```
> > https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> > ```
> 
> @Neftyr now it works, I guess there is problem with the previous link

thank you

**Comment by RhonnieAl** [comment] 2023-01-12 17:58
> seems like git issue, you can solve it by changing below:
> 
> ```
> https://github-readme-stats.vercel.app/api?
> ```
> 
> into
> 
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

Hey @ioanat94 you can fix your git stats issue with this fix :)

**Comment by ioanat94** [comment] 2023-01-12 18:02
> 

Awesome! Thank you :D

**Comment by Sushantlama** [comment] 2023-01-12 20:16
finally it worked .phew

**Comment by rickstaa** [comment] 2023-01-12 21:42
Duplicate of #2380.

**Closed by rickstaa** 2023-01-12 21:42 UTC
Labels: bug

**Comment by Castel4n1** [comment] 2023-01-12 23:20
> ```
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> ```

**Comment by rickstaa** [comment] 2023-01-13 00:21
> > ```
> > https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> > ```

Please check https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1381025166. We will likely also hit the rate limiter on my branch if everybody uses it. Best solution is to deploy your own Vercel instance.
