### ISSUE TITLE
Bug on github stats and most languages used

### ISSUE THREAD

**Issue by Nilson360** [anuraghazra/github-readme-stats#2405] opened 2023-01-13 18:32 UTC
### Describe the bug

Something went wrong! file a issue at https://tiny.one/readme-stats : Please add env variable called PAT_1 with your github token in vercel

**Comment by TheGamer3514** [comment] 2023-01-14 13:32
i am also getting this issue.

**Comment by claudiotancredi** [comment] 2023-01-14 14:28
Duplicate of #2404

**Comment by claudiotancredi** [comment] 2023-01-14 14:29
Duplicate of #2402

**Comment by wang-yurin** [comment] 2023-01-15 11:30
change `https://github-readme-stats.vercel.app` to `https://github-readme-stats-ruby-one.vercel.app`

**Comment by Devarshi0-1** [comment] 2023-01-15 15:40
It worked! Thanks!

**Comment by rickstaa** [comment] 2023-01-22 10:17
It should be fixed for now! Feel free to comment on https://github.com/anuraghazra/github-readme-stats/issues/1515 if things break again.

**Closed by rickstaa** 2023-01-22 10:17 UTC
Labels: bug
