### ISSUE TITLE
Transparent background for the Cards

### ISSUE THREAD

**Issue by HaiderSultanArc** [anuraghazra/github-readme-stats#1981] opened 2022-08-27 00:12 UTC
**Problem**
Github has multiple themes and it looks really good when cards can blend in. We can set bg_color to match the dark theme but if someone is on a bright theme or some other theme then the card looks different.

**Solution**
Allow no_bg property where the card is transparent. No matter what the theme of Github is for someone, the cards will blend with it.

**Alternatives I tried**
I tried to write color code for transparent but that doesn't work I guess.

**Additional context**

![image](https://user-images.githubusercontent.com/59045242/187005898-46b5bb6b-9b5c-43c7-b8cf-e4b7e5b9c0ea.png)

This is the target, but I have set the bg_color property to match the dark theme here. A transparent or no_bg property would do the same.

![image](https://user-images.githubusercontent.com/59045242/187005971-434b8c22-b45f-4d58-8dea-504931e7ab26.png)

On the white theme, I would love them to be white.

**Comment by rickstaa** [comment] 2022-08-27 11:49
Duplicate of #1807.

**Closed by rickstaa** 2022-08-27 11:49 UTC

**Comment by HaiderSultanArc** [comment] 2022-08-27 14:42
> Duplicate of #1807.

Thanks

**Comment by HaiderSultanArc** [comment] 2022-08-27 15:05
We can also add the `bg_color=00000000` property to the card tag to make it transparent.
