### ISSUE TITLE
Readme-stats asks for an env variable.

### ISSUE THREAD

**Issue by jesusalberto18** [anuraghazra/github-readme-stats#2145] opened 2022-10-06 14:14 UTC
Hello @anuraghazra,
I've been having this problem the entire week, it seemed like it already worked out but today it launched this error again.

![IMG_20221006_100325.jpg](https://user-images.githubusercontent.com/105027465/194335582-84d19790-97c1-470e-9f0a-a73044734aba.jpg)

It asks for an env variable that I don't know anything about. Any idea of how I can solve it?
Thanks!

**Comment by RaheemAmer** [comment] 2022-10-06 14:17
Same here

**Comment by jesusalberto18** [comment] 2022-10-06 14:25
Yes, @RaheemAmer. I checked my profile now and it's working out again.

![IMG_20221006_102425.jpg](https://user-images.githubusercontent.com/105027465/194338876-6c6d07bb-f3a3-479a-b124-fb686ebf4b0f.jpg)

I will update if that problem occurs again.

**Comment by rickstaa** [comment] 2022-10-06 14:54
Duplicate of #2130.

**Closed** 2022-10-06 14:53 UTC
