### ISSUE TITLE
Theme transparent not working on Chrome

### ISSUE THREAD

**Issue by hoangminhtran94** [anuraghazra/github-readme-stats#2921] opened 2023-07-07 18:19 UTC
### Describe the bug

Using them=transparent does not work on Chrome. Response error: "Failed to load resource: the server responded with a status of 504"

### Expected behavior

The transparent theme works.

### Screenshots / Live demo link

![image](https://github.com/anuraghazra/github-readme-stats/assets/95241885/1f43cf0c-8bfc-4908-8ee3-d83913153b3f)
![image](https://github.com/anuraghazra/github-readme-stats/assets/95241885/c5a165db-0825-4752-9417-0a65eb3c9483)

**Comment by qwerty541** [comment] 2023-07-07 20:03
This issue is not related to transparent or any other theme, it is a duplicate of https://github.com/anuraghazra/github-readme-stats/issues/2603 caused by a timeout in GitHub. The reason I think the problem is at GitHub's side is that if you reload the page, the cards often appear.

**Closed by qwerty541** 2023-07-07 20:03 UTC
Labels: bug
