### ISSUE TITLE
[Top Languages Card] Jupyter Notebook is not displaying correctly with compact layout

### ISSUE THREAD

**Issue by t-montes** [anuraghazra/github-readme-stats#2732] opened 2023-05-18 06:13 UTC
### Describe the bug

In Top Languages Card, Jupyter Notebook % is out of layout when compact layout is used

### Expected behavior

I would expect the app to make font smaller in this case, or adjust the layout, to let all the text get into the card

### Screenshots / Live demo link

![image](https://github.com/anuraghazra/github-readme-stats/assets/69558777/3a6380b4-4750-478d-8a1a-ea78f0a020d0)

**Comment by t-montes** [comment] 2023-05-18 06:18
I will try to work on it to fix this bug ^

**Comment by rickstaa** [comment] 2023-05-19 08:35
Amazing. I assigned you to the issue. You are welcome to request a review when you create a pull request. The minimum card width should probably be adjusted for the languages that are on the card. In the meantime you can use the `card_width` flag to solve the issues you are experiencing.

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=t-montes&layout=compact&langs_count=10&card_width=350)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=t-montes&layout=compact&langs_count=10&card_width=350)](https://github.com/anuraghazra/github-readme-stats)
```

**Comment by rickstaa** [comment] 2023-07-03 06:58
Duplicate of #2619.

**Closed by rickstaa** 2023-07-03 06:58 UTC
Labels: bug, hacktoberfest, :star: top bug
