### ISSUE TITLE
Make smaller when possible

### ISSUE THREAD

**Issue by donno2048** [anuraghazra/github-readme-stats#555] opened 2020-10-06 15:00 UTC
Even when I use `hide_rank=true&hide_title=true` the whole thing stays wide
I think it would be best if the card will get 'thinner' when using `hide_rank=true`

**Comment by anuraghazra** [comment] 2020-10-17 13:18
Thanks for opening the issue @donno2048.

Closing this as of duplicate of #65 #110 #108

**Closed by anuraghazra** 2020-10-17 13:18 UTC
