### ISSUE TITLE
C++ could not be hidden in Top Langs

### ISSUE THREAD

**Issue by swapnanildutta** [anuraghazra/github-readme-stats#251] opened 2020-07-29 05:56 UTC
**Describe the bug**
When I wanted to hide the C++ from Top Langs, it just didn't work. Instead, it hid the C language bar.

**Expected behavior**
I expected to type hide=c++ in the top langs API and it would hide the c++ bar. I even tried using cpp if that was valid but didn't work.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
The api calling
![image](https://user-images.githubusercontent.com/47251193/88762007-ed4c0e80-d18d-11ea-961d-25251f85eb9b.png)
The result, left one is earlier top langs card, right one after hiding c++
![image](https://user-images.githubusercontent.com/47251193/88762045-02c13880-d18e-11ea-9efb-e2d12655088a.png)

**Additional context**

**Comment by ngtrhieu** [comment] 2020-07-29 06:28
The plus in "c++" is URI reserved character, as specified in [Wikipedia](https://en.wikipedia.org/wiki/Percent-encoding)
You should use "c%2B%2B" instead of "c++". i.e:
```
[![swapnanildutta](https://github-readme-stats.vercel.app/api/top-langs/?username=swapnanildutta&hide=c%2B%2B)](https://github.com/swapnanildutta)
``` 
Demo:
[![swapnanildutta](https://github-readme-stats.vercel.app/api/top-langs/?username=swapnanildutta&hide=c%2B%2B)](https://github.com/swapnanildutta)

For your record, if you want to hide "Jupyter Notebook", you should use "jupyter%20notebook" instead:
[![swapnanildutta](https://github-readme-stats.vercel.app/api/top-langs/?username=swapnanildutta&hide=jupyter%20notebook)](https://github.com/swapnanildutta)

**Comment by anuraghazra** [comment] 2020-07-29 06:58
@swapnanildutta Hi hope you resolved the issue. :) we updated the docs with the information provided by @ngtrhieu in #252 

Duplicate of #201 #220 #194

**Closed by anuraghazra** 2020-07-29 06:58 UTC

**Comment by swapnanildutta** [comment] 2020-07-29 08:01
Thanks for the help !
