### ISSUE TITLE
The 'Total Commits' is being shown in a bad format

### ISSUE THREAD

**Issue by virejdasani** [anuraghazra/github-readme-stats#964] opened 2021-03-25 14:08 UTC
**Describe the bug**
I have over 2 million commits this year.
The Total commits in the GitHub stats card is showing 2267.6k
This should not be the case because it reads: two thousand two hundred and seven point six thousand.

**Expected behavior**
It should show 2.27 million or 2.27M

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
- This is a screenshot:
![Screenshot 2021-03-25 at 7 36 03 PM](https://user-images.githubusercontent.com/67495678/112485849-5a598780-8da1-11eb-81ac-3418851896de.png)
- This is the card rendered in via markdown:
![Github stats](https://github-readme-stats.vercel.app/api?username=virejdasani&count_private=true&show_icons=true&theme=radical)

**Additional context**
If you are wondering how I have these many commits, check out my repository [Commited](https://github.com/virejdasani/commited)

**Comment by virejdasani** [comment] 2021-03-25 17:37
The image card showed what the image shows. The total commits in the markdown card just changed from 2.27M to 7.2k commits

**Comment by Mdsp9070** [comment] 2021-03-29 15:29
I'm having this same issue!

**Comment by rickstaa** [comment] 2023-05-06 08:56
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/564

**Closed by rickstaa** 2023-05-06 08:56 UTC
Labels: bug, stats-card
