### ISSUE TITLE
It does not show the correct number of stars

### ISSUE THREAD

**Issue by fctaddia** [anuraghazra/github-readme-stats#674] opened 2020-12-01 23:49 UTC
**Describe the bug**
It does not show the correct number of stars

**Expected behavior**
It should show 19 stars however it shows 15 stars

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
The first image is the correct number
![star2](https://user-images.githubusercontent.com/44770870/100810069-e5e88a80-3437-11eb-8400-4938a4a45460.png)
Second image
![star1](https://user-images.githubusercontent.com/44770870/100810087-eda82f00-3437-11eb-95ef-607e7ae4c631.png)

**Additional context**
This my link: https://github-readme-stats.vercel.app/api?username=fctaddia&show_icons=true&theme=default&hide=prs&include_all_commits=true

**Comment by anuraghazra** [comment] 2020-12-02 06:46
duplicate of #39 #170 #338

**Closed by anuraghazra** 2020-12-02 06:46 UTC

**Comment by yendi158** [comment] 2020-12-02 07:44
🤔
