### ISSUE TITLE
Can not exclude repo 

### ISSUE THREAD

**Issue by Cristishor201** [anuraghazra/github-readme-stats#1798] opened 2022-06-01 15:15 UTC
**Describe the bug**
`exclude_repo=` doesn't works

**Expected behaviour**
It seems that at least on **fork**ed repos, like this one :D it doesn't work, on **The most used languages**.
Expected to exclude this repo, to display the other repos work.

**Additional context**
`include_forks=false` doesn't help either.

**Comment by antoninhrlt** [comment] 2022-06-08 11:58
I've the same problem :/

**Comment by ilovelinux** [comment] 2022-06-12 12:56
Forked repos aren´t included by default on "Most used languages" as explained in https://github.com/anuraghazra/github-readme-stats/discussions/1255

**Comment by antoninhrlt** [comment] 2022-06-12 12:58
ok but, `&exclude_repo` does not work with my repository (that is not forked)

**Comment by rickstaa** [comment] 2022-06-12 13:32
@antoninhrlt Thanks for your question. I checked your card and the following Syntax seems to work.

**Without exclusions**

```markdown
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt)](https://github.com/anuraghazra/github-readme-stats)
```

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt)](https://github.com/anuraghazra/github-readme-stats)

**With exclusions**

```markdown
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&exclude_repo=antoninhrlt.com)](https://github.com/anuraghazra/github-readme-stats)
```

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&exclude_repo=antoninhrlt.com)](https://github.com/anuraghazra/github-readme-stats)

**Syntax used on your profile without exclusions**

```markdown
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&layout=compact&bg_color=0d1117&hide_title=true&text_color=ffffff&hide_border=true&langs_count=6)](https://github.com/anuraghazra/github-readme-stats)
```

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&layout=compact&bg_color=0d1117&hide_title=true&text_color=ffffff&hide_border=true&langs_count=6)](https://github.com/anuraghazra/github-readme-stats)

**Syntax used on your profile with exclusions**

```markdown
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&layout=compact&bg_color=0d1117&hide_title=true&text_color=ffffff&hide_border=true&langs_count=6&hide=php,css,blade&exclude_repo=antoninhrlt.com)](https://github.com/anuraghazra/github-readme-stats)
```

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&layout=compact&bg_color=0d1117&hide_title=true&text_color=ffffff&hide_border=true&langs_count=6&hide=php,css,blade&exclude_repo=antoninhrlt.com)](https://github.com/anuraghazra/github-readme-stats)

I hope that helps.

**Comment by rickstaa** [comment] 2022-06-12 13:34
I am closing this since I could not find any problems with the current behaviour. Please give a reproducible example below if you still think something is going wrong.

**Comment by antoninhrlt** [comment] 2022-06-12 13:45
> @antoninhrlt Thanks for your question. I checked your card and the following Syntax seems to work.
> 
> **Without exclusions**
> 
> ```markdown
> [![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt)](https://github.com/anuraghazra/github-readme-stats)
> ```
> 
> [![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt)](https://github.com/anuraghazra/github-readme-stats)
> 
> **With exclusions**
> 
> ```markdown
> [![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&exclude_repo=antoninhrlt.com)](https://github.com/anuraghazra/github-readme-stats)
> ```
> 
> [![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&exclude_repo=antoninhrlt.com)](https://github.com/anuraghazra/github-readme-stats)
> 
> **Syntax used on your profile without exclusions**
> 
> ```markdown
> [![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&layout=compact&bg_color=0d1117&hide_title=true&text_color=ffffff&hide_border=true&langs_count=6)](https://github.com/anuraghazra/github-readme-stats)
> ```
> 
> [![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&layout=compact&bg_color=0d1117&hide_title=true&text_color=ffffff&hide_border=true&langs_count=6)](https://github.com/anuraghazra/github-readme-stats)
> 
> **Syntax used on your profile with exclusions**
> 
> ```markdown
> [![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&layout=compact&bg_color=0d1117&hide_title=true&text_color=ffffff&hide_border=true&langs_count=6&hide=php,css,blade&exclude_repo=antoninhrlt.com)](https://github.com/anuraghazra/github-readme-stats)
> ```
> 
> [![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=antoninhrlt&layout=compact&bg_color=0d1117&hide_title=true&text_color=ffffff&hide_border=true&langs_count=6&hide=php,css,blade&exclude_repo=antoninhrlt.com)](https://github.com/anuraghazra/github-readme-stats)
> 
> I hope that helps.
> 

Thank you, the problem was probably from me, maybe I've badly refreshed the page or something like that.
I'm sorry for the disturbance

**Comment by rickstaa** [comment] 2022-06-12 14:31
@antoninhrlt No problem, happy to help!

**Comment by Cristishor201** [comment] 2022-06-12 19:13
> Forked repos aren´t included by default on "Most used languages" as explained in #1255

Ok. But then why I can not exclude this repo ?

**Closed** 2022-06-12 19:18 UTC
Labels: bug
