### ISSUE TITLE
`Total Commits` has wrong value

### ISSUE THREAD

**Issue by anc95** [anuraghazra/github-readme-stats#1536] opened 2022-01-16 07:51 UTC
**Describe the bug**
I found `Total Commit` is wrong for my account

If I visit https://github-readme-stats.vercel.app/api?username=anc95, I got
![image](https://user-images.githubusercontent.com/13167934/149651803-62b6d00a-5a29-4edf-9e3e-9f223c98a25b.png)
`Total Commits` for 2022 is 136

https://github-readme-stats.vercel.app/api?username=anc95&include_all_commits=true
![image](https://user-images.githubusercontent.com/13167934/149651773-203f4558-7c57-4711-8b9f-38d9eaed260c.png)
`Total Commits` for all history is 123

**Expected behavior**
`Total Commits` should display right value

**Comment by MagicLike** [comment] 2022-01-16 09:02
Duplicate of #1234

**Closed** 2022-03-09 08:49 UTC
