### ISSUE TITLE
Hey, how can I hide jupyter notebook for Top Languages Card?

### ISSUE THREAD

**Issue by davidleitw** [anuraghazra/github-readme-stats#352] opened 2020-08-09 17:06 UTC
I try to hide jupyter notebook for top languages card?
How should i do?
I try 

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=davidleitw&hide=Jupyter Notebook)](https://github.com/anuraghazra/github-readme-stats)

and 

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=davidleitw&hide=JupyterNotebook)](https://github.com/anuraghazra/github-readme-stats)

it doesn't work .
Thanks for your help.

**Comment by anuraghazra** [comment] 2020-08-09 17:08
jupyter%20notebook

please read the docs https://github.com/anuraghazra/github-readme-stats/#language-card-exclusive-options

**Comment by anuraghazra** [comment] 2020-08-09 17:09
Duplicate of #201 #320

**Closed by anuraghazra** 2020-08-09 17:08 UTC

**Comment by davidleitw** [comment] 2020-08-09 17:16
Thx, thank for your help!

**Comment by ichisadashioko** [comment] 2020-09-07 11:39
We need to add some documentation about the `ID` of the languages.

**Comment by sajid-munawar** [comment] 2022-06-17 17:49
Thanks.

**Comment by sasha1107** [comment] 2022-11-02 04:19
Thanks a lot!

**Comment by QI-XIANG** [comment] 2024-04-21 01:56
Thanks for help.
