### ISSUE TITLE
The statistic is obsolete and not updating

### ISSUE THREAD

**Issue by dgroup** [anuraghazra/github-readme-stats#1718] opened 2022-04-24 12:34 UTC
**Describe the bug**
The chart with statistics for the past week is obsolete, as you may see on the screen below I didn't use Ruby or Python this week.

**Expected behavior**
Here are the stats from Wakatime for past week
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/1651114/164976536-dddd3158-3e0a-4ca0-b835-29bf69798b19.png">

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
<img alt="dgroup's Off-work Stats" src="https://github-readme-stats.vercel.app/api/wakatime/?username=dgroup&layout=compact&hide_border=true&custom_title=Off-work+activities+for+past+week" />

**Additional context**
Btw, the link https://github-readme-stats.vercel.app/api/wakatime/?username=dgroup is it an accumulated statistic or a weekly statistic? I thought that it's weekly as per https://github.com/anuraghazra/github-readme-stats#wakatime-week-stats docs.

**Comment by rickstaa** [comment] 2023-05-06 10:06
Closing this as I'm unable to reproduce your error. You are welcome to provide additional information if you still have the error. Please keep in mind that we use a 4 hour caching for the cards.

**normal (all time)**

[![willianrod's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=dgroup)](https://github.com/anuraghazra/github-readme-stats)

```md
[![willianrod's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=dgroup)](https://github.com/anuraghazra/github-readme-stats)
```

**Closed** 2023-05-06 10:08 UTC
Labels: bug
