### ISSUE TITLE
Total Commits has dropped to zero

### ISSUE THREAD

**Issue by andry81** [anuraghazra/github-readme-stats#1571] opened 2022-02-08 15:31 UTC
**Describe the bug**
Total Commits counter is dropped to zero.

**Expected behavior**
Correct behaviour.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
If try to directly request the link, then seems it is ok:

https://github-readme-stats.vercel.app/api?username=andry81&theme=dark&count_private=true&show_icons=true&include_all_commits=true

But as a part of a user profile - is not.

**Additional context**
Some repositories were been moved into an organization's account. Is that might be an issue?

**Comment by Dynesshely** [comment] 2022-02-21 13:03
I met this problem too

**Comment by Dynesshely** [comment] 2022-02-21 13:04
When I access this link directly in my browser it works well.
But when it was put in my GitHub README.md it dropped into zero.
Why does it looks like that ?

**Comment by Dynesshely** [comment] 2022-02-21 13:06
But when I delete the argument `include_all_commits=true`
It works well and precisely gave the commits I did in past year.

**Comment by anuraghazra** [comment] 2022-02-22 14:14
I think this was caused by stale cache, please confirm once and if it's resolve we can close this.

**Comment by andry81** [comment] 2022-02-22 14:17
How frequently cache does update?

**Comment by anuraghazra** [comment] 2022-02-22 14:26
From docs:
Repo cards have a default cache of 4 hours (14400 seconds) if the fork count & star count is less than 1k, otherwise, it's 2 hours (7200 seconds). Also, note that the cache is clamped to a minimum of 2 hours and a maximum of 24 hours.

**Comment by andry81** [comment] 2022-02-22 14:43
> From docs: Repo cards have a default cache of 4 hours (14400 seconds) if the fork count & star count is less than 1k, otherwise, it's 2 hours (7200 seconds). Also, note that the cache is clamped to a minimum of 2 hours and a maximum of 24 hours.

Ok. If next time I see that, then I will check.

**Comment by andry81** [comment] 2022-07-21 16:17
I've noticed it has dropped again:
https://github.com/andry81-cache/andry81--gh-content-cache/commit/cc7e495f834f38d844431f4b4300363c1f1ff3b2#diff-3f55dc8dbbd2e6df75c40b737602162956166212f228731699689ce77f693e07

**Comment by rickstaa** [comment] 2022-07-21 17:54
I suspect 

> I think this was caused by stale cache, please confirm once and if it's resolve we can close this.

Hey @andry81, thanks for letting us know. I checked the problem and came to the same conclusion as @anuraghazra above. It looks like the Github rest API temporary flaked, and that the result was saved in the cache. 

I checked the results of your account using the [Github rest API](https://docs.github.com/en/rest), which the GRS uses to fetch the total commits, and it looks like it works. It gives me around 3k public commits for your account.

https://github.com/anuraghazra/github-readme-stats/blob/3430a2944f1f86d5db8c6ab345c524d9d3058bf2/src/fetchers/stats-fetcher.js#L75-L85

```text
https://api.github.com/search/commits?q=author:andry81
```

```markdown
[![Andry81's GitHub stats](https://github-readme-stats.vercel.app/api?username=Andry81&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)
```

[![Andry81's GitHub stats](https://github-readme-stats.vercel.app/api?username=Andry81&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)

I will close this issue again since I don't think the bug you are experiencing is due to something in the GRS code but caused by the upstream. I tried to investigate your readme page to see which command you are using to create the card, but I could not find it due to your action-based caching mechanism. If you want to investigate why this happens, I think your best chance is to call the Github Rest API when you first notice the issue occurs to see if it gives any errors.

**Comment by rickstaa** [comment] 2022-07-21 18:02
@andry81 Interesting caching behaviour, I have never seen it used. I think you do it like that since you are displaying a lot of rendered `svgs`, and the page load time would be too high otherwise?e

**Comment by andry81** [comment] 2022-07-21 23:48
> @andry81 Interesting caching behaviour, I have never seen it used. I think you do it like that since you are displaying a lot of rendered `svgs`, and the page load time would be too high otherwise?e

These svg's just periodically downloaded through the GitHub Action using curl and committed into a repository. I used this approach, because direct links in the markdown file time to time goes offline and does cached as offline version instead of an old version.

**Closed** 2022-07-22 06:50 UTC
Labels: bug, question, upstream
