### ISSUE TITLE
cannot access total commits in Read.me

### ISSUE THREAD

**Issue by cyberdog1776** [anuraghazra/github-readme-stats#3268] opened 2023-09-21 14:58 UTC
### Describe the bug

error message directing me to this site to report a bug.  Changed repo name last week and now there is an error retreving commits.

### Expected behavior

Should have a graph listing total commits and timeline.

**Comment by qwerty541** [comment] 2023-09-21 17:20
@cyberdog1776 Thanks for the report! You can see this when upstream GitHub API respond with error due to some reason during fetching stats card data. Should be resolve automatically after some time. Currently stats card in your profile works well. After merging https://github.com/anuraghazra/github-readme-stats/pull/3255 error message will be improved to be more clear.

Recently we merged https://github.com/anuraghazra/github-readme-stats/pull/3238 which improved confusing behavior of showing 0 commits when upstream API feails, currently we show an error instead, i'm curious what do you think about this change.

Closing as duplicate of https://github.com/anuraghazra/github-readme-stats/issues/3243

**Closed by qwerty541** 2023-09-21 17:20 UTC
Labels: bug

**Comment by cyberdog1776** [comment] 2023-09-21 18:22
Hello:
Thank you for resolving this issue. <3

Sincerely,

Nichole Tullis
God's Army Taxi, LLC
***@***.*** ***@***.***>
762-847-5089

**Comment by rickstaa** [comment] 2023-09-21 18:34
We merged https://github.com/anuraghazra/github-readme-stats/pull/3255.
