### ISSUE TITLE
[error] github stats error

### ISSUE THREAD

**Issue by Jacobkyalo** [anuraghazra/github-readme-stats#2133] opened 2022-10-05 16:39 UTC
please am getting an error in my GitHub stats card,  need some help
![error](https://user-images.githubusercontent.com/94710630/194114686-803f4392-729f-4c71-81d6-70c00aca213b.png)

**Comment by duberlyguarnizofuentesrivera** [comment] 2022-10-05 17:10
This is noted in issue #1772 (first comment). The only thing you can do is wait.

**Comment by rickstaa** [comment] 2022-10-05 17:17
Duplicate of #2130.

**Closed by rickstaa** 2022-10-05 17:17 UTC
