### ISSUE TITLE
MASS ERROR

### ISSUE THREAD

**Issue by MitkoVtori** [anuraghazra/github-readme-stats#2381] opened 2023-01-12 06:34 UTC
### Describe the bug

It's not just me, but everyone. There's some error saying "Cannot read properties of undefined (reading 'user')"
Also described in (#2379, #2380).

### Expected behaviour

Show stats cards.

**Comment by i-am-ijaz** [comment] 2023-01-12 07:38
> ### Describe the bug
> It's not just me, but everyone. There's some error saying "Cannot read properties of undefined (reading 'user')" Also described in (#2379, #2380).
> 
> ### Expected behaviour
> Show stats cards.
> 
> ### Screenshots / Live demo link
> _No response_
> 
> ### Additional context
> _No response_

**==>**  Facing same behavior 
Something went wrong! file an issue at https://tiny.one/readme-stats

Cannot read properties of undefined (reading 'user')

**Comment by MitkoVtori** [comment] 2023-01-12 07:39
> > ### Describe the bug
> > It's not just me, but everyone. There's some error saying "Cannot read properties of undefined (reading 'user')" Also described in (#2379, #2380).
> > ### Expected behaviour
> > Show stats cards.
> > ### Screenshots / Live demo link
> > _No response_
> > ### Additional context
> > _No response_
> 
> **==>** Facing same behavior Something went wrong! file an issue at https://tiny.one/readme-stats
> 
> Cannot read properties of undefined (reading 'user')

The problem is their's, we cannot do anything, we can only wait for someone to resolve this.

**Comment by D3vil0p3r** [comment] 2023-01-12 10:48
@anuraghazra

**Comment by MitkoVtori** [comment] 2023-01-12 12:28
### Here, this is one way to fix the error

![Screenshot 2023-01-12 142306](https://user-images.githubusercontent.com/112943652/212065618-73ed66a6-bfeb-46b9-b6c0-77b79c621531.png)

**Comment by D3vil0p3r** [comment] 2023-01-12 13:02
@MitkoVtori could you link the message please?

**Comment by sovtec** [comment] 2023-01-12 13:57
> ### Here, this is one way to fix the error
> ![Screenshot 2023-01-12 142306](https://user-images.githubusercontent.com/112943652/212065618-73ed66a6-bfeb-46b9-b6c0-77b79c621531.png)

Can you link this message?

**Comment by sovtec** [comment] 2023-01-12 14:13
> @MitkoVtori could you link the message please?

https://github.com/anuraghazra/github-readme-stats/issues/2380

**Comment by rickstaa** [comment] 2023-01-12 21:41
Duplicate of #2380.

**Closed by rickstaa** 2023-01-12 21:42 UTC
Labels: bug

**Comment by MitkoVtori** [comment] 2023-01-13 08:16
> Duplicate of #2380.

Yeah maybe, the idea was to tell the people, the error is for everyone, that's why I even mentioned #2380 and #2379
