### ISSUE TITLE
Something went wrong!  Wakatime user not found 

### ISSUE THREAD

**Issue by willin** [anuraghazra/github-readme-stats#2754] opened 2023-05-27 18:05 UTC
### Describe the bug

Something went wrong! file an issue at https://tiny.one/readme-stats

Wakatime user not found, make sure you have a wakatime profile

### Screenshots / Live demo link

<img width="719" alt="image" src="https://github.com/anuraghazra/github-readme-stats/assets/1890238/286404de-aefb-40fe-9e9f-b58ed94ab783">

https://github-readme-stats.vercel.app/api/wakatime?username=willin&layout=compact&theme=gruvbox&hide_border=true

### Additional context

Public profile link: <https://wakatime.com/@willin>

**Comment by jrocha-dev** [comment] 2023-05-27 18:56
Same here.

**Comment by qwerty541** [comment] 2023-05-27 23:05
> Same here.

Hey, @jrocha-dev! Your wakatime account data is public, but only last week. You should add &range=last_7_days to fix your problem. See #2698.

`https://github-readme-stats.vercel.app/api/wakatime?username=candidoroch&langs_count=5&theme=dark&range=last_7_days`

<img src="https://github-readme-stats.vercel.app/api/wakatime?username=candidoroch&langs_count=5&theme=dark&range=last_7_days" />

Or you can wait until #2707 will be merge and your problem should be fixed automatically.

Hey, @willin! I have not found wakatime card in your profile to offer a specific solution exactly for you as for @jrocha-dev. You can wait until pull request with fix will be merged or you can manually add one of this parameter to card URL: `&range=all_time`, `&range=last_30_days` and `&range=last_7_days`.

**Comment by jrocha-dev** [comment] 2023-05-28 00:03
@querty541, thank you very much!

**Comment by willin** [comment] 2023-05-28 04:55
https://github-readme-stats.vercel.app/api/wakatime?username=willin&layout=compact&theme=gruvbox&hide_border=true&range=last_7_days

<img width="1121" alt="image" src="https://github.com/anuraghazra/github-readme-stats/assets/1890238/e1cc7446-b01b-4380-9ec3-4c903d448fbb">

**Comment by qwerty541** [comment] 2023-05-28 06:00
> https://github-readme-stats.vercel.app/api/wakatime?username=willin&layout=compact&theme=gruvbox&hide_border=true&range=last_7_days
> 
> <img alt="image" width="1121" src="https://user-images.githubusercontent.com/1890238/241491961-e1cc7446-b01b-4380-9ec3-4c903d448fbb.png">

Your card works with `&range=last_year` parameter.

<img src="https://github-readme-stats.vercel.app/api/wakatime?username=willin&layout=compact&theme=gruvbox&hide_border=true&range=last_year" />

Check wakatime API docs for all available range values: https://wakatime.com/developers#stats:~:text=ISO%208601%20format%3E%2C%0A%20%20%20%20%7D%2C%20%E2%80%A6%0A%20%20%5D%2C%0A%7D-,Stats,-GET

**Comment by qwerty541** [comment] 2023-05-28 06:05
I don't use wakatime myself but i think that solution for each person depends from his wakatime profile settings. It is users responsibility to make sure that his profile settings match card range parameter.

**Comment by rickstaa** [comment] 2023-05-28 11:09
Duplicate of #2698. Will be fixed if #2707 is merged. @Zo-Bro-23 can you maybe approve this pull request so that we can merge it?

**Closed by rickstaa** 2023-05-28 11:09 UTC
Labels: bug
