### ISSUE TITLE
The Streak Card is broken for my self deployment, please help

### ISSUE THREAD

**Issue by sc0rp10n-py** [anuraghazra/github-readme-stats#1699] opened 2022-04-13 03:52 UTC
The streak card works fine if I use the one through your deployment link.
[Here](http://github-readme-streak-stats.herokuapp.com?user=sc0rp10n-py&theme=radical&hide_border=true&date_format=M%20j%5B%2C%20Y%5D)

but from my deployed link, it gets broken
[here](https://github-readme-stats-pi-brown.vercel.app?user=sc0rp10n-py&theme=radical&hide_border=true&date_format=M%20j%5B%2C%20Y%5D)

**Comment by rickstaa** [comment] 2022-04-13 18:36
Hey @sc0rp10n-py. Thanks a lot for your issue. 

I think the problem is that you are trying to use a card from the [DenverCoder1/github-readme-streak-stats](https://github.com/DenverCoder1/github-readme-streak-stats) repository with a Vercel instance for the[ github-readme-stats](https://github.com/anuraghazra/github-readme-stats/) repository. Although these two repositories are very much alike, they contain different cards. 

I think you should open an issue on https://github.com/DenverCoder1/github-readme-streak-stats/issues. I will close this issue for now. Feel free to leave a comment if you have any other problems.

**Closed by rickstaa** 2022-04-13 18:36 UTC
Labels: question
