### ISSUE TITLE
Not able to fetch data

### ISSUE THREAD

**Issue by aleenaanil13** [anuraghazra/github-readme-stats#3856] opened 2024-07-18 09:09 UTC
### Describe the bug

Stats and top language cards are not being displayed. The issue could be because of the current deployment problem.

**Comment by aryankeluskar** [comment] 2024-07-18 09:26
Yep, I believe his server is rate-limited. I recommend checking out this video https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s for fixing it!

**Comment by qwerty541** [comment] 2024-07-18 18:57
Hey guys! All this time the public instance was deployed on Vercel on the account with enterprise plan provided for free for Anurag. I just received a message from Anurag that Vercel stopped their OSS sponsorship and account was returned to basic plan, so when the limits was exceeded the deployment was paused. As I understand, at the moment Anurag returned it to work with own money, but in the near future we have to migrate on another cloud provider because Vercel is very expensive. Therefore, deployment on the [github-readme-stats.vercel.app](https://github-readme-stats.vercel.app/) will be shutdown soon. For now I recommend you all to [deploy your own Vercel instances](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel) in order to avoid impact of future shutdown of public instance.

**Comment by qwerty541** [comment] 2024-07-18 18:58
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/3851

**Closed by qwerty541** 2024-07-18 18:58 UTC
Labels: bug
