### ISSUE TITLE
Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by alanchrissantony** [anuraghazra/github-readme-stats#2399] opened 2023-01-13 07:24 UTC
<h1>Bug</h1>
<img align="center" src="https://user-images.githubusercontent.com/83913615/212261447-44e9b5de-118f-4987-8575-af17ee8b9eaa.png">

**Comment by KyeOnDiscord** [comment] 2023-01-13 07:27
same here
<img width="565" alt="Screenshot 2023-01-13 at 6 27 11 pm" src="https://user-images.githubusercontent.com/36981621/212262083-a2d80687-5ea2-4090-bd5d-ecab55126891.png">
must be something on their end

**Comment by Chris1320** [comment] 2023-01-13 07:42
Duplicate of #2380.

**Comment by anuraghazra** [comment] 2023-01-13 07:50
fixed in #2400

**Closed by anuraghazra** 2023-01-13 07:50 UTC
