### ISSUE TITLE
Total commit count with include_all_commits=true is no longer correct

### ISSUE THREAD

**Issue by MacroPower** [anuraghazra/github-readme-stats#518] opened 2020-09-30 14:36 UTC
**Describe the bug**
My total commits (include_all_commits=true) is a much smaller number than my 2020 commits (include_all_commits=false).

**Expected behavior**
`Total commits (2020)` should be less than or equal to `Total commits`.

**Screenshots / Live demo link**
include_all_commits=true:
https://github-readme-stats.vercel.app/api?username=macropower&include_all_commits=true
![image](https://user-images.githubusercontent.com/5648814/94699723-a226b700-0308-11eb-8aa8-a1c8c09da84c.png)

include_all_commits=false:
https://github-readme-stats.vercel.app/api?username=macropower&include_all_commits=false
![image](https://user-images.githubusercontent.com/5648814/94699759-ae127900-0308-11eb-8d70-f00034bd6e38.png)

**Additional context**
This was working fine until about a week ago, with `include_all_commits=true` resulting in total commits over 1k.

**Comment by IliasMariosG** [comment] 2020-10-01 09:19
**Issue**
My total commits (include_all_commits=true) is a smaller number than my commits as they were shown a few weeks ago.
I do not have a screenshot to provide evidence, so I will just say that I have a strong feeling that until a few weeks ago, the total commits were significantly higher. I remember this because of the comparison I could make between the commits presented in the badge and the contributions shown by GitHub.
Right now, total commits are 219 ( ![Screenshot 2020-10-01 at 12 12 09 PM](https://user-images.githubusercontent.com/57366310/94790769-6c083680-03df-11eb-925c-2d5740f56a95.png)) and contributions on GitHub are 273 (
![Screenshot 2020-10-01 at 12 14 51 PM](https://user-images.githubusercontent.com/57366310/94791010-c30e0b80-03df-11eb-9833-487274b4503d.png)). Right now, the difference between those two is small, but it used to be significantly larger (around 400 commits shown in the badge).

Thank you and I'm sorry that it's not possible to provide evidence, as I have not captured a screenshot.

**Comment by Techno-Disaster** [comment] 2020-11-16 05:01
Yep, I can confirm this, even my number of commits has decreased. @anuraghazra any idea what's up with this?

**Comment by MacroPower** [comment] 2020-12-16 14:27
This is still an issue.

**Comment by MacroPower** [comment] 2021-01-16 00:00
This is still an issue.

**Comment by mihai-db** [comment] 2021-02-08 16:51
Yes, same here.

**Comment by mihai-db** [comment] 2021-03-11 17:52
This is still an issue.

**Comment by harryghgim** [comment] 2021-03-24 16:15
Same here.

With `include_all_commits=true`

[![Github stats](https://github-readme-stats-harryghgim.vercel.app/api?username=harryghgim&show_icons=true&hide=stars&theme=dark&include_all_commits=true)](https://github.com/nuraghazra/github-readme-stats)

w/o it.

[![Github stats](https://github-readme-stats-harryghgim.vercel.app/api?username=harryghgim&show_icons=true&hide=stars&theme=dark)](https://github.com/anuraghazra/github-readme-stats)

One more thing, I've never pushed as many commits as displayed this year so far. According to my github profile down below, my commits so far this year only 102. 
<img width="992" alt="Screen Shot 2021-03-25 at 1 05 25 AM" src="https://user-images.githubusercontent.com/35060447/112343154-309f5280-8d06-11eb-893a-e78d204a5c1a.png">

Suppose the card is somehow counting commits since one year ago from now. Still if that were the case, shouldn't the number of commits at least match either the number with `include_all_commits=true` or the number with this year only? 

<img width="780" alt="Screen Shot 2021-03-25 at 1 07 54 AM" src="https://user-images.githubusercontent.com/35060447/112343500-8a078180-8d06-11eb-84c3-b9db9b20aad7.png">

It feels I'm lying about my commits, and I hate being a liar 😅.

Can someone tell me how commit counts work? Am I missing something?

**Comment by simonSlamka** [comment] 2021-07-20 21:58
Still an issue, ffs.

**Comment by sabertazimi** [comment] 2021-07-22 03:36
This is still an issue.

**Comment by simonSlamka** [comment] 2021-07-22 14:53
I stopped using this repo for my stats because of this. Sad that the maintainer doesn't seem to care anymore. It surely seems like it.

**Comment by sabertazimi** [comment] 2021-07-22 15:00
> I stopped using this repo for my stats because of this. Sad that the maintainer doesn't seem to care anymore. It surely seems like it.

So do you have any alternatives?

**Comment by simonSlamka** [comment] 2021-07-22 15:06
Yes. You can check out [my profile](https://github.com/simonSlamka); I'm using lots of various stats. It's all done through GH Actions. If you're interested in any particular one, let me know, and I'll give you a link to the original repo, or you can look it up yourself.

**Comment by Elius94** [comment] 2022-02-04 17:00
I think it still a issue!

**Comment by rickstaa** [comment] 2022-09-24 14:13
Duplicate of #1515. Lets track this issue there.

**Closed by rickstaa** 2022-09-24 14:13 UTC
Labels: bug, stats-card

**Comment by silasoli** [comment] 2024-05-18 13:01
> I stopped using this repo for my stats because of this. Sad that the maintainer doesn't seem to care anymore. It surely seems like it.

I was observing some bugs and researching I saw that several features have unresolved bugs, I'll try to use something similar to yours, I'll research
