### ISSUE TITLE
Personal Instance with Repo Access PAT Cannot Read Yearly Commit Correctly

### ISSUE THREAD

**Issue by ForsakenRei** [anuraghazra/github-readme-stats#2793] opened 2023-06-08 17:00 UTC
### Describe the bug

Update 6/10: Current situation explained in https://github.com/anuraghazra/github-readme-stats/issues/2793#issuecomment-1585832224

----

Sorry I know this have been asking multiple times recently, I have been using my own vercel instance for months and everything worked well until I synced my fork yesterday and remove `count_private` was inplemented. Yesterday it shows 300+ commits but today it's 200+. 

Counted from my contribution activity it should be 300ish in 2023, if it is last year from June 2022 to June 2023 it will be 400ish.

Top language seems working properly since the percentage didn't change much from yesterday but status card only shows public commits now? If I add `include_all_commits=true` the commit number(1.3K for all years) seems contain all my commits regardless of private or public repo.

I recreated a vercel instance based on [38c8a7a](https://github.com/ForsakenRei/github-readme-stats/commit/38c8a7a1e4fea71409f7c4834f7c7b1b8cd695ca) with a new PAT granted repo access, but the behavior is still the same.

Am I missing any argument?

### Expected behavior

Status card includes commits to private repo as well.

### Screenshots / Live demo link
![include_all_commits](https://github-readme-stats-murex-five-78.vercel.app/api?username=forsakenrei&show_icons=true&theme=tokyonight&include_all_commits=true)

![normal](https://github-readme-stats-murex-five-78.vercel.app/api?username=forsakenrei&show_icons=true&theme=tokyonight)

https://github.com/ForsakenRei/ForsakenRei

From official instance
![include_all_commits](https://github-readme-stats.vercel.app/api?username=forsakenrei&show_icons=true&theme=tokyonight&include_all_commits=true)

![normal](https://github-readme-stats.vercel.app/api?username=forsakenrei&show_icons=true&theme=tokyonight)

**Comment by salesp07** [comment] 2023-06-09 00:12
Same problem here. They should revert the commit where `count_private` was removed until this is sorted out.

**Comment by rickstaa** [comment] 2023-06-09 07:10
@ForsakenRei I just checked your stats, and for the `include_all_commits=false` case it looks like you did something wrong while deploying your [own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own). Please ensure that the PAT has the rights to read data from your private repositories. You can check this out yourself using the https://docs.github.com/en/graphql/overview/explorer:

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    name
    login
    contributionsCollection {
      totalCommitContributions
      restrictedContributionsCount
    }
  }
}
```

```graphql
{"login": "forsakenRei"}
```

![image](https://github.com/anuraghazra/github-readme-stats/assets/17570430/a9deae75-8c4c-4837-ae2b-be6ca9e879cf)

I don't have access to your private repositories, so I will see the public ones. You will likely see a higher number if you have private commits. 

For the `include_all_commits=true` case, I just noticed that we use the Public REST API, which does not have access to your private commits:

https://github.com/anuraghazra/github-readme-stats/blob/7a302f6f671ef1b8b49d8139fb7fdb0717b3bdf4/src/fetchers/stats-fetcher.js#L146-L156

This indeed is a bug, and it can be fixed by merging https://github.com/anuraghazra/github-readme-stats/pull/1691. This pull request, however, cannot be merged on the Public instance since it will lead to the [GraphQL limits](https://docs.github.com/en/graphql/overview/resource-limitations) being triggered rapidly. It will likely be deployed under an ENV variable when the GitHub action is released (see https://github.com/anuraghazra/github-readme-stats/issues/2179).

There however is a way to solve it now on the public instance. We can change the code above so that the PAT that is set is used (see https://docs.github.com/en/rest/overview/authenticating-to-the-rest-api?apiVersion=2022-11-28) 👍🏻. It would be great if somebody can create a pull request for this 🚀.

**Comment by ForsakenRei** [comment] 2023-06-09 13:54
@rickstaa thanks for all the explanations.

Here's the output of GraphQL following your example.
```
{
  "data": {
    "user": {
      "name": "しぐれ",
      "login": "ForsakenRei",
      "contributionsCollection": {
        "totalCommitContributions": 429,
        "restrictedContributionsCount": 0
      }
    }
  }
}
```
but I signed in with my account...so I guess it not really testing my PAT then I tried this
```
curl -sS -f -I -H "Authorization: {myToken}" https://api.github.com
```
but didn't see anything about repo. I check another one PAT with full access to my account which basically have the same output so I think I'm not doing it with the right API end point?

and my PAT has repo access only
![2~B}1 NW5Q4_O}}9PS0~V91](https://github.com/anuraghazra/github-readme-stats/assets/23041178/2ef92085-fa66-4414-9386-53c7da17a0d9)
was added to my vercel instance
![image](https://github.com/anuraghazra/github-readme-stats/assets/23041178/aee5ed51-5987-487f-b680-57189762473c)

scratching my head lol

**Comment by ForsakenRei** [comment] 2023-06-09 15:43
Here's a comparison of the top language card
Official Instance
![image](https://github-readme-stats.vercel.app/api/top-langs/?username=forsakenrei&layout=compact&theme=tokyonight&exclude_repo=&hide=Cmake,C%2B%2B)
Personal Instance
![image](https://github-readme-stats-swart-rho.vercel.app/api/top-langs/?username=forsakenrei&layout=compact&theme=tokyonight&exclude_repo=&hide=Cmake,C%2B%2B)

So I my PAT is working since it reads all my personal Python code, but just not working properly for the commit?

**Comment by rickstaa** [comment] 2023-06-09 19:20
> curl -sS -f -I -H "Authorization: {myToken}" https://api.github.com

Sorry, my last response was incorrect. It seems that we do use the PAT when fetching data from the REST API:

https://github.com/anuraghazra/github-readme-stats/blob/44c268e05ad6b9eb572810a2d71f043900d4cd2e/src/common/retryer.js#L24-L28

You should therefore receive the same number of commits as would you would receive when curling the REST API directly:

```bash
export TOKEN=<YOUR_PAT>
curl -sS -f -I -H "Authorization: $TOKEN" https://api.github.com/search/commits?q=author:ForsakenRei
```

**Comment by rickstaa** [comment] 2023-06-09 19:22
The following permissions should work:

![image](https://github.com/anuraghazra/github-readme-stats/assets/17570430/1bfbf59e-0116-440f-a0dc-af3b15678f00)

**Comment by rickstaa** [comment] 2023-06-09 19:24
Please note that the Rest API is buggy (see https://github.com/anuraghazra/github-readme-stats/issues/1515).

**Comment by ForsakenRei** [comment] 2023-06-09 20:23
> Please note that the Rest API is buggy (see #1515).

Yeah I think the numbers difference is probably caused by the buggy API. 1.2K is actually the right number.
```
curl -f -H "Authorization: $TOKEN" https://api.github.com/search/commits?q=author:ForsakenRei | grep to
tal
```
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  "total_count": 1186,
100  262k  100  262k    0     0   483k      0 --:--:-- --:--:-- --:--:--  484k
```

And my PAT does have repo permission, which is the only permission it has. Here's the API response after some doc reading.
```
curl -f -H "Authorization: $TOKEN" https://api.github.com/search/commits?q=author:ForsakenRei+author-date:\>2022-06-09 | rg total
```
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  "total_count": 412,
100  273k  100  273k    0     0   451k      0 --:--:-- --:--:-- --:--:--  452k
```
So it's actually 412 instead of 268 if I use my personal instance.

**Comment by rickstaa** [comment] 2023-06-09 21:09
> > Please note that the Rest API is buggy (see #1515).
> 
> Thanks, yeah I think the numbers difference is probably caused by the buggy API. 1.2K is actually the right number.
> 
> ```
> curl -f -H "Authorization: $TOKEN" https://api.github.com/search/commits?q=author:ForsakenRei | grep to
> tal
> ```
> 
> ```
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  "total_count": 1186,
> 100  262k  100  262k    0     0   483k      0 --:--:-- --:--:-- --:--:--  484k
> ```
> 
> And my PAT does have repo permission, which is the only permission it has. Here's the API response after some doc reading.
> 
> ```
> curl -f -H "Authorization: $TOKEN" https://api.github.com/search/commits?q=author:ForsakenRei+author-date:\>2022-06-09 | rg total
> ```
> 
> ```
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  "total_count": 412,
> 100  273k  100  273k    0     0   451k      0 --:--:-- --:--:-- --:--:--  452k
> ```
> 
> So it's actually 412 instead of 268 if I use my personal instance.

Ah, thanks for the in-depth analysis 👍🏻.

**Comment by ForsakenRei** [comment] 2023-06-09 21:18
I mean, the issue for private commit is not solved yet...or it just cannot be solved now?

If my PAT has the correct permission and I'm using my own instance(most used language also provided evidence) I should see 412 instead of 268 commits, but now I got exact the same number regardless I'm using the official instance or my own.

**Comment by rickstaa** [comment] 2023-06-09 21:43
> I mean, the issue for private commit is not solved yet...or it just cannot be solved now?
> 
> If my PAT has the correct permission and I'm using my own instance(most used language also provided evidence) I should see 412 instead of 268 commits, but now I got exact the same number regardless I'm using the official instance or my own.

The Rest API is buggy and is therefore only when `include_all_commits=true`. If you want to check whether the yearly commits are correct you should compare it with the GraphQL response when you are logged it. It's very hard for me to help you since I don't have access to your account and can not reproduce the issue on my accounts. I think the best thing to do is:

1. Fork the repository.
2. Ensure that it is up to date with the `main` branch of the upstream.
3. Build the GRS package locally (see https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#local-development).
4. Install vscode.
5. Put debug statements before the API calls:

https://github.com/anuraghazra/github-readme-stats/blob/44c268e05ad6b9eb572810a2d71f043900d4cd2e/src/fetchers/stats-fetcher.js#L146-L156

https://github.com/anuraghazra/github-readme-stats/blob/44c268e05ad6b9eb572810a2d71f043900d4cd2e/src/fetchers/stats-fetcher.js#L196

6. Check what the the APIs return in the code.

Let me know if you need any help.

**Comment by ForsakenRei** [comment] 2023-06-09 22:00
> > I mean, the issue for private commit is not solved yet...or it just cannot be solved now?
> > If my PAT has the correct permission and I'm using my own instance(most used language also provided evidence) I should see 412 instead of 268 commits, but now I got exact the same number regardless I'm using the official instance or my own.
> 
> The Rest API is buggy and is therefore only when `include_all_commits=true`. If you want to check whether the yearly commits are correct you should compare it with the GraphQL response when you are logged it. It's very hard for me to help you since I don't have access to your account and can not reproduce the issue on my accounts. I think the best thing to do is:
> 
> 1. Fork the repository.
> 2. Ensure that it is up to date with the `main` branch of the upstream.
> 3. Build the GRS package locally (see https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md#local-development).
> 4. Install vscode.
> 5. Put debug statements before the API calls:
> 
> https://github.com/anuraghazra/github-readme-stats/blob/44c268e05ad6b9eb572810a2d71f043900d4cd2e/src/fetchers/stats-fetcher.js#L146-L156
> 
> https://github.com/anuraghazra/github-readme-stats/blob/44c268e05ad6b9eb572810a2d71f043900d4cd2e/src/fetchers/stats-fetcher.js#L196
> 
> 6. Check what the the APIs return in the code.
> 
> Let me know if you need any help.

Thanks, I will probably try to build locally later today. Now I want to try deleting my fork and fork a new one then deploy a fresh instance, but Vercel is taking forever to import the repo, will update if it works on not once it goes through.

**Comment by rickstaa** [comment] 2023-06-10 09:40
Since this is a duplicate of https://github.com/anuraghazra/github-readme-stats/issues/1515, let's discuss it there further.

**Comment by ForsakenRei** [comment] 2023-06-10 16:31
Well originally my main issue it my perosnal instance with correct permission PAT cannot read private commit correctly. The total commit difference is more like a side discovery.

The fresh repo and vercel instance give me the same result. Therefore I forked it locally and run `vercel dev`. If I don't have PAT setup it will post a few messages ask for PAT and the localhost API retrun is also asking for a PAT. With the correct PAT set, I got the same result as the vercel instance I'm using. But apperantly my most use languages still includes all my private repos(compared to https://github.com/anuraghazra/github-readme-stats/issues/2793#issuecomment-1584791820)
![image](https://github.com/anuraghazra/github-readme-stats/assets/23041178/44800150-75e2-4220-a7ec-f7522a4065ce)
![image](https://github.com/anuraghazra/github-readme-stats/assets/23041178/8aa737e8-d321-4779-8211-737d2e867608)

I didn't know much about JS so I'm not sure if I'm doing it currotly but add `debugger;` before line 146 seems have no effect on my local vercel dev instance...?

And it seems the API is really buggy, I tried postman just want to see what I can get and compared to GRS.
```
GET https://api.github.com/search/commits?q=author:forsakenrei+author-date:>2022-12-31
```
Without auth token ```"total_count": 221``` and with token ```"total_count": 349```. On my profile page it is 357 for 2023 but includes all contributions not only commits. Commits numbers are different but relatively speaking, the current year commit number I got from my own GRS instance is more like the one without PAT, i.e. not counting my private repo.

I don't know where I can try to fix it though, tried hardcode my PAT to line 86 and 153 but nothing changed.

**Comment by rickstaa** [comment] 2023-06-10 16:59
> Well originally my main issue is my perosnal instance with correct permission PAT cannot read private commit correctly. The total commit difference is more like a side discovery.
> 
> The fresh repo and vercel instance give me the same result. Therefore I forked it locally and run `vercel dev`. If I don't have PAT setup it will post a few messages ask for PAT and the localhost API retrun is also asking for a PAT. With the correct PAT set, I got the same result as the vercel instance I'm using. But apperantly my most use languages still includes all my private repos(compared to [#2793 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/2793#issuecomment-1584791820)) ![image](https://user-images.githubusercontent.com/23041178/244880257-44800150-75e2-4220-a7ec-f7522a4065ce.png) ![image](https://user-images.githubusercontent.com/23041178/244880289-8aa737e8-d321-4779-8211-737d2e867608.png)
> 
> I didn't know much about JS so I'm not sure if I'm doing it currotly but add `debugger;` before line 146 seems have no effect on my local vercel dev instance...?
> 
> And it seems the API is really buggy, I tried postman just want to see what I can get and compared to GRS.
> 
> ```
> GET https://api.github.com/search/commits?q=author:forsakenrei+author-date:>2022-12-31
> ```
> 
> Without auth token `"total_count": 221` and with token `"total_count": 349`. On my profile page it is 357 for 2023 but includes all contributions not only commits. Commits numbers are different but relatively speaking, the current year commit number I got from my own GRS instance is more like the one without PAT, i.e. not counting my private repo.
> 
> I don't know where I can try to fix it, tried hardcode my PAT to line 86 and 153 of `stats-fetcher.js` but nothing changed. Clearly it's working since I didn't hardcode it in `top-language-fetcher.js` and when refersh top language card I got `PAT_* faild` and `Maximum retries exceeded`, but refresh the stats card just works, returns the same result though.

Yea, the REST API is sadly very buggy. You can simply add the PAT to Vercel, as it will inject it when you run `vercel dev`. 

About the debugging, you have to ensure [the JavaScript debugger](https://code.visualstudio.com/docs/languages/javascript) is working in an example script. If the debugger works, you can use the following `launch.json`:

```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}",
            "request": "attach",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "node"
        }
    ]
}
```

This config will allow you to attach to the local Vercel instance that is started with the `vercel dev` command. You can then add breakpoints, on which the debugger will stop if they are triggered. For me, the process I had to attach to showed up as:

![image](https://github.com/anuraghazra/github-readme-stats/assets/17570430/89ab4f83-f13e-4696-98e6-0b48367ef632)


Hope you can find your problem, as I cannot reproduce it on my private Vercel instance.

**Comment by ForsakenRei** [comment] 2023-06-10 17:43
Yes I used `.env` originally, just want to check if hardcode it has the same effect as the injection and the answser is yes I got the exact same result. I tried different PAT with full account access as well.

I will try JS debugger after I got back home, another thing I can try is a different github account(borrow one from my friend probably). Like you said, if we two are using the same configuration and same repo but yours has no issue at all, will there be something wrong with my Github account?

BTW could you re-open the issue as I'm not done with my investigation yet?

**Comment by rickstaa** [comment] 2023-06-10 18:03
> Yes I used `.env` originally, just want to check if hardcode it has the same effect as the injection and the answser is yes I got the exact same result. I tried different PAT with full account access as well.
> 
> I will try JS debugger after I got back home, another thing I can try is a different github account(borrow one from my friend probably). Like you said, if we two are using the same configuration and same repo but yours has no issue at all, will there be something wrong with my Github account?
> 
> BTW could you re-open the issue as I'm not done with my investigation yet?

Done! Maybe you can explain to me again what problem you are still experiencing. The reason that I say that I don't experience your problem is that my commits did not change compared to the last changes that could have affected the commits, and there is a clear difference between the private and public results (see below) 🤔. I, however, did not verify that the results I get for my account from GitHub are the correct ones because there is not much we can do if they are not correct 😅.

### Public results

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)

### Private results

[![Anurag's GitHub stats](https://github-readme-stats-rickstaa.vercel.app/api?username=rickstaa)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats-rickstaa.vercel.app/api?username=rickstaa)](https://github.com/anuraghazra/github-readme-stats)
```

```md
[![Anurag's GitHub stats](https://github-readme-stats-rickstaa.vercel.app/api?username=rickstaa&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats-rickstaa.vercel.app/api?username=rickstaa&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)

**Comment by ForsakenRei** [comment] 2023-06-10 22:11
Thanks, and let me go through the current issue again(after all those debugging I'm getting lost as well lol), bear with me since it will be a little lengthy.

For total commits(all or laster year), between official instance and private instace, there should be a clear difference since only private instance can read private repo commits. Unless the user has no private commits at all.

The example of your account shows a 8.9K vs 6.8K difference of total commits, which is the expected behavior since only your own instance can read all those private commits. And that's true for my case as well after I checked with postman, 1339 vs 1186 matched the result I have earlier 1.3K vs 1.2K. (https://github.com/anuraghazra/github-readme-stats/issues/2793#issue-1748328574)

Therefore I think we can conclude that `include_total_commits` works as expected though the API is still buggy.

But if we look at total commits in 2023, from your account they are both 1.5K, I don't know how many commits you have in private repos so if you barely have private commits in 2023 it's probably correct, otherwise something is wrong. And for my case, I got the exact same number which is not expected since I have about 100 commits in private repos in 2023. When I use postman to call the API
```
https://api.github.com/search/commits?q=author:forsakenrei+author-date:>2022-12-31
```
with PAT I got 350, without it's 221. And from GRS the number is 269 for 2023(I assume the date range is after 2022-12-31, correct me if I'm wrong since I didn't read all the code). So there seems to be something wrong, with the API or the fetcher or combined?

P.S. I got another Github account, will do some test and update later.

**Comment by rickstaa** [comment] 2023-06-10 22:32
> Thanks, and let me go through the current issue again(after all those debugging I'm getting lost as well lol), bear with me since it will be a little lengthy.
> 
> For total commits(all or laster year), between official instance and private instace, there should be a clear difference since only private instance can read private repo commits. Unless the user has no private commits at all.
> 
> The example of your account shows a 8.9K vs 6.8K difference of total commits, which is the expected behavior since only your own instance can read all those private commits. And that's true for my case as well after I checked with postman, 1339 vs 1186 matched the result I have earlier 1.3K vs 1.2K. ([#2793 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/2793#issue-1748328574))
> 
> Therefore I think we can conclude that `include_total_commits` works as expected though the API is still buggy.
> 
> But if we look at total commits in 2023, from your account they are both 1.5K, I don't know how many commits you have in private repos so if you barely have private commits in 2023 it's probably correct, otherwise something is wrong. And for my case, I got the exact same number which is not expected since I have about 100 commits in private repos in 2023. When I use postman to call the API
> 
> ```
> https://api.github.com/search/commits?q=author:forsakenrei+author-date:>2022-12-31
> ```
> 
> with PAT I got 350, without it's 221. And from GRS the number is 269 for 2023(I assume the date range is after 2022-12-31, correct me if I'm wrong since I didn't read all the code). So there seems to be something wrong, with the API or the fetcher or combined?
> 
> P.S. I got another Github account, will do some test and update later.

Thanks for the detailed report. Great to hear that, although buggy, the `include_all_commit` flag is working with the PAT. 

For the other problem, since it uses GraphQL, it is effortless to check if it works by comparing the public version with the results from the [GraphQL explorer](https://docs.github.com/en/graphql/overview/explorer) when logged in to your user account. For my account, I got the results below. Strangely enough, the card doesn't show the right private commits 🤔.

**GraphQL private:**

```graphql
{
  "data": {
    "user": {
      "name": "Rick Staa",
      "login": "rickstaa",
      "contributionsCollection": {
        "totalCommitContributions": 1832,
        "restrictedContributionsCount": 352
      }
    }
  }
}
```

**GraphQL public**

```graphql
{
  "data": {
    "user": {
      "name": "Rick Staa",
      "login": "rickstaa",
      "contributionsCollection": {
        "totalCommitContributions": 1554,
        "restrictedContributionsCount": 675
      }
    }
  }
}
```

**Private card**

```md
[![Anurag's GitHub stats](https://github-readme-stats-rickstaa.vercel.app/api?username=rickstaa)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats-rickstaa.vercel.app/api?username=rickstaa)](https://github.com/anuraghazra/github-readme-stats)

**Public card**

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa)](https://github.com/anuraghazra/github-readme-stats)

**Comment by ForsakenRei** [comment] 2023-06-10 22:56
Yes, I think that's the case. PR, issue etc. all works, total commits works, but just commits in recent year didn't work properly.

My result from GraphQL basically echos your case, 412 is the total includes private commits while 269 is all the public commits. However private instance card shows the same number as the public one. A different Github/Vercel account reproduced this issue with the exact same behavior.

Debugger works but my JS knowledge is dragging me down, don't even know what I should look at lol.

**Comment by rickstaa** [comment] 2023-06-10 23:11
@ForsakenRei No problem. I created a small script in which we can test the behaviour 👍🏻.

```js
/**
 * Call the GitHub GraphQL API to see how many commits a user has made in the last year.
 */
import axios from "axios";

const QUERY = `
    query userInfo($login: String!) {
        user(login: $login) {
        name
        login
        contributionsCollection {
            totalCommitContributions
        }
        }
    }
`;
const VARIABLES = {
    "login": "rickstaa",
};
const PRIVATE_PAT = "<INSERT_PAT>"; // Pat that has access to your private repos and user data.
const PUBLIC_PAT = "<INSERT_PUBLIC_PAT>"; // Pat that has no access to your private repos.    

const main = async () => {

    // Fetch total public commits for a user.
    const res = await axios({
        url: "https://api.github.com/graphql",
        method: "post",
        headers: {
            Authorization: `bearer ${PRIVATE_PAT}`,
        },
        data: {
            "query": QUERY, "variables": VARIABLES
        },
    })

    // Print total private commits.
    console.log(`Total private commits: ${res.data.data.user.contributionsCollection.totalCommitContributions}`);

    // Fetch total public commits for a user.
    const res2 = await axios({
        url: "https://api.github.com/graphql",
        method: "post",
        headers: {
            Authorization: `bearer ${PUBLIC_PAT}`,
        },
        VARIABLES,
    })

    // Print total private commits.
    console.log(`Total public commits: ${res.data.data.user.contributionsCollection.totalCommitContributions}`);
}

main();
```

**Comment by rickstaa** [comment] 2023-06-10 23:15
@ForsakenRei I think I have it the PAT needs the `user:read` permission:

![image](https://github.com/anuraghazra/github-readme-stats/assets/17570430/098756ed-7016-445f-9133-2b34f18de761)

**Comment by rickstaa** [comment] 2023-06-10 23:22
My new results after giving the `read:user` permission to my PAT:

### Public results

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&random=1243)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&random=1243)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&include_all_commits=true&random=1243)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&include_all_commits=true&random=1243)](https://github.com/anuraghazra/github-readme-stats)

### Private results

```md
[![Anurag's GitHub stats](https://github-readme-stats-rickstaa.vercel.app/api?username=rickstaa&random=1243)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats-rickstaa.vercel.app/api?username=rickstaa&random=1243)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats-rickstaa.vercel.app/api?username=rickstaa&include_all_commits=true&random=1243)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats-rickstaa.vercel.app/api?username=rickstaa&include_all_commits=true&random=1243)](https://github.com/anuraghazra/github-readme-stats)

**Comment by ForsakenRei** [comment] 2023-06-10 23:26
Works for me as well!
I think no code change needed(hopefully) but doc change will be necessary then.

**Comment by rickstaa** [comment] 2023-06-10 23:36
Yea, will update the docs. For the language card, the `repo:status` permission is needed.

![image](https://github.com/anuraghazra/github-readme-stats/assets/17570430/6214d1fc-0985-4900-a190-55351ad8dbf4)


### Language card

#### Public

```md
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=rickstaa&langs_count=10&layout=compact&random=123435)](https://github.com/anuraghazra/github-readme-stats)
```

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=rickstaa&langs_count=10&layout=compact&random=123435)](https://github.com/anuraghazra/github-readme-stats)

#### Private

```md
[![Top Langs](https://github-readme-stats-rickstaa.vercel.app//api/top-langs/?username=rickstaa&langs_count=10&layout=compact&random=123435)](https://github.com/anuraghazra/github-readme-stats)
```

[![Top Langs](https://github-readme-stats-rickstaa.vercel.app//api/top-langs/?username=rickstaa&langs_count=10&layout=compact&random=123435)](https://github.com/anuraghazra/github-readme-stats)

**Closed by rickstaa** 2023-06-10 23:36 UTC
Labels: bug, :star: top bug

**Comment by ForsakenRei** [comment] 2023-06-10 23:38
Thanks for all the help!

**Comment by rickstaa** [comment] 2023-06-10 23:41
No problem. I created https://github.com/anuraghazra/github-readme-stats/pull/2805/files to prevent other people from having this problem.
