### ISSUE TITLE
cannot read properties of undefined reading user

### ISSUE THREAD

**Issue by rfyiamcool** [anuraghazra/github-readme-stats#2387] opened 2023-01-12 14:28 UTC
### Describe the bug

cannot read properties of undefined reading user

### Expected behaviour

cannot read properties of undefined reading user

### Screenshots / Live demo link

cannot read properties of undefined reading user

### Additional context

cannot read properties of undefined reading user

**Comment by SonyaCore** [comment] 2023-01-12 14:31
same for me :)
<img width="641" alt="image" src="https://user-images.githubusercontent.com/66337103/212093627-ec420aa1-1d2f-450f-aff1-257b83983d88.png">
https://github.com/SonyaCore/SonyaCore

**Comment by BabyfaceDeveloper** [comment] 2023-01-12 14:31
same here
![image](https://user-images.githubusercontent.com/58478947/212093772-2268d757-ec97-4591-8d4b-2bd62cc14193.png)

**Comment by Lukareliz** [comment] 2023-01-12 14:32
Same here!
![image](https://user-images.githubusercontent.com/101203704/212093955-26ab8e98-0959-46ed-aa83-960c5e3d3ac9.png)

**Comment by mabbaszadegan** [comment] 2023-01-12 14:33
me 2 :)

**Comment by rfyiamcool** [comment] 2023-01-12 14:37
please use new url `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api`.

it works 😁

**Comment by Lukareliz** [comment] 2023-01-12 14:39
> please use new url `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api`.
> 
> it works 😁

Thaks, have a nice day everyone!

**Comment by BabyfaceDeveloper** [comment] 2023-01-12 14:41
hmm they changed url. That's why

**Comment by BabyfaceDeveloper** [comment] 2023-01-12 15:03
@rfyiamcool 
The waka time still has that error

![image](https://user-images.githubusercontent.com/58478947/212101554-c886e3bc-7d39-43fa-9ffc-2c74e7822f7b.png)

`[![BabyfaceDeveloper's wakatime stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/wakatime?username=BabyfaceDeveloper)](https://github.com/anuraghazra/github-readme-stats)`

**Comment by VeckoTheGecko** [comment] 2023-01-12 15:10
> please use new url `https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api`.
> 
> it works 😁

Where is the first mention of this URL change @rfyiamcool ? Is it mentioned in this repo by the maintainers, or is this URL working off a deployment from a separate codebase?

**Comment by yooniversal** [comment] 2023-01-12 15:32
> please use new url https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api.
>
> it works 😁

thanks. it works 😊

before:
`https://github-readme-stats.vercel.app/api?username={username}`
after:
`https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username={username}`

**Comment by CodePurble** [comment] 2023-01-12 17:00
Is there a note from the author advising this migration? I can't find anything regarding the new URL from the author. Am I missing something?

**Comment by nu11secur1ty** [comment] 2023-01-12 17:14
fix:
## Source URL
```URL
https://github-readme-stats.vercel.app/api?
```
change to 
```URL
https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
````

**Comment by CodePurble** [comment] 2023-01-12 17:18
Yeah I get that everyone is moving to this new one, but what is the author's comment on this?

**Comment by VeckoTheGecko** [comment] 2023-01-12 17:19
None as far as I know. I [raised the same concern](https://github.com/anuraghazra/github-readme-stats/issues/2387#issuecomment-1380532664)

**Comment by rickstaa** [comment] 2023-01-12 21:43
Duplicate of #2380.

**Closed by rickstaa** 2023-01-12 21:43 UTC
Labels: bug
