### ISSUE TITLE
The `Contributed To` Count Was Decreased

### ISSUE THREAD

**Issue by jdevstatic** [anuraghazra/github-readme-stats#1454] opened 2021-11-10 13:25 UTC
**Describe the bug**
Hello guys, just want to ask, if you updated anything related to the `Contributed To`, because I noticed my count was decreased to 6 but I contributed to a lot of other repos and orgs.

Maybe, when you update certain piece of code related to graphql api, the count was affected. If this is the case, then this is already a bug.

Hoping there will be reply. Thanks.

**Comment by xdvrx1** [comment] 2021-11-10 13:29
https://github.com/anuraghazra/github-readme-stats/issues/1447

check the other issue also, I think they are related, thanks

**Comment by ElectroPerf** [comment] 2021-11-10 13:32
> **Describe the bug** Hello guys, just want to ask, if you updated anything related to the `Contributed To`, because I noticed my count was decreased to 6 but I contributed to a lot of other repos and orgs.
> 
> Maybe, when you update certain piece of code related to graphql api, the count was affected. If this is the case, then this is already a bug.
> 
> Hoping there will be reply. Thanks.

Yes this is the case... Actually is this something with github or your readme stats?

**Comment by ElectroPerf** [comment] 2021-11-10 13:33
> > **Describe the bug** Hello guys, just want to ask, if you updated anything related to the `Contributed To`, because I noticed my count was decreased to 6 but I contributed to a lot of other repos and orgs.
> > Maybe, when you update certain piece of code related to graphql api, the count was affected. If this is the case, then this is already a bug.
> > Hoping there will be reply. Thanks.
> 
> Yes this is the case... Actually is this something with github or the readme stats repo?

**Comment by xdvrx1** [comment] 2021-11-10 13:51
I am also not sure which side, either this app or GitHub itself, I just noticed the changes too. Also, mine was 2.7k commits, for now it was just 2.5k.

**Comment by xdvrx1** [comment] 2021-11-10 13:55
Also, if you noticed, the graph of GitHub is per year, if you click each year then add all the commits, mine will be more than 3k total commits. Check yours too, add them manually.

**Comment by ElectroPerf** [comment] 2021-11-10 14:34
> Also, if you noticed, the graph of GitHub is per year, if you click each year then add all the commits, mine will be more than 3k total commits. Check yours too, add them manually.

Yea  same

**Comment by nohli** [comment] 2021-12-21 18:00
Could it be that `contributed to` only counts the last 12 months?

**Comment by rickstaa** [comment] 2022-03-09 08:36
Related to #1053.

**Comment by rickstaa** [comment] 2022-09-25 09:22
Duplicate of #1515.

**Closed by rickstaa** 2022-09-25 09:22 UTC
Labels: bug, stats-card
