### ISSUE TITLE
Switch theme depending upon prefers-color-scheme?

### ISSUE THREAD

**Issue by 2KAbhishek** [anuraghazra/github-readme-stats#414] opened 2020-08-22 17:40 UTC
Is there a way that something like this can be implemented, because dark themes look out of place on the default github interface, unless the end user is using any kind of theme extension.

Would love to help with this.

![Light Theme Current](https://user-images.githubusercontent.com/25423853/90962160-8e975d80-e4cb-11ea-821c-40ee004be174.png)

![Dark Theme Current](https://user-images.githubusercontent.com/25423853/90962287-9d324480-e4cc-11ea-9ed4-aa55edb172cf.png)

*P S - I had modified the headings before taking the second screenshot, and the link is also visited, that's why colour is different. Please ignore these.*

**Comment by anuraghazra** [comment] 2020-11-05 10:30
duplicate of #79

**Closed by anuraghazra** 2020-11-05 10:30 UTC
