### ISSUE TITLE
`count_private` doesn't work properly

### ISSUE THREAD

**Issue by Zo-Bro-23** [anuraghazra/github-readme-stats#2450] opened 2023-01-21 10:56 UTC
### Describe the bug

`count_private` seems to be showing more contributions on the public instance than on a private instance with the correct PAT. More info [here](https://github.com/anuraghazra/github-readme-stats/discussions/2435#discussioncomment-4736301). Not a high severity issue, but might be worth taking the time to look at later on.

**Comment by rickstaa** [comment] 2023-01-24 11:14
Closing this since I can not reproduce it on any private Vercel instance other than @Fabio-Vicente's instance. Something went wrong during deployment.

# Your user account

## Without count private

### My fork (I have no access to your private repositories)

[![Anurag's GitHub stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=Fabio-Vicente&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=Fabio-Vicente&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

### Your fork (your PAT should have access to your private repositories)

[![Anurag's GitHub stats](https://readme-stats-fabio-vicente.vercel.app/api?username=Fabio-Vicente&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://readme-stats-fabio-vicente.vercel.app/api?username=Fabio-Vicente&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

### Public instance (should not have access to your private repositories)

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Fabio-Vicente&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Fabio-Vicente&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

## With count private

### My fork (I have no access to your private repositories)

[![Anurag's GitHub stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=Fabio-Vicente&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=Fabio-Vicente&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

### Your fork (your PAT should have access to your private repositories)

[![Anurag's GitHub stats](https://readme-stats-fabio-vicente.vercel.app/api?username=Fabio-Vicente&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://readme-stats-fabio-vicente.vercel.app/api?username=Fabio-Vicente&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

### Public instance (should not have access to your private repositories)

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Fabio-Vicente&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)


```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Fabio-Vicente&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

# My user account

## Without count private

### My fork (I should have access to my private repositories)

[![Anurag's GitHub stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=rickstaa&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=rickstaa&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

### Your fork (your PAT should not have access to my private repositories)

[![Anurag's GitHub stats](https://readme-stats-fabio-vicente.vercel.app/api?username=rickstaa&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://readme-stats-fabio-vicente.vercel.app/api?username=rickstaa&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

### Public instance (should not have access to my private repositories)

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

## With count private

### My fork (I should have access to my private repositories)

[![Anurag's GitHub stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=rickstaa&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=rickstaa&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

### Your fork (your PAT should not have access to my private repositories)

[![Anurag's GitHub stats](https://readme-stats-fabio-vicente.vercel.app/api?username=rickstaa&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://readme-stats-fabio-vicente.vercel.app/api?username=rickstaa&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

### Public instance (should not have access to my private repositories)

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)


```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa&count_private=true&random=2323431sd2f)](https://github.com/anuraghazra/github-readme-stats)
```

**Closed by rickstaa** 2023-01-24 11:14 UTC
Labels: bug
