### ISSUE TITLE
Double star count on GitHub Stats board

### ISSUE THREAD

**Issue by brunolnetto** [anuraghazra/github-readme-stats#2593] opened 2023-03-29 23:44 UTC
### Describe the bug

I have some stars, something between 15 to 20. Some time ago, the board I have [here](https://github.com/brunolnetto/brunolnetto), which used to count correctly, now have two times more stars than before. This sounds weird, but I am not sure if it occurs because of some misconfiguration on route queries. 

### Expected behaviour

Count repository stars correctly 

### Screenshots / Live demo link

Check the first board: https://github.com/brunolnetto/brunolnetto

**Comment by HemanthPaila** [comment] 2023-04-05 08:09
Hey @brunolnetto can I work on it. Could you please assign it to me?

**Comment by rickstaa** [comment] 2023-04-05 08:52
> ### Describe the bug
> I have some stars, something between 15 to 20. Some time ago, the board I have [here](https://github.com/brunolnetto/brunolnetto), which used to count correctly, now have two times more stars than before. This sounds weird, but I am not sure if it occurs because of some misconfiguration on route queries.
> 
> ### Expected behaviour
> Count repository stars correctly
> 
> ### Screenshots / Live demo link
> Check the first board: https://github.com/brunolnetto/brunolnetto
> 
> ### Additional context
> _No response_

@brunolnetto I just tried to reproduce your problem, but I am unable to do so on the main branch:

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=brunolnetto)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=brunolnetto)](https://github.com/anuraghazra/github-readme-stats)
```

![GitHub User's stars](https://img.shields.io/github/stars/brunolnetto?style=social)

```md
![GitHub User's stars](https://img.shields.io/github/stars/brunolnetto?style=social)
```

The problem caused because you use https://github.com/anuraghazra/github-readme-stats/pull/2459 or https://github.com/anuraghazra/github-readme-stats/pull/1122 which also counts stars for organizations you contributed to.

**Closed by rickstaa** 2023-04-05 08:52 UTC
Labels: bug
