### ISSUE TITLE
Card doesn't load, says maximum retries exceeded

### ISSUE THREAD

**Issue by ZahidMKhan** [anuraghazra/github-readme-stats#2231] opened 2022-10-25 14:55 UTC
### Describe the bug

the read-me stats card i have on my profile just not loading any information up anymore. It says that it retired fetching the information but failed every time and reached maximum retries limit. (check screenshot)

![image](https://user-images.githubusercontent.com/35687516/197807933-b41e9e81-7b37-4f14-8fea-5b5bcb191f72.png)

### Screenshots / Live demo link

![image](https://user-images.githubusercontent.com/35687516/197808045-f8d84b30-94c0-4be5-bb51-c36daefb66e6.png)

**Comment by lazy-geek** [comment] 2022-10-25 15:31
i am facing same issue

**Comment by rickstaa** [comment] 2022-10-25 19:37
@ZahidMKhan, thanks for your bug report. This issue is caused by the Public Vercel server being overloaded. The easiest way to prevent this error from happening is to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). You can find more information in #1471.

**Comment by rickstaa** [comment] 2022-10-25 19:37
Closing this for now since this issue is tracked in #1471.

**Closed by rickstaa** 2022-10-25 19:37 UTC
Labels: bug
