### ISSUE TITLE
Please include the ownership and contributions to organizations in the metrics.

### ISSUE THREAD

**Issue by ManuelSchneid3r** [anuraghazra/github-readme-stats#1035] opened 2021-04-30 08:49 UTC
Not much more to say. I dont see the point In rating private repos only

**Comment by GMkonan** [comment] 2021-06-26 22:05
Agree, A lot of people contribute a lot for organizations and there is no mention of it in the cards. But to be fair I don't know how possible or impossible is to make this feature, will probably investigate myself :)

**Comment by anuraghazra** [comment] 2021-06-27 10:47
Duplicate of #1

**Closed by anuraghazra** 2021-06-27 10:47 UTC
