### ISSUE TITLE
include_all_commits tag sets Total Commits value to 0

### ISSUE THREAD

**Issue by Tomgxz** [anuraghazra/github-readme-stats#2821] opened 2023-06-14 16:01 UTC
### Describe the bug

include_all_commits tag sets Total Commits value to 0

### Expected behavior

Expected it to show a number >=375, which is the value for 2023.

### Screenshots / Live demo link

![Tomgxz's GitHub stats](https://github-readme-stats.vercel.app/api?username=Tomgxz&show_icons=true&theme=holi&hide_border=true&bg_color=00000000&include_all_commits=true)

**Comment by rickstaa** [comment] 2023-06-14 21:03
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/1515.

**Closed by rickstaa** 2023-06-14 21:03 UTC
Labels: bug
