### ISSUE TITLE
Add `card_width` argument to pin card

### ISSUE THREAD

**Issue by yaten2302** [anuraghazra/github-readme-stats#3406] opened 2023-10-22 19:35 UTC
### Is your feature request related to a problem? Please describe.

Currently there is no way to set the width of the `pin card` manually,.

### Describe the solution you'd like

Adding the `card_width` argument to the pin card endpoint.

**Comment by parthasdey2304** [comment] 2023-10-25 10:26
Would you please assign that to me!

**Comment by bikrantjajware** [comment] 2023-10-25 11:52
Hello @yaten2302 , linked a PR to fix this issue please review

**Comment by yaten2302** [comment] 2023-10-26 05:13
Hi @bikrantjajware, I'm not the maintainer of GRS. I just created the issue so that the maintainers could assign it to me, but it's perfectly fine if you have created the PR👍

**Comment by rickstaa** [comment] 2023-10-30 10:27
Duplicate of #3368 will be fixed when #3359 is merged.

**Closed by rickstaa** 2023-10-30 10:27 UTC
Labels: enhancement
