### ISSUE TITLE
The github-readme-stats is not working.

### ISSUE THREAD

**Issue by 0055kms** [anuraghazra/github-readme-stats#3858] opened 2024-07-18 11:11 UTC
### Describe the bug

The github-readme-stats is not working.
![image](https://github.com/user-attachments/assets/80b043b7-3b5d-4527-8874-911479fe3672)

**Comment by qwerty541** [comment] 2024-07-18 19:02
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/3851

**Closed by qwerty541** 2024-07-18 19:02 UTC
Labels: bug
