### ISSUE TITLE
Complaining about not having a token set

### ISSUE THREAD

**Issue by galaxine-senpai** [anuraghazra/github-readme-stats#2590] opened 2023-03-27 16:33 UTC
### Describe the bug

When embedded in a profile, it complains that there is not a token provided on some of the "embeds" but not others.

### Expected behaviour

It should display the stats as normal

### Screenshots / Live demo link

***WILL EDIT THIS LATER AS I AM NOT HOME***

### Additional context

This is happening on the link provided by the repo and one I self-hosted on vercel, I am also using a brand new token.

***ISSUE HAS RESOLVED ITSELF BUT WILL LEAVE OPEN FOR THE PROBLEM WITH THE MAIN LINK***

**Comment by 000rosiu** [comment] 2023-03-27 19:01
The same for me... `Something went wrong! file an issue at https://tiny.one/readme-stats
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel`

**Comment by bnylund** [comment] 2023-03-27 19:07
Same issue over here.

![image](https://user-images.githubusercontent.com/31191383/228041805-178902da-9cc8-4dca-9259-51e259b31581.png)

**Comment by xPoke-glitch** [comment] 2023-03-28 15:12
Same for me. It seems like the problem is related to the username - I've tried changing it with the username of one of my friend and it works. But when I change it back to mine, it doesn't work.

**Comment by galaxine-senpai** [comment] 2023-03-28 15:17
> Same for me. It seems like the problem is related to the username - I've tried changing it with the username of one of my friend and it works. But when I change it back to mine, it doesn't work.

Have you tried using all lowercase? (xpoke-glitch)

**Comment by xPoke-glitch** [comment] 2023-03-28 15:19
> 

Fixed by changing the API URL like this: `https://github-readme-stats-sigma-five.vercel.app/api` (I added sigma-five to it)

**Comment by galaxine-senpai** [comment] 2023-03-28 15:21
It should work regardless of which link you use.

**Closed** 2023-03-29 08:38 UTC
Labels: bug

**Comment by PencilNavigator** [comment] 2023-04-14 13:07
> > 
> 
> Fixed by changing the API URL like this: `https://github-readme-stats-sigma-five.vercel.app/api` (I added sigma-five to it)

https://github.com/PencilNavigator/readme-stats-URL
here are also some url that you can use.
