### ISSUE TITLE
[Feature Request] [New Card] Pinned Gists

### ISSUE THREAD

**Issue by MirayXS** [anuraghazra/github-readme-stats#308] opened 2020-08-04 16:43 UTC
**Is your feature request related to a problem? Please describe.**
I have some `GISTS` to display in my profile. You can display GISTS as pinned repositories on github, but i don't have any space to put these gists.

**Describe the solution you'd like**
I would like a new card; `Pinned Gists Card` wich will display github gists; like the Pinned Repositories one

**Comment by MirayXS** [comment] 2020-08-04 16:47
This is an example of my idea

![image](https://user-images.githubusercontent.com/55494819/89321261-00297c00-d683-11ea-8a81-17c754172232.png)

**Comment by nthnchu** [comment] 2020-08-04 21:37
I think this is a duplicate of #13. This would be cool though 👍

**Comment by anuraghazra** [comment] 2020-08-11 13:20
There are few difficulties with pinned gists i mentioned in #13

**Comment by anuraghazra** [comment] 2020-10-03 07:08
Closing this since we are not gonna include this feature as mentioned in https://github.com/anuraghazra/github-readme-stats/issues/13#issuecomment-699643208

**Closed** 2020-10-03 07:08 UTC
