### ISSUE TITLE
Github stats not loading 

### ISSUE THREAD

**Issue by SimardeepSingh-zsh** [anuraghazra/github-readme-stats#3263] opened 2023-09-20 16:19 UTC
### Describe the bug

Error message displaying as follows :-
Something went wrong! file an issue at https://tiny.one/readme-stats
Could not fetch total commits.
<img width="1440" alt="Screenshot 2023-09-20 at 10 17 04 AM" src="https://github.com/anuraghazra/github-readme-stats/assets/134756717/4322c1fe-e650-4e32-a356-c97bbf50f4bb">

### Expected behavior

From my perspective this is the API failure/err.

### Screenshots / Live demo link

# 💻 Tech Stack:
![GraphQL](https://img.shields.io/badge/-GraphQL-E10098?style=for-the-badge&logo=graphql&logoColor=white) ![JavaScript](https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E) ![Python](https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54) ![HTML5](https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white) ![CSS3](https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white) ![AWS](https://img.shields.io/badge/AWS-%23FF9900.svg?style=for-the-badge&logo=amazon-aws&logoColor=white) ![Jenkins](https://img.shields.io/badge/jenkins-%232C5263.svg?style=for-the-badge&logo=jenkins&logoColor=white) ![AmazonDynamoDB](https://img.shields.io/badge/Amazon%20DynamoDB-4053D6?style=for-the-badge&logo=Amazon%20DynamoDB&logoColor=white) ![MySQL](https://img.shields.io/badge/mysql-%2300f.svg?style=for-the-badge&logo=mysql&logoColor=white) ![LINUX](https://img.shields.io/badge/Linux-FCC624?style=for-the-badge&logo=linux&logoColor=black) ![GIT](https://img.shields.io/badge/Git-fc6d26?style=for-the-badge&logo=git&logoColor=white) ![Docker](https://img.shields.io/badge/docker-%230db7ed.svg?style=for-the-badge&logo=docker&logoColor=white) ![Jira](https://img.shields.io/badge/jira-%230A0FFF.svg?style=for-the-badge&logo=jira&logoColor=white) ![Kubernetes](https://img.shields.io/badge/kubernetes-%23326ce5.svg?style=for-the-badge&logo=kubernetes&logoColor=white) ![Terraform](https://img.shields.io/badge/terraform-%235835CC.svg?style=for-the-badge&logo=terraform&logoColor=white) ![Angular](https://img.shields.io/badge/angular-%23DD0031.svg?style=for-the-badge&logo=angular&logoColor=white)

# 📊 GitHub Stats:
![](https://github-readme-stats.vercel.app/api?username=SimardeepSingh-zsh&theme=highcontrast&hide_border=false&include_all_commits=true&count_private=false)<br/>
![](https://github-readme-streak-stats.herokuapp.com/?user=SimardeepSingh-zsh&theme=highcontrast&hide_border=false)<br/>
![](https://github-readme-stats.vercel.app/api/top-langs/?username=SimardeepSingh-zsh&theme=highcontrast&hide_border=false&include_all_commits=true&count_private=false&layout=compact)

**Comment by Iamtsquare07** [comment] 2023-09-20 19:16
According to the team, this is caused by too many requests. however they promised to change the error message to something more practical, and it may resolve itself after a few seconds, I knew because I opened a similar issue and they told me that.

**Comment by qwerty541** [comment] 2023-09-21 15:13
@SimardeepSingh-zsh Thanks for the report! You can see this when upstream GitHub API respond with error due to some reason during fetching stats card data. Should be resolve automatically after some time. Currently stats card in your profile works well.

@Iamtsquare07 I have opened pull request https://github.com/anuraghazra/github-readme-stats/pull/3255 which improves error message, but due to branch protection rules i need to receive at least one approve from another collaborator to merge it.

Closing as duplicate of https://github.com/anuraghazra/github-readme-stats/issues/3243

**Closed by qwerty541** 2023-09-21 15:13 UTC
Labels: bug

**Comment by qwerty541** [comment] 2023-09-21 17:15
@SimardeepSingh-zsh @Iamtsquare07 Recently we merged https://github.com/anuraghazra/github-readme-stats/pull/3238 which improved confusing behavior of showing 0 commits when upstream API feails, currently we show an error instead, i'm curious what you guys think about this change.

**Comment by rickstaa** [comment] 2023-09-21 18:35
We merged https://github.com/anuraghazra/github-readme-stats/pull/3255 to improve the error message.
