### ISSUE TITLE
2024-7-18 vercel服务器异常，卡片无法使用。我想，我自己可以解决了哈哈🤣打扰了！

### ISSUE THREAD

**Issue by lieheng-1** [anuraghazra/github-readme-stats#3852] opened 2024-07-18 01:20 UTC
### Describe the bug

像这个，

`https://github-readme-stats.vercel.app/api?username=lmliheng&theme=dark&show_icons=true`

是错误的😅

### Screenshots / Live demo link

![image](https://github.com/user-attachments/assets/b6e17875-140e-4c50-bc84-a4fea622cbf5)

**Comment by thunderbolt-fire** [comment] 2024-07-18 01:27
怎么解决啊

**Comment by fcoagz** [comment] 2024-07-18 01:38
how we can help...? :(

**Comment by qwerty541** [comment] 2024-07-18 02:14
Closing this issue since it is related to Vercel rather than this repository.

Hope this link will help:

https://vercel.com/guides/why-is-my-account-deployment-blocked

**Comment by qwerty541** [comment] 2024-07-18 02:22
Sorry, looks like I was wrong, at first i though that the problem was on your private deployment, but now I see that public deployment doesn't work. I will contant Anurag via direct message since only he has access to Vercel account.

**Comment by fcoagz** [comment] 2024-07-18 02:41
Possibly a request made from github when pulling the data. They made changes to the github api or to the request

**Comment by itsanji** [comment] 2024-07-18 03:10
@lieheng-1 Could you please translate the issue title into English so others can understand it?

**Comment by lieheng-1** [comment] 2024-07-18 06:44
> 怎么解决啊

目前公有vercel是不生效的，可以私有化

**Comment by lieheng-1** [comment] 2024-07-18 06:45
> how we can help...? :(

我想我能自己解决，感谢老哥！😄🤣

**Comment by lieheng-1** [comment] 2024-07-18 06:46
> Sorry, looks like I was wrong, at first i though that the problem was on your private deployment, but now I see that public deployment doesn't work. I will contact Anurag via direct message since only he has access to Vercel account.

好的👍

**Comment by lieheng-1** [comment] 2024-07-18 06:47
> @lieheng-1 Could you please translate the issue title into English so others can understand it?

Sure, brother. I love the translation function of the browser too much😝

**Comment by MagicGopher** [comment] 2024-07-18 07:55
> > Sorry, looks like I was wrong, at first i though that the problem was on your private deployment, but now I see that public deployment doesn't work. I will contact Anurag via direct message since only he has access to Vercel account.
> 
> 好的👍

老哥，描述英文，不然国际友人看不懂。

**Comment by lmliheng** [comment] 2024-07-18 08:14
> > > Sorry, looks like I was wrong, at first i though that the problem was on your private deployment, but now I see that public deployment doesn't work. I will contact Anurag via direct message since only he has access to Vercel account.
> > 
> > 
> > 好的👍
> 
> 老哥，描述英文，不然国际友人看不懂。

🤣🤣🤣

**Comment by lmliheng** [comment] 2024-07-18 08:16
Private deployment, like this

![image](https://github.com/user-attachments/assets/389d4ea2-436b-440e-9cd5-b508ba425c29)

**Comment by qwerty541** [comment] 2024-07-18 18:53
Hey guys! All this time the public instance was deployed on Vercel on the account with enterprise plan provided for free for Anurag. I just received a message from Anurag that Vercel stopped their OSS sponsorship and account was returned to basic plan, so when the limits was exceeded the deployment was paused. As I understand, at the moment Anurag returned it to work with own money, but in the near future we have to migrate on another cloud provider because Vercel is very expensive. Therefore, deployment on the [github-readme-stats.vercel.app](https://github-readme-stats.vercel.app/) will be shutdown soon. For now I recommend you all to [deploy your own Vercel instances](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel) in order to avoid impact of future shutdown of public instance.

**Comment by qwerty541** [comment] 2024-07-18 18:58
Duplicate of https://github.com/anuraghazra/github-readme-stats/issues/3851

**Closed by qwerty541** 2024-07-18 18:58 UTC

**Comment by fcoagz** [comment] 2024-07-18 20:30
@qwerty541 thank you!
