### ISSUE TITLE
Support for Organizations

### ISSUE THREAD

**Issue by kaaax0815** [anuraghazra/github-readme-stats#668] opened 2020-11-29 19:19 UTC
**Is your feature request related to a problem? Please describe.**
I have many of my repositories on a organization 

**Describe the solution you'd like**
Be able to declare a Organisation for e. G. languages card

**Comment by Zethson** [comment] 2020-12-04 22:20
I would like to second this request. I am mostly contributing to organizations and would like to have this reflected.

**Comment by BenMorel** [comment] 2020-12-06 02:45
Same here. Most of my stars come from projects I own under an organization, so the card does not reflect my actual contributions.

**Comment by anuraghazra** [comment] 2020-12-06 15:21
duplicate of #1

See #1 for more info.

**Closed by anuraghazra** 2020-12-06 15:21 UTC
