### ISSUE TITLE
Suggestion for more ranks or a different raking system.

### ISSUE THREAD

**Issue by codereptile** [anuraghazra/github-readme-stats#1579] opened 2022-02-09 17:34 UTC
**Is your feature request related to a problem? Please describe.**
I think that 5 rank levels is too little. Most people instantly get the `A+` level, but then it takes roughly 1900 commits to get to level `A++`. If you work on several complicated projects and make about 2-3 commits per day, it would take you 2 years of continuous work to reach the `A++` level. 

For me, these levels could be a good opportunity to motivate people to commit more to open source, especially if you could see a gradual increase in your level as you progress. However, setting a goal so far away makes it much less exciting and motivating (at least that's what happened to me).

**Describe the solution you'd like**
I would like to suggest to increase the number of available levels to at least 10 or more. The exact number is debatable, but in my opinion, it should be such that you would see a first increase in your level in several moths, not 2 years.

**Describe alternatives you've considered**
A possible alternative is to set levels as a value that steadily increases from 1 to infinity. My proposal would be such:
lvl 1 is available immediately to all github users.
lvl 2 is reached when you have a score of 1 (i mean the non-normalized score at [src/calculateRank.js](./src/calculateRank.js))
This is roughly 2 repos and 60 commits, which can easily be gained in the first week.
lvl 3 is reached when you have a score of 2
lvl 4 = score of 3
...
The exact function is, again, debatable, but the general idea is that you would see a lvl up every month (for avg active user).

To counter for faster growth as you develop, a non linear function can be used. My take on it is:

lvl x = score of x^(Pi / 2)

Reasoning: It simple, it has Pi and it grows reasonably slow at the start, but we won't see lvl 100500.

**Comment by rickstaa** [comment] 2022-03-09 09:00
Related to #455.

**Comment by rickstaa** [comment] 2023-05-26 13:51
Duplicate of #2265. You are welcome to add your suggestion there 👍🏻.

**Closed by rickstaa** 2023-05-26 13:51 UTC
Labels: enhancement, ranks, proposal

**Comment by Khusinov** [comment] 2023-10-20 05:42
oh thanks guys
