### ISSUE TITLE
Toggle bold off or on for stats card

### ISSUE THREAD

**Issue by anubhav217** [anuraghazra/github-readme-stats#1426] opened 2021-10-28 21:36 UTC
**Describe the bug**

**Expected behavior**

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**

**Comment by anuraghazra** [comment] 2021-12-13 14:51
Duplicate of #1169

**Closed by anuraghazra** 2021-12-13 14:51 UTC
