### ISSUE TITLE
"Most used langs" api is bugging

### ISSUE THREAD

**Issue by zplusfour** [anuraghazra/github-readme-stats#803] opened 2021-01-10 18:02 UTC
## It displays languages that I don't know and I don't use
Like the TeX programming language, I don't know what is it and how to use it, and I don't have a repo with the `.tex` file extension

## I expected to see
1. JavaScript
2. C++
3. HTML
4. CSS
4. Go

## Some images
**Preview**: <br />
![image](https://user-images.githubusercontent.com/73612690/104131313-45628000-537e-11eb-8408-3e4c1851956c.png)

**Code**: <br />
![image](https://user-images.githubusercontent.com/73612690/104131389-b013bb80-537e-11eb-940c-2478b534d2b7.png)

## Notes
This project is amazing, good job on it, I'll be very happy when you fix the bug 😄 
Have a great day!

**Comment by anuraghazra** [comment] 2021-01-11 10:55
Hi @zplusfour thanks for opening the PR. 

This is not a bug tho.. you do have TeX in this repo https://github.com/zplusfour/rapi 
![image](https://user-images.githubusercontent.com/35374649/104171992-86639e80-5429-11eb-971b-8f56e48d64f0.png)


If you don't want TeX in your language card use the `hide` parameter

https://github-readme-stats.vercel.app/api/top-langs?username=zplusfour&hide=TeX

**Comment by zplusfour** [comment] 2021-01-11 11:16
oh i'm very sorry!
thanks!!

**Comment by anuraghazra** [comment] 2021-01-11 18:58
Awesome hopefully that resolved your issue. Closing this now. :)

**Closed by anuraghazra** 2021-01-11 18:58 UTC
