### ISSUE TITLE
Something went wrong! file an issue at https://tiny.one/readme-stats

### ISSUE THREAD

**Issue by abdulrhmanalqassas** [anuraghazra/github-readme-stats#2391] opened 2023-01-12 19:07 UTC
### Describe the bug

at request to ( https://github-readme-stats.vercel.app/api?username=ali ) 
 
the response is  :  
Something went wrong! file an issue at https://tiny.one/readme-stats
Cannot read properties of undefined (reading 'user')

for : 
(any user name ) .

### Expected behaviour

Get dynamically generated GitHub stats  for the user.

### Screenshots / Live demo link

![image](https://user-images.githubusercontent.com/46942535/212158135-33a46039-dffe-46e9-a183-9feb8e922b53.png)

**Comment by figonzal1** [comment] 2023-01-12 19:09
before posting a problem read existing ones #2388

**Comment by IODevBlue** [comment] 2023-01-12 19:23
I'm getting this exact same error on my profile. Somehow, it's working for others but not mine.

**Comment by AdityaSeth777** [comment] 2023-01-12 19:37
Is it working for others ?
I just saw a couple of profiles and saw that it isn't.

**Comment by IODevBlue** [comment] 2023-01-12 19:45
This should work for your profile, I just tried it now:

https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?username=adityaseth777&&show_icons=true&theme=dark

The link has changed but the readme says nothing about the changes.

**Comment by AdityaSeth777** [comment] 2023-01-12 19:48
Heyy !! 
Thanks :)

**Comment by IODevBlue** [comment] 2023-01-12 19:55
You're welcome!!

Can I follow for a follow back? Let's connect and contribute to open source 😄

**Comment by djerfy** [comment] 2023-01-12 19:56
This url is just a temporary solution, see #2390

**Comment by dhayanesh** [comment] 2023-01-12 20:22
I have updated the URL and it works now.

[![Top Langs](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs/?username=username&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

**Comment by dhayanesh** [comment] 2023-01-12 20:22
I updated the url and it works now
[![Top Langs](https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs/?username=anuraghazra&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

**Comment by AdityaSeth777** [comment] 2023-01-12 20:24
Sure absolutely :)
I did follow you though @IODevBlue

**Comment by EvgenyPlaksin** [comment] 2023-01-12 20:25
@dhayanesh, it works, thanks!

**Comment by rickstaa** [comment] 2023-01-12 21:36
I can not find an error in the code base 🤔. I think it is a problem with the @anuraghazra Vercel instance. I texted him to check if he could find out what was going wrong. You can use my Vercel instance, but I'm afraid it will be rate-limited very quickly since GitHub allows only 5000 API requests per hour on my instance, and we currently use 70k per hour on the public Vercel instance 🤣. As explained in https://github.com/anuraghazra/github-readme-stats/issues/1471, the best option is to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). 👍

**Comment by rickstaa** [comment] 2023-01-12 21:41
Duplicate of #2380.

**Closed by rickstaa** 2023-01-12 21:41 UTC
Labels: bug

**Comment by PiyushKumar-18-AI** [comment] 2023-01-12 23:02
<img width="1609" alt="Screenshot 2023-01-13 at 4 30 23 AM" src="https://user-images.githubusercontent.com/68659006/212199512-2b62bcf4-8566-45ee-b31c-2ef749fb9a75.png">

Add "-git-masterrstaa-rickstaa" into the existing code and your problem will be solved.

from:

https://github-readme-stats.vercel.app/api?

into:

https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?

**Comment by rickstaa** [comment] 2023-01-13 00:19
> In the following image you can see the change in the readme file which fixed the github-readme problem. <img alt="Screenshot 2023-01-13 at 4 30 23 AM" width="1609" src="https://user-images.githubusercontent.com/68659006/212199512-2b62bcf4-8566-45ee-b31c-2ef749fb9a75.png">
> 
> So, by adding "-git-masterrstaa-rickstaa" into the existing code and your problem will be solved.
> 
> from:
> 
> https://github-readme-stats.vercel.app/api?
> 
> into:
> 
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?



> In the following image you can see the change in the readme file which fixed the github-readme problem. <img alt="Screenshot 2023-01-13 at 4 30 23 AM" width="1609" src="https://user-images.githubusercontent.com/68659006/212199512-2b62bcf4-8566-45ee-b31c-2ef749fb9a75.png">
> 
> So, by adding "-git-masterrstaa-rickstaa" into the existing code and your problem will be solved.
> 
> from:
> 
> https://github-readme-stats.vercel.app/api?
> 
> into:
> 
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?

Please check https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1381025166. We will likely have the same problem on my branch if everybody uses it. Best to deploy your own instance for now.

**Comment by anuraghazra** [comment] 2023-01-13 07:52
Hi this is fixed in #2400 you may revert back to the original URL to get latest updates. 

https://github.com/anuraghazra/github-readme-stats/issues/2380#issuecomment-1381436516

**Comment by iAmKankan** [comment] 2023-01-16 20:47
> In the following image you can see the change in the readme file which fixed the github-readme problem. <img alt="Screenshot 2023-01-13 at 4 30 23 AM" width="1609" src="https://user-images.githubusercontent.com/68659006/212199512-2b62bcf4-8566-45ee-b31c-2ef749fb9a75.png">
> 
> So, by adding "-git-masterrstaa-rickstaa" into the existing code and your problem will be solved.
> 
> from:
> 
> https://github-readme-stats.vercel.app/api?
> 
> into:
> 
> https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?

Solved.. Thanks

**Comment by rickstaa** [comment] 2023-01-16 21:19
> > In the following image you can see the change in the readme file which fixed the github-readme problem. <img alt="Screenshot 2023-01-13 at 4 30 23 AM" width="1609" src="https://user-images.githubusercontent.com/68659006/212199512-2b62bcf4-8566-45ee-b31c-2ef749fb9a75.png">
> > So, by adding "-git-masterrstaa-rickstaa" into the existing code and your problem will be solved.
> > from:
> > https://github-readme-stats.vercel.app/api?
> > into:
> > https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api?
> 
> Solved.. Thanks

Please check https://github.com/anuraghazra/github-readme-stats/issues/2391#issuecomment-1381142500. If everybody starts using my Vercel instance it will soon also be rate limited. 😅

**Comment by iAmKankan** [comment] 2023-01-16 23:54
Just seen brother..it was my bad. Corrected

**Comment by j-archives** [comment] 2023-01-19 11:51
> -git-masterrstaa-rickstaa

Thanks! it worked :))

**Comment by kavinkumar24** [comment] 2023-07-12 13:21
Thank you , it's working fine

**Comment by Moyosore1605** [comment] 2023-08-04 15:53
Please, what should I do, although I can see the 'add env variable to vercel with my github token' but I don't know how to go about that so I came to file a complaint first

**Comment by qwerty541** [comment] 2023-08-05 01:39
> Please, what should I do, although I can see the 'add env variable to vercel with my github token' but I don't know how to go about that so I came to file a complaint first

@Moyosore1605 You can't do that because you are using public Vercel instance instead of own. This error means that all GitHub API tokens hit the limits due to high load. The only way to avoid this error is [deploying you own Vercel instance](https://github.com/anuraghazra/github-readme-stats#on-vercel) using your own GitHub API token. You can read more about this error there: https://github.com/anuraghazra/github-readme-stats/issues/1471
