### ISSUE TITLE
Star Count doesn't include organisations

### ISSUE THREAD

**Issue by FredHappyface** [anuraghazra/github-readme-stats#924] opened 2021-03-05 01:03 UTC
**Describe the bug**

The star count is lower than expected and looking at how its calculated I think this is because organisations are not included in this 

A list of organisations can be obtained from https://api.github.com/users/:user/orgs for public memberships eg. https://api.github.com/users/fredhappyface/orgs

**Expected behavior**
Star counts includes that of organisations a user is a member of (config option?)

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
<details>
  <summary>Spoiler warning</summary>
<img src="https://user-images.githubusercontent.com/41634689/110051738-4e544a00-7d4e-11eb-81d0-4b956118eae9.png">
</details>

**Additional context**

**Comment by anuraghazra** [comment] 2021-03-07 16:21
For more info please see the mentioned issue. thanks!

Duplicate of #1

**Closed by anuraghazra** 2021-03-07 16:21 UTC
