### ISSUE TITLE
parameter to set the height and font size of cards with different description lengths the same.

### ISSUE THREAD

**Issue by Extravi** [anuraghazra/github-readme-stats#3159] opened 2023-08-28 04:10 UTC
### Is your feature request related to a problem? Please describe.

![image](https://github.com/anuraghazra/github-readme-stats/assets/98912029/5ea2c66c-961f-471e-84cb-4dba2500765b)

so i wont have to do this and result in the above
```html
            <a href="https://github.com/Extravi/tailsx" target="_blank">
                <img alt="svg" class="github" align="middle" src="https://github-readme-stats.vercel.app/api/pin/?username=Extravi&amp;repo=tailsx&amp;theme=dark&amp;border_color=3c4043" height="150">
            </a>            
```

### Describe the solution you'd like

add &line_height=75 or something like that

### Describe alternatives you've considered

```html
            <a href="https://github.com/Extravi/tailsx" target="_blank">
                <img alt="svg" class="github" align="middle" src="https://github-readme-stats.vercel.app/api/pin/?username=Extravi&amp;repo=tailsx&amp;theme=dark&amp;border_color=3c4043" height="150">
            </a>            
```

setting that but it wont look right

### Additional context

na

**Comment by Extravi** [comment] 2023-08-28 04:11
https://github.com/anuraghazra/github-readme-stats/discussions/3158

**Comment by Extravi** [comment] 2023-08-28 08:21
I want to do something like this for those that don't have the same height so they can all fix it correctly.

![Screenshot_20230828_042016](https://github.com/anuraghazra/github-readme-stats/assets/98912029/b35db889-5822-4a1c-bc01-e2bdfcfc3458)

**Comment by anmolchhabra21** [comment] 2023-10-01 13:25
@Extravi, I am thinking about showing the content to a specific length and using "..." after, suppose only 2 lines, and fixing the text width for the heading as well as the content, this should solve this, Could You please Assign me this?

**Comment by devvrat011** [comment] 2023-10-03 15:51
plss assign it to me. I can solve this.

**Comment by rickstaa** [comment] 2023-10-12 15:07
@anmolchhabra21, thanks for considering contributing to our project 🚀. I assigned you to the issue.

**Comment by rickstaa** [comment] 2023-10-12 17:35
Hey @anmolchhabra21, tackling this feature request took a bit of pondering. It seems like @Extravi has a wishlist:

- Wanting to tweak card height through query parameters. In my opinion, this is a bit redundant since people can already do this with HTML. However, if @anuraghazra and @qwerty541 are okay with it, I think it's okay.
- Expressing a desire to play with the font size of the main card text. I'm not sold on this—it might turn our styling into a bit of a fashion disaster.
- Fixing an issue when different-length card descriptions are placed next to each other. 

@Extravi, is there any chance you could show us the bug in action and elaborate on the first two points? I really appreciate any help you can provide.

**Comment by Extravi** [comment] 2023-10-12 19:38
> Hey @anmolchhabra21, tackling this feature request took a bit of pondering. It seems like @Extravi has a wishlist:
> 
>     * Wanting to tweak card height through query parameters. In my opinion, this is a bit redundant since people can already do this with HTML. However, if @anuraghazra and @qwerty541 are okay with it, I think it's okay.
> 
>     * Expressing a desire to play with the font size of the main card text. I'm not sold on this—it might turn our styling into a bit of a fashion disaster.
> 
>     * Fixing an issue when different-length card descriptions are placed next to each other.
> 
> 
> @Extravi, is there any chance you could show us the bug in action and elaborate on the first two points? I really appreciate any help you can provide.

if i try to resize the image to match other images with more text it gets messed up
![image](https://github.com/anuraghazra/github-readme-stats/assets/98912029/32e85558-0870-481d-b4f5-2506e834deff)

**Comment by Extravi** [comment] 2023-10-12 19:39
i had to put more text in my github repo description to fix it 

![image](https://github.com/anuraghazra/github-readme-stats/assets/98912029/9464e446-358c-4b79-9ebf-166da0bbac00)

**Comment by Extravi** [comment] 2023-10-12 19:40
![image](https://github.com/anuraghazra/github-readme-stats/assets/98912029/49c1fbab-f76b-4bb5-89ea-586a93b2f699)

**Comment by Extravi** [comment] 2023-10-12 19:40
thats what i had to do

**Comment by rickstaa** [comment] 2023-10-13 08:40
@Extravi, thanks for your elaborate answer. I tried to reproduce your problems but have been unable to do so.

#### Without height property

<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=bendyworks&repo=bwoken"/>
</a>
</div>

```html
<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=bendyworks&repo=bwoken"/>
</a>
</div>
```

#### With height property

<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img height=259 src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img height=259 src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=bendyworks&repo=bwoken"/>
</a>
</div>

```html
<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img height=200 src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img height=200 src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=bendyworks&repo=bwoken"/>
</a>
</div>
```

**Comment by Extravi** [comment] 2023-10-13 08:42
@anuraghazra that went to my email I still saw it

**Comment by Extravi** [comment] 2023-10-13 08:43
idk it's an issue I had months ago I don't know how to explain it again.

**Comment by rickstaa** [comment] 2023-10-13 08:43
> @anuraghazra that went to my email, I still saw it

Sorry, I'm trying to reproduce your issue, but GitHub's cache is not updating my example cards, so I removed the comment again. I will tag you when I am done experimenting 😅.

**Comment by Extravi** [comment] 2023-10-13 08:44
in the screenshot you sent they are still not the same height as each other

**Comment by Extravi** [comment] 2023-10-13 08:44
alright

**Comment by rickstaa** [comment] 2023-10-13 09:02
@Extravi, big thanks for the detailed response. I successfully replicated the issue you mentioned. It seems to stem from the use of the HTML height property, causing the SVG image to scale and the fonts to enlarge.

I'm thinking we could introduce a card_height argument, ensuring that it maintains the minimum height required for displaying the text 🤔. Any thoughts on this, @anuraghazra or @qwerty541? Open to better ideas!

#### Without height property

<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask"/>
</a>
</div>

```html
<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask"/>
</a>
</div>
```

#### With height property

<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img height=120 src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img height=120 src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask"/>
</a>
</div>

```html
<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img height=120 src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img height=120 src="https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask"/>
</a>
</div>
```

**Comment by rickstaa** [comment] 2023-10-14 07:43
Related to https://github.com/anuraghazra/github-readme-stats/issues/2900.

**Comment by rickstaa** [comment] 2023-10-14 09:41
@anmolchhabra21 did you already start this, or can @airwakz take this issue on (see [this related issue](https://github.com/anuraghazra/github-readme-stats/issues/2900) for the pin card).

**Comment by qwerty541** [comment] 2023-10-26 07:54
@rickstaa Implementing full-fledged support of  `card_height` parameter is quite difficult task, i mean if not just changing height property of `Card` class, for proper implementation we should calculate position of all cards elements depending on the user specified height which can be too high or too low. In my opinion the more easier solution can be adding `description_lines_count` query parameter instead of `card_height`. It will be easier because count of description lines already taken into account during calculation of cards elemets position (https://github.com/anuraghazra/github-readme-stats/blob/master/src/cards/repo-card.js#L85-L91). Currently card shows up to three description lines, value of this new parameter will be clamped from 1 to 3, actual description lines count will have higher pririty than user specified. If user specified lines count will be higher than actual than empty strung will be added, it is just how built-in GitHub pins works. The only minus of this solution is unobvious API for users. Let me know what do you think.

**Comment by rickstaa** [comment] 2023-10-26 19:16
> @rickstaa Implementing full-fledged support of `card_height` parameter is quite difficult task, i mean if not just changing height property of `Card` class, for proper implementation we should calculate position of all cards elements depending on the user specified height which can be too high or too low. In my opinion the more easier solution can be adding `description_lines_count` query parameter instead of `card_height`. It will be easier because count of description lines already taken into account during calculation of cards elemets position (https://github.com/anuraghazra/github-readme-stats/blob/master/src/cards/repo-card.js#L85-L91). Currently card shows up to three description lines, value of this new parameter will be clamped from 1 to 3, actual description lines count will have higher pririty than user specified. If user specified lines count will be higher than actual than empty strung will be added, it is just how built-in GitHub pins works. The only minus of this solution is unobvious API for users. Let me know what do you think.

Your approach makes a lot of sense! Incorporating a height parameter can indeed be tricky with the dependency on `card_width`. I'm totally on board with your suggestion of allowing users to specify the number of description lines and automatically add a white line when it falls short of the user-defined setting. It's a smart solution that addresses the issue raised by @Extravi without overcomplicating the code. Thumbs up! 👍🏻

**Comment by qwerty541** [comment] 2023-10-29 04:12
> > @rickstaa Implementing full-fledged support of `card_height` parameter is quite difficult task, i mean if not just changing height property of `Card` class, for proper implementation we should calculate position of all cards elements depending on the user specified height which can be too high or too low. In my opinion the more easier solution can be adding `description_lines_count` query parameter instead of `card_height`. It will be easier because count of description lines already taken into account during calculation of cards elemets position (https://github.com/anuraghazra/github-readme-stats/blob/master/src/cards/repo-card.js#L85-L91). Currently card shows up to three description lines, value of this new parameter will be clamped from 1 to 3, actual description lines count will have higher pririty than user specified. If user specified lines count will be higher than actual than empty strung will be added, it is just how built-in GitHub pins works. The only minus of this solution is unobvious API for users. Let me know what do you think.
> 
> Your approach makes a lot of sense! Incorporating a height parameter can indeed be tricky with the dependency on `card_width`. I'm totally on board with your suggestion of allowing users to specify the number of description lines and automatically add a white line when it falls short of the user-defined setting. It's a smart solution that addresses the issue raised by @Extravi without overcomplicating the code. Thumbs up! 👍🏻

Thanks for your support! If that solution suits us, i think we can close all this issues/pull requests opened in recent days about adding `card_height` and `card_width` querystring parameters. In my opinion adding these parameters only gives user an ability to break the card, the result desired by @Extravi can be reached with `description_lines_count` parameter. I can implement it soon if you're up to merge it.

**Comment by Extravi** [comment] 2023-10-29 04:33
thanks

**Comment by rickstaa** [comment] 2023-11-01 14:41
> > > @rickstaa Implementing full-fledged support of `card_height` parameter is quite difficult task, i mean if not just changing height property of `Card` class, for proper implementation we should calculate position of all cards elements depending on the user specified height which can be too high or too low. In my opinion the more easier solution can be adding `description_lines_count` query parameter instead of `card_height`. It will be easier because count of description lines already taken into account during calculation of cards elemets position (https://github.com/anuraghazra/github-readme-stats/blob/master/src/cards/repo-card.js#L85-L91). Currently card shows up to three description lines, value of this new parameter will be clamped from 1 to 3, actual description lines count will have higher pririty than user specified. If user specified lines count will be higher than actual than empty strung will be added, it is just how built-in GitHub pins works. The only minus of this solution is unobvious API for users. Let me know what do you think.
> > 
> > 
> > Your approach makes a lot of sense! Incorporating a height parameter can indeed be tricky with the dependency on `card_width`. I'm totally on board with your suggestion of allowing users to specify the number of description lines and automatically add a white line when it falls short of the user-defined setting. It's a smart solution that addresses the issue raised by @Extravi without overcomplicating the code. Thumbs up! 👍🏻
> 
> Thanks for your support! If that solution suits us, i think we can close all this issues/pull requests opened in recent days about adding `card_height` and `card_width` querystring parameters. In my opinion adding these parameters only gives user an ability to break the card, the result desired by @Extravi can be reached with `description_lines_count` parameter. I can implement it soon if you're up to merge it.

While incorporating the card_width parameter appears reasonable, the presence of both raises concerns. My suggestion is to proceed with the card_width pull requests and dismiss the card_height counterparts, favoring the inclusion of the description_lines_count parameter.

**Comment by qwerty541** [comment] 2023-11-01 18:35
> > > > @rickstaa Implementing full-fledged support of `card_height` parameter is quite difficult task, i mean if not just changing height property of `Card` class, for proper implementation we should calculate position of all cards elements depending on the user specified height which can be too high or too low. In my opinion the more easier solution can be adding `description_lines_count` query parameter instead of `card_height`. It will be easier because count of description lines already taken into account during calculation of cards elemets position (https://github.com/anuraghazra/github-readme-stats/blob/master/src/cards/repo-card.js#L85-L91). Currently card shows up to three description lines, value of this new parameter will be clamped from 1 to 3, actual description lines count will have higher pririty than user specified. If user specified lines count will be higher than actual than empty strung will be added, it is just how built-in GitHub pins works. The only minus of this solution is unobvious API for users. Let me know what do you think.
> > > 
> > > 
> > > Your approach makes a lot of sense! Incorporating a height parameter can indeed be tricky with the dependency on `card_width`. I'm totally on board with your suggestion of allowing users to specify the number of description lines and automatically add a white line when it falls short of the user-defined setting. It's a smart solution that addresses the issue raised by @Extravi without overcomplicating the code. Thumbs up! 👍🏻
> > 
> > 
> > Thanks for your support! If that solution suits us, i think we can close all this issues/pull requests opened in recent days about adding `card_height` and `card_width` querystring parameters. In my opinion adding these parameters only gives user an ability to break the card, the result desired by @Extravi can be reached with `description_lines_count` parameter. I can implement it soon if you're up to merge it.
> 
> While incorporating the card_width parameter appears reasonable, the presence of both raises concerns. I suggest proceeding with the `card_width` pull requests and dismissing the `card_height` counterparts, favouring the inclusion of the `description_lines_count` parameter.

I suggested to reject addition of `card_width` and `card_height` in order to prevent bloating of querystring parameters count and reduce our future maintenance efforts since it is enough to add just one parameter to resolve current issue. If solution with `description_lines_count` suites us, i do not see any advantage in addition of parameters for configuring height and width and have doubts if we need both of them. I just can't imagine situation when manual changing of card height and width can be useful since in order to look good card should keep its original aspect ration and by breaking it card just will look worse.

**Comment by rickstaa** [comment] 2023-11-01 19:36
> > > > > @rickstaa Implementing full-fledged support of `card_height` parameter is quite difficult task, i mean if not just changing height property of `Card` class, for proper implementation we should calculate position of all cards elements depending on the user specified height which can be too high or too low. In my opinion the more easier solution can be adding `description_lines_count` query parameter instead of `card_height`. It will be easier because count of description lines already taken into account during calculation of cards elemets position (https://github.com/anuraghazra/github-readme-stats/blob/master/src/cards/repo-card.js#L85-L91). Currently card shows up to three description lines, value of this new parameter will be clamped from 1 to 3, actual description lines count will have higher pririty than user specified. If user specified lines count will be higher than actual than empty strung will be added, it is just how built-in GitHub pins works. The only minus of this solution is unobvious API for users. Let me know what do you think.
> > > > 
> > > > 
> > > > Your approach makes a lot of sense! Incorporating a height parameter can indeed be tricky with the dependency on `card_width`. I'm totally on board with your suggestion of allowing users to specify the number of description lines and automatically add a white line when it falls short of the user-defined setting. It's a smart solution that addresses the issue raised by @Extravi without overcomplicating the code. Thumbs up! 👍🏻
> > > 
> > > 
> > > Thanks for your support! If that solution suits us, i think we can close all this issues/pull requests opened in recent days about adding `card_height` and `card_width` querystring parameters. In my opinion adding these parameters only gives user an ability to break the card, the result desired by @Extravi can be reached with `description_lines_count` parameter. I can implement it soon if you're up to merge it.
> > 
> > 
> > While incorporating the card_width parameter appears reasonable, the presence of both raises concerns. I suggest proceeding with the `card_width` pull requests and dismissing the `card_height` counterparts, favouring the inclusion of the `description_lines_count` parameter.
> 
> I suggested to reject addition of `card_width` and `card_height` in order to prevent bloating of querystring parameters count and reduce our future maintenance efforts since it is enough to add just one parameter to resolve current issue. If solution with `description_lines_count` suites us, i do not see any advantage in addition of parameters for configuring height and width and have doubts if we need both of them. I just can't imagine situation when manual changing of card height and width can be useful since in order to look good card should keep its original aspect ration and by breaking it card just will look worse.

I suggested adding `card_width` since it is already in the stats and language card. But if there is no demand from the community, it doesn't make sense just to add it because of consistency.

**Comment by qwerty541** [comment] 2023-11-02 18:27
> > > > > > @rickstaa Implementing full-fledged support of `card_height` parameter is quite difficult task, i mean if not just changing height property of `Card` class, for proper implementation we should calculate position of all cards elements depending on the user specified height which can be too high or too low. In my opinion the more easier solution can be adding `description_lines_count` query parameter instead of `card_height`. It will be easier because count of description lines already taken into account during calculation of cards elemets position (https://github.com/anuraghazra/github-readme-stats/blob/master/src/cards/repo-card.js#L85-L91). Currently card shows up to three description lines, value of this new parameter will be clamped from 1 to 3, actual description lines count will have higher pririty than user specified. If user specified lines count will be higher than actual than empty strung will be added, it is just how built-in GitHub pins works. The only minus of this solution is unobvious API for users. Let me know what do you think.
> > > > > 
> > > > > 
> > > > > Your approach makes a lot of sense! Incorporating a height parameter can indeed be tricky with the dependency on `card_width`. I'm totally on board with your suggestion of allowing users to specify the number of description lines and automatically add a white line when it falls short of the user-defined setting. It's a smart solution that addresses the issue raised by @Extravi without overcomplicating the code. Thumbs up! 👍🏻
> > > > 
> > > > 
> > > > Thanks for your support! If that solution suits us, i think we can close all this issues/pull requests opened in recent days about adding `card_height` and `card_width` querystring parameters. In my opinion adding these parameters only gives user an ability to break the card, the result desired by @Extravi can be reached with `description_lines_count` parameter. I can implement it soon if you're up to merge it.
> > > 
> > > 
> > > While incorporating the card_width parameter appears reasonable, the presence of both raises concerns. I suggest proceeding with the `card_width` pull requests and dismissing the `card_height` counterparts, favouring the inclusion of the `description_lines_count` parameter.
> > 
> > 
> > I suggested to reject addition of `card_width` and `card_height` in order to prevent bloating of querystring parameters count and reduce our future maintenance efforts since it is enough to add just one parameter to resolve current issue. If solution with `description_lines_count` suites us, i do not see any advantage in addition of parameters for configuring height and width and have doubts if we need both of them. I just can't imagine situation when manual changing of card height and width can be useful since in order to look good card should keep its original aspect ration and by breaking it card just will look worse.
> 
> I suggested adding `card_width` since it is already in the stats and language card. But if there is no demand from the community, it doesn't make sense just to add it because of consistency.

I hae opened pull request https://github.com/anuraghazra/github-readme-stats/pull/3453 with addition of `description_lines_count` query parameter, please check it out. Here is a little preview:

Before:

<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-feature-15ab7c-github-readme-stats-team.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-feature-15ab7c-github-readme-stats-team.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask"/>
</a>
</div>

After:

<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-feature-15ab7c-github-readme-stats-team.vercel.app/api/pin/?username=rjyo&repo=Air-Test&description_lines_count=3"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats-git-feature-15ab7c-github-readme-stats-team.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask&description_lines_count=3"/>
</a>
</div>

**Closed** 2023-11-20 18:08 UTC
Labels: enhancement, repo-card, feature

**Comment by qwerty541** [comment] 2023-11-20 18:14
Pull request #3453 was merged, now equal height for different repositories cards can be achieved by the following way:

## Before:

```html
<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask"/>
</a>
</div>
```

<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=rjyo&repo=Air-Test"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask"/>
</a>
</div>

## After (`&description_lines_count=3`):

```html
<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=rjyo&repo=Air-Test&description_lines_count=3"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask&description_lines_count=3"/>
</a>
</div>
```

<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=rjyo&repo=Air-Test&description_lines_count=3"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask&description_lines_count=3"/>
</a>
</div>

## After (`&description_lines_count=1`):

```html
<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=rjyo&repo=Air-Test&description_lines_count=1"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask&description_lines_count=1"/>
</a>
</div>
```

<div align="center"> 
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=rjyo&repo=Air-Test&description_lines_count=1"/>
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=meako689&repo=FortyTwoTestTask&description_lines_count=1"/>
</a>
</div>
