### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by nikosdaridis** [anuraghazra/github-readme-stats#2890] opened 2023-06-28 06:40 UTC
### Describe the bug

When I visit my GitHub profile the cards don't load, I get broken images but if I refresh everything works fine for 1-2 hours until it happens again (I guess because it's cached).

### Screenshots / Live demo link

![Screenshot](https://github.com/anuraghazra/github-readme-stats/assets/101875554/37e4335a-7a9c-4206-bcd9-ecce775df94f)

### Additional context

It never happened when I was using the public Vercel but since I switched to using mine it happens every time. I tested it in Chrome, Mozilla both pc and mobile.

**Comment by rickstaa** [comment] 2023-06-28 07:22
This is a duplicate of https://github.com/anuraghazra/github-readme-stats/issues/2603 caused by a timeout in GitHub. It could be that functions execute faster on the Vercel pro plan used in the Public instance 🤔. The reason I think the problem is at GitHub's side is that if you reload the page, the cards often appear.

**Closed** 2023-06-28 07:23 UTC
Labels: bug
