### ISSUE TITLE
[BUG] - add an env variable called PAT_1 with your github token in vercel

### ISSUE THREAD

**Issue by yash251** [anuraghazra/github-readme-stats#2149] opened 2022-10-06 18:27 UTC
**Describe the bug**
Getting
```
Something went wrong! file an issue at https://tiny.one/readme-stats
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel
```

**Expected behaviour**
Need to show my stats

**Comment by NevilleMthw** [comment] 2022-10-06 18:28
Can confirm, just saw this error on my profile as well.

**Comment by yash251** [comment] 2022-10-06 18:47
Thanks for that @NevilleMthw

**Comment by rickstaa** [comment] 2022-10-06 19:53
Duplicate of #2130.

**Closed by rickstaa** 2022-10-06 19:53 UTC

**Comment by YulietM** [comment] 2023-01-06 15:41
hi
they should only add a variable increasing the token's

This is what I had with the error:
`    <a href="">
      <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/>
    </a>`

and adding (sigma-five) so it was solved:
`    <a href="">
      <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/>
    </a>`

**Comment by bewithkomalkumar** [comment] 2023-01-09 16:17
problem resolved thanks!

**Comment by KayvanShah1** [comment] 2023-01-13 20:47
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

Issue resolved... Thanks!

**Comment by raysylverne** [comment] 2023-01-14 14:39
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

 Problem Resolved thanks @YulietM

**Comment by redolfosei** [comment] 2023-01-14 19:50
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

This was helpful. thanks for sharing.

**Comment by rickstaa** [comment] 2023-01-14 20:34
> > hi they should only add a variable increasing the token's
> > This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> > and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> This was helpful. thanks for sharing.

We solved the problem on the master branch. You can therefore switch back to the public Vercel instance or deploy a Vercel instance yourself. If to many people switch to @sigma-five's branch that instance will likely reach GitHub's rate limits. 😅

**Comment by OtabekVaxobov** [comment] 2023-01-18 05:06
big thank you

**Comment by bbring2** [comment] 2023-01-18 15:41
Thanks! resolved as well :-)

**Comment by Oracle728** [comment] 2023-01-19 12:42
Thank you, everybody.

**Comment by guilhermeDTNA** [comment] 2023-01-19 14:49
@YulietM perfect! Thanks.

**Comment by Cocowwy** [comment] 2023-01-20 03:05
> 

TKS

**Comment by Cocowwy** [comment] 2023-01-20 03:06
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

TKS

**Comment by andressaribeiroo** [comment] 2023-01-20 16:54
> oi , eles devem apenas adicionar uma variável aumentando o token
> 
> Isso é o que eu tive com o erro: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> e somando (sigma-cinco) assim ficou resolvido: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

Muito obrigada  :)

**Comment by Kolpashnikova** [comment] 2023-01-24 17:19
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

this helped, thank you!

**Comment by vaiibhavkale** [comment] 2023-03-02 15:48
> 

Thankyou...this solved my problem

**Comment by edmilsonmedeiross** [comment] 2023-03-02 17:19
thank you, this solved my problem to

**Comment by MdFahimShahriarFahim** [comment] 2023-03-08 16:24
thank you guys, the bug is solved.

**Comment by Jeferson0Silva** [comment] 2023-03-09 16:29
@YulietM Thanks.

**Comment by sarjataziz** [comment] 2023-03-16 15:05
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

Thanks. Problem solved.

**Comment by kleberfdev** [comment] 2023-03-20 14:59
Something went wrong! file an issue at https://tiny.one/readme-stats
Maximum retries exceeded Please add an env variable called PAT_1 with your github token in vercel

**Comment by LucasXXI** [comment] 2023-03-28 18:08
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

thanks! solved here.

**Comment by abdolazizsalimi** [comment] 2023-03-28 20:37
thanks, well done

**Comment by Roberton003** [comment] 2023-04-04 18:26
Excelente!!! o Erro é corrigido com adição de **"-sigma-five" **no trecho de "github-readme-stats.vercel.app". Ficando desse forma:
**github-readme-stats-sigma-five.vercel.app**

**Comment by GusDev0** [comment] 2023-05-03 14:13
very thanks

**Comment by ManuelaFran** [comment] 2023-05-04 18:34
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

Thaks! 💯

**Comment by Rezakazemi890** [comment] 2023-05-09 15:15
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

Thanks! 🙏

**Comment by night-slayer18** [comment] 2023-05-29 14:24
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

thanks man

**Comment by tejanshsachdeva** [comment] 2023-05-31 18:29
Issue Resolved. Thanks bud. Any idea how you draw this conclusion?

**Comment by jdevstatic** [comment] 2023-06-11 09:33
back then, there was the suggestion 

`https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app`

now, I'm restoring it to the original 

`https://github-readme-stats.vercel.app`

and it's working again

**Comment by pinkovay** [comment] 2023-07-10 19:59
> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`



> hi they should only add a variable increasing the token's
> 
> This is what I had with the error: ` <a href=""> <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`
> 
> and adding (sigma-five) so it was solved: ` <a href=""> <img align="center" src="https://github-readme-stats-sigma-five.vercel.app/api/top-langs/?username=YulietM&theme=react&line_height=40&hide=css"/> </a>`

Thanks!! 🙌

**Comment by ManjeshYdv** [comment] 2023-09-08 17:14
This Problem is occurs due to change in username=" " so check the username 
Problem
<p><img align="left" src="https://github-readme-stats.vercel.app/api/top-langs?username=manjeshydv&show_icons=true&locale=en&layout=compact" alt="manjeshydv" /></p>

solution
By changing  manjeshydv to manjeshYdv

<p><img align="left" src="https://github-readme-stats.vercel.app/api/top-langs?username=manjeshYdv&show_icons=true&locale=en&layout=compact" alt="manjeshYdv" /></p>



just adding your correct user name it will display it again

**Comment by qwerty541** [comment] 2023-09-09 12:07
Hi, @ManjeshYdv! The case of username does not affect on this problem. You can see this error message during public instance downtime cause by underlying GitHub API rate limits. To avoid this problem you can [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#on-vercel) using own GitHub API token or wait until public instance will be longer available. Changing username helped you most likely because changing URL breaks cache.
