### ISSUE TITLE
Maximum retries exceeded

### ISSUE THREAD

**Issue by sriramgroot** [anuraghazra/github-readme-stats#2114] opened 2022-10-04 12:42 UTC
**Describe the bug**
Iam trying to create a github readme statistics, but its throwing a error as **"Something went wrong!"**

**Expected behaviour**
It should be properly showing my github statistics without any issues

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
<img width="860" alt="Screenshot 2022-10-04 at 6 09 08 PM" src="https://user-images.githubusercontent.com/58930932/193821598-8d5253b7-12ae-4f99-b4f2-9a1dd6bcc133.png">

**Additional context**
Link used to show the statistics. [Click here](https://github-readme-stats.vercel.app/api?username=sriramgroot&show_icons=true&hide_border=true&bg_color=040d21&title_color=165df5&icon_color=165df5&text_color=FFFFFF)

**Comment by rickstaa** [comment] 2022-10-04 12:47
Thanks for letting us know. It is related to https://github.com/anuraghazra/github-readme-stats/issues/1471. We are aware of the issue.

**Comment by sriramgroot** [comment] 2022-10-04 12:51
> Thanks for letting us know. It is related to #1471. We are aware of the issue.

Thanks for the reply @rickstaa. once it is fixed please let us know.

**Comment by Aatmaj-Zephyr** [comment] 2022-10-04 13:03
Also commits are showing lesser than the prev values...

**Comment by rickstaa** [comment] 2022-10-04 14:07
This should be fixed.

**Comment by docimin** [comment] 2022-10-04 16:26
Same!

**Comment by emjose** [comment] 2022-10-04 16:55
> Hi Rick, just letting you know I'm experiencing this issue, before and after this comment. 🙂
> 
> > This should be fixed.

Same, as of 12:55 PM EDT.

**Comment by veD-tnayrB** [comment] 2022-10-04 16:59
Same here!

**Comment by JT122406** [comment] 2022-10-04 17:01
yup

**Comment by rickstaa** [comment] 2022-10-04 17:03
Your right. I think @anuraghazra still needs to update the PATs. I will let him close this issue when the issue is fixed.

**Comment by kaviranga** [comment] 2022-10-04 17:06
I have get the same issue !

Maximum retries exceeded !

**Comment by HarshalCODE** [comment] 2022-10-04 17:30
Same Issue !

**Comment by rickstaa** [comment] 2022-10-04 17:36
We are working on it progress can be followed in #1471.

**Comment by rickstaa** [comment] 2022-10-04 23:00
Should be fixed for now.

**Closed by rickstaa** 2022-10-04 23:00 UTC
Labels: bug, upstream

**Comment by Gchism94** [comment] 2022-10-05 18:14
Same problem with `theme=dark` parameter.

**Comment by rickstaa** [comment] 2022-10-05 18:23
> Same problem with `theme=dark` parameter.

I think that problem is mainly caused by the fact that we cache the cards to reduce server load. You can break this behavior by adding a random query parameter `&random=&randomss524272`. In the future, I will probably create a PR to change this behavior for the case that the cards fails to fetch data.

**Comment by Gchism94** [comment] 2022-10-05 18:38
> > Same problem with `theme=dark` parameter.
> 
> I think that problem is mainly caused by the fact that we cache the cards to reduce server load. You can break this behavior by adding a random query parameter `&random=&randomss524272`. In the future, I will probably create a PR to change this behavior for the case that the cards fails to fetch data.

That worked, but I notably had to add `&random=&randomss524272` before `&theme=dark`. Thanks!
