### ISSUE TITLE
Text overlap on the number in Total Commits in the stats card

### ISSUE THREAD

**Issue by afif1400** [anuraghazra/github-readme-stats#1106] opened 2021-06-02 09:28 UTC
**Describe the bug**
The left column name **Total Commits (2021)** in the card is overlapping with the number.

**Expected behavior**
There must be a margin between the two columns.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![issue-stats](https://user-images.githubusercontent.com/51887071/120455767-ab45b780-c3b2-11eb-99ac-cbb64f9b26cb.png)

**Comment by rickstaa** [comment] 2022-03-09 08:08
@afif1400 Judging from your profile, it looks like the problem is fixed? I will close this for now. I am happy to re-open if people can provide some steps to reproduce the issue.

**Closed by rickstaa** 2022-03-09 08:08 UTC
