### ISSUE TITLE
Stats Image not loading properly in github app

### ISSUE THREAD

**Issue by ksdkamesh99** [anuraghazra/github-readme-stats#782] opened 2021-01-04 15:37 UTC
**Describe the bug**
In GitHub mobile app version when I am loading my profile then the stats image associated with the readme is not displaying properly

**Expected behavior**
It should load all the stats in the image

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

I am hereby attaching the screenshots 

![image](https://user-images.githubusercontent.com/46109386/103551747-d2b25a00-4ed0-11eb-9642-ebcd38851b21.png)

**Additional context**

I hope it will be solved soon

**Comment by anuraghazra** [comment] 2021-01-04 17:04
duplicate of #776 #215

**Closed by anuraghazra** 2021-01-04 17:04 UTC
