### ISSUE TITLE
Provide most used languages statistics for private repo

### ISSUE THREAD

**Issue by itxcjm** [anuraghazra/github-readme-stats#2515] opened 2023-02-13 04:22 UTC
### Is your feature request related to a problem? Please describe.

Provide most used languages statistics for private repo.

**Comment by Zo-Bro-23** [comment] 2023-02-13 04:32
Duplicate of #2478.

**Closed by Zo-Bro-23** 2023-02-13 04:32 UTC
Labels: enhancement

**Comment by itxcjm** [comment] 2023-02-13 05:10
But it is not most used languages.

**Comment by Zo-Bro-23** [comment] 2023-02-13 05:55
Well, it is. See the two cards below:
![](https://github-readme-stats.zohan.tech/api/top-langs?username=Zo-Bro-23&theme=onedark&hide_border=true)
![](https://github-readme-stats.vercel.app/api/top-langs?username=Zo-Bro-23&theme=onedark&hide_border=true)

The first one is my deployment, and the second one is the public Vercel instance. These show slightly different stats because my deployment counts my private repos too. The solution @rickstaa mentioned - to deploy your own instance - will work for the most used languages card too.

**Comment by itxcjm** [comment] 2023-02-14 10:34
I have been deploying this project myself,but it dosn't work

**Comment by itxcjm** [comment] 2023-02-14 10:35
Is the token need some scopes?

**Comment by Zo-Bro-23** [comment] 2023-02-14 10:41
> Is the token need some scopes?

Repo permissions with private repos enabled should work.

**Comment by itxcjm** [comment] 2023-02-15 04:59
Thank you, it works!
